/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            /**
             * @description machine-readable error code (e.g. "auth.invalid_token")
             * @example auth.invalid_token
             */
            error: string;
            /**
             * @description human-readable error message
             * @example invalid token
             */
            message: string;
            /**
             * @description Optional structured context for the error. Shape is
             *     code-specific; omitted when there is nothing to add.
             */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description missing or invalid bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description authenticated but not permitted for the requested operation */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description requested route or resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
