/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a refresh token for a new access+refresh pair */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a token (or all tokens for the account) */
        post: operations["revokeToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin OAuth authorization flow — returns the provider authorize URL */
        post: operations["startOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange OAuth authorization code for a portal token pair */
        post: operations["oauthCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/magic-link/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a magic-link sign-in email */
        post: operations["requestMagicLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/magic-link/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a magic-link token for a portal token pair */
        post: operations["exchangeMagicLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the authenticated account's profile and org memberships */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new org; the authenticated account becomes its creator */
        post: operations["createOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{orgID}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members of an org (requires creator or member role) */
        get: operations["listOrgMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{orgID}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an org invite (requires creator role); sends email to recipient */
        post: operations["createOrgInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{orgID}/invites/{inviteID}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a pending org invite (requires Bearer; verifies token + recipient email) */
        post: operations["acceptOrgInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{orgID}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new session in the org; the authenticated account becomes the creator */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{orgID}/sessions/{sessionID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update goal, scope (widening only), or default_mode; creator only */
        patch: operations["patchSession"];
        trace?: never;
    };
    "/api/orgs/{orgID}/sessions/{sessionID}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition session to finalizing; idempotent if already finalizing */
        post: operations["finalizeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{orgID}/sessions/{sessionID}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abandon the session without finalizing; sets status=ended, end_reason=abandoned; creator only */
        post: operations["abandonSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            /**
             * @description machine-readable error code (e.g. "auth.invalid_token")
             * @example auth.invalid_token
             */
            error: string;
            /**
             * @description human-readable error message
             * @example invalid token
             */
            message: string;
            /**
             * @description Optional structured context for the error. Shape is
             *     code-specific; omitted when there is nothing to add.
             */
            details?: {
                [key: string]: unknown;
            };
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
            /** Format: date-time */
            access_expires_at: string;
            /** Format: date-time */
            refresh_expires_at: string;
        };
        MagicLinkRequestBody: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
        };
        OAuthStartBody: {
            /**
             * @description OAuth provider name, e.g. "github"
             * @example github
             */
            provider: string;
        };
        OAuthStartResponse: {
            /** @description Provider authorization URL the browser should be redirected to */
            authorize_url: string;
        };
        OAuthCallbackBody: {
            /**
             * @description OAuth provider name, e.g. "github"
             * @example github
             */
            provider: string;
            /** @description Authorization code from the provider */
            code: string;
            /** @description State nonce echoed back from the provider */
            state: string;
        };
        MagicLinkExchangeBody: {
            /** @description Raw magic-link token from the URL query parameter */
            token: string;
        };
        EventEnvelope: {
            /**
             * Format: int64
             * @description Monotonic per-session sequence number
             */
            seq: number;
            /**
             * @description Envelope version; always 1
             * @enum {integer}
             */
            version: 1;
            /**
             * @description Event type; used as discriminator for payload
             * @enum {string}
             */
            type: "commit.arrived" | "merge.succeeded" | "conflict.detected" | "conflict.resolved" | "comment.added" | "comment.resolved" | "ref.forked" | "mode.changed" | "turn.ended" | "presence.updated" | "session.finalizing" | "session.ended";
            /**
             * Format: date-time
             * @description ISO-8601 timestamp of event emission
             */
            timestamp: string;
            /** @description Session this event belongs to */
            session_id: string;
            payload: components["schemas"]["CommitArrivedPayload"] | components["schemas"]["MergeSucceededPayload"] | components["schemas"]["ConflictDetectedPayload"] | components["schemas"]["ConflictResolvedPayload"] | components["schemas"]["CommentAddedPayload"] | components["schemas"]["CommentResolvedPayload"] | components["schemas"]["RefForkedPayload"] | components["schemas"]["ModeChangedPayload"] | components["schemas"]["TurnEndedPayload"] | components["schemas"]["PresenceUpdatedPayload"] | components["schemas"]["SessionFinalizingPayload"] | components["schemas"]["SessionEndedPayload"];
        };
        /** @description A commit was pushed to a session ref. PROTOCOL.md canonical fields: ref, sha, author_id, summary. */
        CommitArrivedPayload: {
            /** @description The session ref the commit landed on (e.g. jam/<session>/<user>/<branch>) */
            ref: string;
            /** @description The commit SHA that arrived */
            sha: string;
            /** @description Account ID of the commit author */
            author_id: string;
            /** @description One-line summary of the commit message */
            summary: string;
        };
        /** @description Auto-merger successfully merged a source commit into the draft tip. PROTOCOL.md canonical fields: source_sha, draft_sha, merge_commit_sha. */
        MergeSucceededPayload: {
            /** @description The source commit SHA that was merged */
            source_sha: string;
            /** @description The draft tip SHA after the merge */
            draft_sha: string;
            /** @description The merge commit SHA created by the auto-merger */
            merge_commit_sha: string;
        };
        ConflictFileRange: {
            /** @description Start line (1-indexed) of the conflict range */
            start: number;
            /** @description End line (1-indexed) of the conflict range */
            end: number;
        };
        ConflictFile: {
            /** @description File path within the repository */
            file: string;
            /** @description Line ranges in conflict within this file */
            ranges: components["schemas"]["ConflictFileRange"][];
        };
        /** @description Auto-merger detected a three-way merge conflict. Payload is the full conflict event per PROTOCOL.md conflict event schema. PROTOCOL.md canonical fields: id, session_id, source_commit_sha, source_ref, draft_tip_sha, ancestor_sha, conflicts, addressed_to, status, resolving_commit_sha, resolved_at, created_at. */
        ConflictDetectedPayload: {
            /** @description Conflict event ID (UUID) */
            id: string;
            /** @description Session the conflict belongs to */
            session_id: string;
            /** @description The commit that could not be merged */
            source_commit_sha: string;
            /** @description The ref the source commit came from */
            source_ref: string;
            /** @description The draft tip at the time of the failed merge attempt */
            draft_tip_sha: string;
            /** @description The common ancestor commit SHA */
            ancestor_sha: string;
            /** @description Per-file conflict details */
            conflicts: components["schemas"]["ConflictFile"][];
            /** @description Addressing tokens for impacted participants (e.g. "@user/branch") */
            addressed_to: string[];
            /**
             * @description Current status of this conflict
             * @enum {string}
             */
            status: "open" | "resolved" | "abandoned";
            /** @description Set when a Resolves-Conflict trailer matches this event */
            resolving_commit_sha?: string | null;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp when the conflict was resolved
             */
            resolved_at?: string | null;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp when the conflict was detected
             */
            created_at: string;
        };
        /** @description A conflict has been resolved via a commit with a matching Resolves-Conflict trailer. PROTOCOL.md canonical fields: event_id, resolving_commit_sha. */
        ConflictResolvedPayload: {
            /** @description The conflict event ID that was resolved */
            event_id: string;
            /** @description The commit SHA that resolved the conflict */
            resolving_commit_sha: string;
        };
        CommentAnchor: {
            /** @description The commit being commented on */
            commit_sha: string;
            /** @description File within the commit's tree; null for commit-level comments */
            file_path?: string | null;
            /** @description 1-indexed line range; null for file-level or commit-level comments */
            line_range?: components["schemas"]["ConflictFileRange"] | null;
        };
        /** @description A comment was posted in the session. Payload is the full comment per PROTOCOL.md comment schema. PROTOCOL.md canonical fields: id, session_id, author_id, author_kind, anchor, body, addressed_to, kind, created_at, resolved_at, resolved_by, resolution_note. */
        CommentAddedPayload: {
            /** @description Comment ID (UUID) */
            id: string;
            /** @description Session the comment belongs to */
            session_id: string;
            /** @description Account ID of the comment author */
            author_id: string;
            /**
             * @description Whether the author is a human or an agent
             * @enum {string}
             */
            author_kind: "human" | "agent";
            anchor: components["schemas"]["CommentAnchor"];
            /** @description Comment body in markdown */
            body: string;
            /** @description Addressing token (e.g. "@user", "@user/branch", "@all-agents") */
            addressed_to?: string | null;
            /**
             * @description Comment kind
             * @enum {string}
             */
            kind: "fyi" | "question" | "suggestion" | "action-request";
            /**
             * Format: date-time
             * @description ISO-8601 timestamp of creation
             */
            created_at: string;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp when resolved; null if open
             */
            resolved_at?: string | null;
            /** @description Account ID of resolver; null if open */
            resolved_by?: string | null;
            /** @description Optional resolution note */
            resolution_note?: string | null;
        };
        /** @description A comment was marked resolved. PROTOCOL.md canonical fields: comment_id, resolved_by, note. */
        CommentResolvedPayload: {
            /** @description The comment ID that was resolved */
            comment_id: string;
            /** @description Account ID of the user who resolved the comment */
            resolved_by: string;
            /** @description Optional resolution note */
            note?: string | null;
        };
        /** @description A participant forked a new session ref. PROTOCOL.md canonical fields: ref, parent_sha, mode. */
        RefForkedPayload: {
            /** @description The new ref name (e.g. jam/<session>/<user>/<branch>) */
            ref: string;
            /** @description The commit SHA the new ref was parented at */
            parent_sha: string;
            /** @description The collaboration mode of the new ref (sync or isolated) */
            mode: string;
        };
        /** @description A ref's collaboration mode was changed. PROTOCOL.md canonical fields: ref, old_mode, new_mode. */
        ModeChangedPayload: {
            /** @description The ref whose mode changed */
            ref: string;
            /** @description The previous mode */
            old_mode: string;
            /** @description The new mode */
            new_mode: string;
        };
        /** @description A participant's turn ended; they yielded control back to the human. PROTOCOL.md canonical fields: user_id, ref, final_sha. */
        TurnEndedPayload: {
            /** @description Account ID of the participant whose turn ended */
            user_id: string;
            /** @description The ref the participant was working on */
            ref: string;
            /** @description The final commit SHA on the ref at turn end */
            final_sha: string;
        };
        /** @description A participant's presence (active ref + tip SHA) was updated. PROTOCOL.md canonical fields: user_id, ref, current_sha, last_active. */
        PresenceUpdatedPayload: {
            /** @description Account ID of the participant */
            user_id: string;
            /** @description The ref the participant is currently on */
            ref: string;
            /** @description The current tip SHA of the participant's ref */
            current_sha: string;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp of last participant activity
             */
            last_active: string;
        };
        /** @description A session has entered the finalizing state. PROTOCOL.md canonical fields: by_user_id. */
        SessionFinalizingPayload: {
            /** @description Account ID of the participant who initiated finalization */
            by_user_id: string;
        };
        /** @description A session has ended (finalized, abandoned, or timed out). PROTOCOL.md canonical fields: reason. */
        SessionEndedPayload: {
            /**
             * @description The reason the session ended
             * @enum {string}
             */
            reason: "finalize" | "abandon" | "timeout";
        };
        MeOrgMembership: {
            /**
             * @description Org UUID
             * @example 01926e42-0000-7000-a000-000000000001
             */
            id: string;
            /**
             * @description Org display name
             * @example acme
             */
            name: string;
            /**
             * @description URL-safe org slug
             * @example acme
             */
            slug: string;
            /**
             * @description The authenticated account's role in this org
             * @example creator
             */
            role: string;
        };
        MeResponse: {
            /**
             * @description Account UUID
             * @example 01926e42-0000-7000-a000-000000000000
             */
            id: string;
            /**
             * Format: email
             * @description Verified email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description Human-readable display name
             * @example Ada Lovelace
             */
            display_name: string;
            /** @description All org memberships for this account */
            orgs: components["schemas"]["MeOrgMembership"][];
        };
        OrgRef: {
            /**
             * @description Org UUID
             * @example 01926e42-0000-7000-a000-000000000001
             */
            id: string;
            /**
             * @description Org display name
             * @example acme
             */
            name: string;
            /**
             * @description URL-safe org slug
             * @example acme
             */
            slug: string;
        };
        CreateOrgBody: {
            /**
             * @description Desired org name; used to derive the slug
             * @example acme
             */
            name: string;
        };
        MemberRef: {
            /**
             * @description Account UUID
             * @example 01926e42-0000-7000-a000-000000000000
             */
            account_id: string;
            /**
             * Format: email
             * @description Member's email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description Member's display name
             * @example Ada Lovelace
             */
            display_name: string;
            /**
             * @description Member's role in the org
             * @example member
             */
            role: string;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp when the member joined the org
             */
            joined_at: string;
        };
        InviteBody: {
            /**
             * Format: email
             * @description Email address to invite
             * @example invitee@example.com
             */
            email: string;
        };
        InviteRef: {
            /**
             * @description Invite ID
             * @example 01926e42-0000-7000-a000-000000000002
             */
            id: string;
            /**
             * Format: email
             * @description Email address the invite was sent to
             * @example invitee@example.com
             */
            recipient_email: string;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp when the invite expires
             */
            expires_at: string;
        };
        AcceptInviteBody: {
            /** @description Raw invite token from the email link query parameter */
            token: string;
        };
        MemberSummary: {
            /**
             * @description Account UUID
             * @example 01926e42-0000-7000-a000-000000000000
             */
            account_id: string;
            /**
             * @description Member's role in the session (creator or member)
             * @example creator
             */
            role: string;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp when the member joined the session
             */
            joined_at: string;
        };
        Session: {
            /**
             * @description Session UUID
             * @example 01926e42-0000-7000-a000-000000000010
             */
            id: string;
            /**
             * @description Owning org UUID
             * @example 01926e42-0000-7000-a000-000000000001
             */
            org_id: string;
            /**
             * @description Short display name for the session
             * @example Fix auth bug
             */
            name: string;
            /**
             * @description Free-text description of the session's objective
             * @example Resolve the token refresh race condition in auth middleware
             */
            goal: string;
            /**
             * @description JSON array of path glob strings defining the writable scope
             * @example ["src/auth/**","tests/auth/**"]
             */
            scope: string;
            /**
             * @description Default ref mode for session participants
             * @example sync
             * @enum {string}
             */
            default_mode: "sync" | "isolated";
            /**
             * @description Lifecycle status of the session
             * @example active
             * @enum {string}
             */
            status: "active" | "finalizing" | "ended" | "archived";
            /** @description The base commit SHA this session branched from; null until first push */
            base_sha?: string | null;
            /**
             * @description Why the session ended; null while active
             * @example abandoned
             */
            end_reason?: string | null;
            /** @description Account ID holding the finalize-flow lock; null when unlocked */
            finalize_locked_by_account_id?: string | null;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp when the session was created
             */
            created_at: string;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp when the session ended; null while active
             */
            ended_at?: string | null;
            /** @description Current session members */
            members: components["schemas"]["MemberSummary"][];
        };
        CreateSessionRequest: {
            /**
             * @description Short display name for the session
             * @example Fix auth bug
             */
            name: string;
            /**
             * @description Free-text description of the session's objective
             * @example Resolve the token refresh race condition in auth middleware
             */
            goal: string;
            /**
             * @description JSON array of path glob strings defining the writable scope
             * @example ["src/auth/**","tests/auth/**"]
             */
            scope: string;
            /**
             * @description Default ref mode for session participants
             * @example sync
             * @enum {string}
             */
            default_mode: "sync" | "isolated";
        };
        /**
         * @description Fields that can be updated on an active session. All fields are optional;
         *     only present fields are updated. Scope is append-only (narrowing is rejected).
         */
        PatchSessionRequest: {
            /**
             * @description Updated session goal
             * @example Also fix the logout path
             */
            goal?: string;
            /**
             * @description Updated JSON array of path globs. Must be a superset of the current scope
             *     (scope narrowing is rejected with 400 session.scope_narrowing_rejected).
             * @example ["src/auth/**","tests/auth/**","src/logout/**"]
             */
            scope?: string;
            /**
             * @description Updated default ref mode
             * @enum {string}
             */
            default_mode?: "sync" | "isolated";
        };
    };
    responses: {
        /** @description missing or invalid bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description authenticated but not permitted for the requested operation */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description requested route or resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description New token pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    /** @default false */
                    revoke_all?: boolean;
                };
            };
        };
        responses: {
            /** @description Revocation complete */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    startOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthStartBody"];
            };
        };
        responses: {
            /** @description Authorization URL ready for browser redirect */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthStartResponse"];
                };
            };
            /** @description Unknown or unconfigured provider */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Provider not configured on this server */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    oauthCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthCallbackBody"];
            };
        };
        responses: {
            /** @description Token pair issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Invalid or expired state nonce, or provider mismatch */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    requestMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkRequestBody"];
            };
        };
        responses: {
            /** @description Magic link email sent (or silently accepted if address unknown) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error (email delivery failure) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    exchangeMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkExchangeBody"];
            };
        };
        responses: {
            /** @description Token pair issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account info with org memberships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgBody"];
            };
        };
        responses: {
            /** @description Org created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgRef"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listOrgMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org ID */
                orgID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of org members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRef"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createOrgInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org ID */
                orgID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteBody"];
            };
        };
        responses: {
            /** @description Invite created; email sent to recipient */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteRef"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    acceptOrgInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org ID */
                orgID: string;
                /** @description Invite ID */
                inviteID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteBody"];
            };
        };
        responses: {
            /** @description Invite accepted; account bound as org member */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgRef"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Invite already accepted */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org ID */
                orgID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    patchSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org ID */
                orgID: string;
                /** @description Session ID */
                sessionID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchSessionRequest"];
            };
        };
        responses: {
            /** @description Session updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Scope narrowing rejected or invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    finalizeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org ID */
                orgID: string;
                /** @description Session ID */
                sessionID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session is finalizing (or was already finalizing) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Session has already ended */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    abandonSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org ID */
                orgID: string;
                /** @description Session ID */
                sessionID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session abandoned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Session has already ended */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
