// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package pgstore

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, email, display_name, github_user_id, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, display_name, github_user_id, created_at
`

type CreateAccountParams struct {
	ID           string      `json:"id"`
	Email        string      `json:"email"`
	DisplayName  string      `json:"display_name"`
	GithubUserID pgtype.Text `json:"github_user_id"`
	CreatedAt    time.Time   `json:"created_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.GithubUserID,
		arg.CreatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.GithubUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, display_name, github_user_id, created_at
FROM accounts
WHERE email = $1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.GithubUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByGitHubUserID = `-- name: GetAccountByGitHubUserID :one
SELECT id, email, display_name, github_user_id, created_at
FROM accounts
WHERE github_user_id = $1
`

func (q *Queries) GetAccountByGitHubUserID(ctx context.Context, githubUserID pgtype.Text) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByGitHubUserID, githubUserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.GithubUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, display_name, github_user_id, created_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.GithubUserID,
		&i.CreatedAt,
	)
	return i, err
}

const updateAccountDisplayName = `-- name: UpdateAccountDisplayName :exec
UPDATE accounts
SET display_name = $1
WHERE id = $2
`

type UpdateAccountDisplayNameParams struct {
	DisplayName string `json:"display_name"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateAccountDisplayName(ctx context.Context, arg UpdateAccountDisplayNameParams) error {
	_, err := q.db.Exec(ctx, updateAccountDisplayName, arg.DisplayName, arg.ID)
	return err
}
