// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: archived_sessions.sql

package pgstore

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArchivedSession = `-- name: GetArchivedSession :one
SELECT session_id, org_id, name, goal_text, member_account_ids, ended_at, archived_at, end_reason, final_branch_name
FROM archived_sessions
WHERE org_id = $1 AND session_id = $2
`

type GetArchivedSessionParams struct {
	OrgID     string `json:"org_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) GetArchivedSession(ctx context.Context, arg GetArchivedSessionParams) (ArchivedSession, error) {
	row := q.db.QueryRow(ctx, getArchivedSession, arg.OrgID, arg.SessionID)
	var i ArchivedSession
	err := row.Scan(
		&i.SessionID,
		&i.OrgID,
		&i.Name,
		&i.GoalText,
		&i.MemberAccountIds,
		&i.EndedAt,
		&i.ArchivedAt,
		&i.EndReason,
		&i.FinalBranchName,
	)
	return i, err
}

const insertArchivedSession = `-- name: InsertArchivedSession :exec
INSERT INTO archived_sessions (session_id, org_id, name, goal_text, member_account_ids, ended_at, archived_at, end_reason, final_branch_name)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertArchivedSessionParams struct {
	SessionID        string             `json:"session_id"`
	OrgID            string             `json:"org_id"`
	Name             string             `json:"name"`
	GoalText         string             `json:"goal_text"`
	MemberAccountIds string             `json:"member_account_ids"`
	EndedAt          *time.Time         `json:"ended_at"`
	ArchivedAt       pgtype.Timestamptz `json:"archived_at"`
	EndReason        string             `json:"end_reason"`
	FinalBranchName  pgtype.Text        `json:"final_branch_name"`
}

func (q *Queries) InsertArchivedSession(ctx context.Context, arg InsertArchivedSessionParams) error {
	_, err := q.db.Exec(ctx, insertArchivedSession,
		arg.SessionID,
		arg.OrgID,
		arg.Name,
		arg.GoalText,
		arg.MemberAccountIds,
		arg.EndedAt,
		arg.ArchivedAt,
		arg.EndReason,
		arg.FinalBranchName,
	)
	return err
}
