// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: conflict_events.sql

package pgstore

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConflictEventByID = `-- name: GetConflictEventByID :one
SELECT id, org_id, session_id, source_commit, draft_tip, ancestor,
       conflicts, addressed_to, status, resolving_commit_sha, created_at, resolved_at
FROM conflict_events
WHERE id = $1
`

func (q *Queries) GetConflictEventByID(ctx context.Context, id string) (ConflictEvent, error) {
	row := q.db.QueryRow(ctx, getConflictEventByID, id)
	var i ConflictEvent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SessionID,
		&i.SourceCommit,
		&i.DraftTip,
		&i.Ancestor,
		&i.Conflicts,
		&i.AddressedTo,
		&i.Status,
		&i.ResolvingCommitSha,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const insertConflictEvent = `-- name: InsertConflictEvent :exec
INSERT INTO conflict_events (
    id, org_id, session_id, source_commit, draft_tip, ancestor,
    conflicts, addressed_to, status, resolving_commit_sha, created_at, resolved_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertConflictEventParams struct {
	ID                 string             `json:"id"`
	OrgID              string             `json:"org_id"`
	SessionID          string             `json:"session_id"`
	SourceCommit       string             `json:"source_commit"`
	DraftTip           string             `json:"draft_tip"`
	Ancestor           string             `json:"ancestor"`
	Conflicts          string             `json:"conflicts"`
	AddressedTo        string             `json:"addressed_to"`
	Status             string             `json:"status"`
	ResolvingCommitSha pgtype.Text        `json:"resolving_commit_sha"`
	CreatedAt          time.Time          `json:"created_at"`
	ResolvedAt         pgtype.Timestamptz `json:"resolved_at"`
}

func (q *Queries) InsertConflictEvent(ctx context.Context, arg InsertConflictEventParams) error {
	_, err := q.db.Exec(ctx, insertConflictEvent,
		arg.ID,
		arg.OrgID,
		arg.SessionID,
		arg.SourceCommit,
		arg.DraftTip,
		arg.Ancestor,
		arg.Conflicts,
		arg.AddressedTo,
		arg.Status,
		arg.ResolvingCommitSha,
		arg.CreatedAt,
		arg.ResolvedAt,
	)
	return err
}

const listOpenConflictEventsForSession = `-- name: ListOpenConflictEventsForSession :many
SELECT id, org_id, session_id, source_commit, draft_tip, ancestor,
       conflicts, addressed_to, status, resolving_commit_sha, created_at, resolved_at
FROM conflict_events
WHERE session_id = $1 AND status = 'open'
ORDER BY created_at ASC
`

func (q *Queries) ListOpenConflictEventsForSession(ctx context.Context, sessionID string) ([]ConflictEvent, error) {
	rows, err := q.db.Query(ctx, listOpenConflictEventsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConflictEvent
	for rows.Next() {
		var i ConflictEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SessionID,
			&i.SourceCommit,
			&i.DraftTip,
			&i.Ancestor,
			&i.Conflicts,
			&i.AddressedTo,
			&i.Status,
			&i.ResolvingCommitSha,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConflictEventResolved = `-- name: MarkConflictEventResolved :exec
UPDATE conflict_events
SET status = 'resolved',
    resolving_commit_sha = $1,
    resolved_at = $2
WHERE id = $3 AND session_id = $4 AND status = 'open'
`

type MarkConflictEventResolvedParams struct {
	ResolvingCommitSha pgtype.Text        `json:"resolving_commit_sha"`
	ResolvedAt         pgtype.Timestamptz `json:"resolved_at"`
	ID                 string             `json:"id"`
	SessionID          string             `json:"session_id"`
}

func (q *Queries) MarkConflictEventResolved(ctx context.Context, arg MarkConflictEventResolvedParams) error {
	_, err := q.db.Exec(ctx, markConflictEventResolved,
		arg.ResolvingCommitSha,
		arg.ResolvedAt,
		arg.ID,
		arg.SessionID,
	)
	return err
}
