// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package pgstore

import (
	"context"
	"time"
)

const allocateNextSeq = `-- name: AllocateNextSeq :one
UPDATE event_seq SET next = next + 1 WHERE session_id = $1 RETURNING next
`

func (q *Queries) AllocateNextSeq(ctx context.Context, sessionID string) (int32, error) {
	row := q.db.QueryRow(ctx, allocateNextSeq, sessionID)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const allocateNextSeqN = `-- name: AllocateNextSeqN :one
UPDATE event_seq SET next = next + $1 WHERE session_id = $2 RETURNING next
`

type AllocateNextSeqNParams struct {
	Next      int32  `json:"next"`
	SessionID string `json:"session_id"`
}

func (q *Queries) AllocateNextSeqN(ctx context.Context, arg AllocateNextSeqNParams) (int32, error) {
	row := q.db.QueryRow(ctx, allocateNextSeqN, arg.Next, arg.SessionID)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const ensureEventSeqRow = `-- name: EnsureEventSeqRow :exec
INSERT INTO event_seq (session_id, next) VALUES ($1, 0)
ON CONFLICT(session_id) DO NOTHING
`

func (q *Queries) EnsureEventSeqRow(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, ensureEventSeqRow, sessionID)
	return err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (id, org_id, session_id, seq, type, payload, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertEventParams struct {
	ID        string    `json:"id"`
	OrgID     string    `json:"org_id"`
	SessionID string    `json:"session_id"`
	Seq       int32     `json:"seq"`
	Type      string    `json:"type"`
	Payload   string    `json:"payload"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.OrgID,
		arg.SessionID,
		arg.Seq,
		arg.Type,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const listEventsSince = `-- name: ListEventsSince :many
SELECT id, org_id, session_id, seq, type, payload, created_at
FROM events
WHERE session_id = $1 AND seq > $2
ORDER BY seq ASC
LIMIT $3
`

type ListEventsSinceParams struct {
	SessionID string `json:"session_id"`
	Seq       int32  `json:"seq"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListEventsSince(ctx context.Context, arg ListEventsSinceParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsSince, arg.SessionID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SessionID,
			&i.Seq,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
