// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finalize_locks.sql

package pgstore

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveFinalizeLockForSession = `-- name: GetActiveFinalizeLockForSession :one
SELECT id, org_id, session_id, acquired_by_account_id,
       acquired_at, last_activity_at, selected_commit_shas,
       target_branch, base_sha, mode, commit_message,
       superseded_by_lock_id, released_at
FROM finalize_locks
WHERE session_id = $1
  AND released_at IS NULL
  AND superseded_by_lock_id IS NULL
ORDER BY acquired_at DESC
LIMIT 1
`

func (q *Queries) GetActiveFinalizeLockForSession(ctx context.Context, sessionID string) (FinalizeLock, error) {
	row := q.db.QueryRow(ctx, getActiveFinalizeLockForSession, sessionID)
	var i FinalizeLock
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SessionID,
		&i.AcquiredByAccountID,
		&i.AcquiredAt,
		&i.LastActivityAt,
		&i.SelectedCommitShas,
		&i.TargetBranch,
		&i.BaseSha,
		&i.Mode,
		&i.CommitMessage,
		&i.SupersededByLockID,
		&i.ReleasedAt,
	)
	return i, err
}

const getFinalizeLockByID = `-- name: GetFinalizeLockByID :one
SELECT id, org_id, session_id, acquired_by_account_id,
       acquired_at, last_activity_at, selected_commit_shas,
       target_branch, base_sha, mode, commit_message,
       superseded_by_lock_id, released_at
FROM finalize_locks
WHERE id = $1
`

func (q *Queries) GetFinalizeLockByID(ctx context.Context, id string) (FinalizeLock, error) {
	row := q.db.QueryRow(ctx, getFinalizeLockByID, id)
	var i FinalizeLock
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SessionID,
		&i.AcquiredByAccountID,
		&i.AcquiredAt,
		&i.LastActivityAt,
		&i.SelectedCommitShas,
		&i.TargetBranch,
		&i.BaseSha,
		&i.Mode,
		&i.CommitMessage,
		&i.SupersededByLockID,
		&i.ReleasedAt,
	)
	return i, err
}

const insertFinalizeLock = `-- name: InsertFinalizeLock :exec
INSERT INTO finalize_locks (
    id, org_id, session_id, acquired_by_account_id,
    acquired_at, last_activity_at, selected_commit_shas,
    target_branch, base_sha, mode, commit_message,
    superseded_by_lock_id, released_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertFinalizeLockParams struct {
	ID                  string      `json:"id"`
	OrgID               string      `json:"org_id"`
	SessionID           string      `json:"session_id"`
	AcquiredByAccountID string      `json:"acquired_by_account_id"`
	AcquiredAt          time.Time   `json:"acquired_at"`
	LastActivityAt      time.Time   `json:"last_activity_at"`
	SelectedCommitShas  []byte      `json:"selected_commit_shas"`
	TargetBranch        string      `json:"target_branch"`
	BaseSha             *string     `json:"base_sha"`
	Mode                string      `json:"mode"`
	CommitMessage       pgtype.Text `json:"commit_message"`
	SupersededByLockID  pgtype.Text `json:"superseded_by_lock_id"`
	ReleasedAt          *time.Time  `json:"released_at"`
}

func (q *Queries) InsertFinalizeLock(ctx context.Context, arg InsertFinalizeLockParams) error {
	_, err := q.db.Exec(ctx, insertFinalizeLock,
		arg.ID,
		arg.OrgID,
		arg.SessionID,
		arg.AcquiredByAccountID,
		arg.AcquiredAt,
		arg.LastActivityAt,
		arg.SelectedCommitShas,
		arg.TargetBranch,
		arg.BaseSha,
		arg.Mode,
		arg.CommitMessage,
		arg.SupersededByLockID,
		arg.ReleasedAt,
	)
	return err
}

const releaseFinalizeLock = `-- name: ReleaseFinalizeLock :exec
UPDATE finalize_locks
SET released_at = $1
WHERE id = $2 AND released_at IS NULL
`

type ReleaseFinalizeLockParams struct {
	ReleasedAt *time.Time `json:"released_at"`
	ID         string     `json:"id"`
}

func (q *Queries) ReleaseFinalizeLock(ctx context.Context, arg ReleaseFinalizeLockParams) error {
	_, err := q.db.Exec(ctx, releaseFinalizeLock, arg.ReleasedAt, arg.ID)
	return err
}

const supersedeFinalizeLock = `-- name: SupersedeFinalizeLock :exec
UPDATE finalize_locks
SET superseded_by_lock_id = $1
WHERE id = $2
`

type SupersedeFinalizeLockParams struct {
	SupersededByLockID pgtype.Text `json:"superseded_by_lock_id"`
	ID                 string      `json:"id"`
}

func (q *Queries) SupersedeFinalizeLock(ctx context.Context, arg SupersedeFinalizeLockParams) error {
	_, err := q.db.Exec(ctx, supersedeFinalizeLock, arg.SupersededByLockID, arg.ID)
	return err
}

const touchFinalizeLock = `-- name: TouchFinalizeLock :exec
UPDATE finalize_locks
SET last_activity_at = $1
WHERE id = $2
`

type TouchFinalizeLockParams struct {
	LastActivityAt time.Time `json:"last_activity_at"`
	ID             string    `json:"id"`
}

func (q *Queries) TouchFinalizeLock(ctx context.Context, arg TouchFinalizeLockParams) error {
	_, err := q.db.Exec(ctx, touchFinalizeLock, arg.LastActivityAt, arg.ID)
	return err
}

const updateFinalizeLockCuration = `-- name: UpdateFinalizeLockCuration :exec
UPDATE finalize_locks
SET selected_commit_shas = $1,
    target_branch = $2,
    base_sha = $3,
    mode = $4,
    commit_message = $5,
    last_activity_at = $6
WHERE id = $7
`

type UpdateFinalizeLockCurationParams struct {
	SelectedCommitShas []byte      `json:"selected_commit_shas"`
	TargetBranch       string      `json:"target_branch"`
	BaseSha            *string     `json:"base_sha"`
	Mode               string      `json:"mode"`
	CommitMessage      pgtype.Text `json:"commit_message"`
	LastActivityAt     time.Time   `json:"last_activity_at"`
	ID                 string      `json:"id"`
}

func (q *Queries) UpdateFinalizeLockCuration(ctx context.Context, arg UpdateFinalizeLockCurationParams) error {
	_, err := q.db.Exec(ctx, updateFinalizeLockCuration,
		arg.SelectedCommitShas,
		arg.TargetBranch,
		arg.BaseSha,
		arg.Mode,
		arg.CommitMessage,
		arg.LastActivityAt,
		arg.ID,
	)
	return err
}
