// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leases.sql

package pgstore

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const issueLeaseFencingToken = `-- name: IssueLeaseFencingToken :one
SELECT nextval('jamsesh_lease_fencing_tokens')::bigint AS token
`

func (q *Queries) IssueLeaseFencingToken(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, issueLeaseFencingToken)
	var token int64
	err := row.Scan(&token)
	return token, err
}

const insertLease = `-- name: InsertLease :one
INSERT INTO leases (session_id, pod_id, fencing_token, acquired_at, released_at, heartbeat_at)
VALUES ($1, $2, $3, now(), NULL, now())
ON CONFLICT (session_id) DO UPDATE
    SET pod_id        = EXCLUDED.pod_id,
        fencing_token = EXCLUDED.fencing_token,
        acquired_at   = now(),
        released_at   = NULL,
        heartbeat_at  = now()
RETURNING session_id, pod_id, fencing_token, acquired_at, released_at, heartbeat_at
`

type InsertLeaseParams struct {
	SessionID    string `json:"session_id"`
	PodID        string `json:"pod_id"`
	FencingToken int64  `json:"fencing_token"`
}

func (q *Queries) InsertLease(ctx context.Context, arg InsertLeaseParams) (Lease, error) {
	row := q.db.QueryRow(ctx, insertLease, arg.SessionID, arg.PodID, arg.FencingToken)
	var i Lease
	err := row.Scan(
		&i.SessionID,
		&i.PodID,
		&i.FencingToken,
		&i.AcquiredAt,
		&i.ReleasedAt,
		&i.HeartbeatAt,
	)
	return i, err
}

const markLeaseReleased = `-- name: MarkLeaseReleased :exec
UPDATE leases
SET released_at = now()
WHERE session_id = $1
`

func (q *Queries) MarkLeaseReleased(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, markLeaseReleased, sessionID)
	return err
}

const updateLeaseHeartbeat = `-- name: UpdateLeaseHeartbeat :exec
UPDATE leases
SET heartbeat_at = now()
WHERE session_id = $1
`

func (q *Queries) UpdateLeaseHeartbeat(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, updateLeaseHeartbeat, sessionID)
	return err
}

const deleteReleasedLeasesOlderThan = `-- name: DeleteReleasedLeasesOlderThan :exec
DELETE FROM leases
WHERE released_at IS NOT NULL
  AND released_at < $1
`

func (q *Queries) DeleteReleasedLeasesOlderThan(ctx context.Context, before time.Time) error {
	_, err := q.db.Exec(ctx, deleteReleasedLeasesOlderThan,
		pgtype.Timestamptz{Time: before, Valid: true},
	)
	return err
}
