// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: oauth_tokens.sql

package pgstore

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnonymousBearer = `-- name: CreateAnonymousBearer :one
INSERT INTO oauth_tokens (id, account_id, token_hash, kind, session_id,
                          issued_at, expires_at)
VALUES ($1, $2, $3, 'anonymous_session_bearer', $4, $5, $6)
RETURNING id, account_id, token_hash, kind, session_id, issued_at, expires_at, last_used_at, revoked_at
`

type CreateAnonymousBearerParams struct {
	ID        string      `json:"id"`
	AccountID string      `json:"account_id"`
	TokenHash string      `json:"token_hash"`
	SessionID pgtype.Text `json:"session_id"`
	IssuedAt  time.Time   `json:"issued_at"`
	ExpiresAt time.Time   `json:"expires_at"`
}

// Inserts an anonymous-session-scoped bearer row. The session_id FK
// ensures the bearer is cascade-deleted when the session is destroyed
// (ON DELETE CASCADE). expires_at is set by the caller, typically to
// the session's hard-cap deadline.
func (q *Queries) CreateAnonymousBearer(ctx context.Context, arg CreateAnonymousBearerParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, createAnonymousBearer,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.SessionID,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.Kind,
		&i.SessionID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createOAuthToken = `-- name: CreateOAuthToken :one
INSERT INTO oauth_tokens (id, account_id, token_hash, kind, issued_at, expires_at, last_used_at, revoked_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, account_id, token_hash, kind, session_id, issued_at, expires_at, last_used_at, revoked_at
`

type CreateOAuthTokenParams struct {
	ID         string     `json:"id"`
	AccountID  string     `json:"account_id"`
	TokenHash  string     `json:"token_hash"`
	Kind       string     `json:"kind"`
	IssuedAt   time.Time  `json:"issued_at"`
	ExpiresAt  time.Time  `json:"expires_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
}

func (q *Queries) CreateOAuthToken(ctx context.Context, arg CreateOAuthTokenParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, createOAuthToken,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.Kind,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
		arg.RevokedAt,
	)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.Kind,
		&i.SessionID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getOAuthTokenByHash = `-- name: GetOAuthTokenByHash :one
SELECT id, account_id, token_hash, kind, session_id, issued_at, expires_at, last_used_at, revoked_at
FROM oauth_tokens
WHERE token_hash = $1
`

func (q *Queries) GetOAuthTokenByHash(ctx context.Context, tokenHash string) (OauthToken, error) {
	row := q.db.QueryRow(ctx, getOAuthTokenByHash, tokenHash)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.Kind,
		&i.SessionID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listOAuthTokensForAccount = `-- name: ListOAuthTokensForAccount :many
SELECT id, account_id, token_hash, kind, session_id, issued_at, expires_at, last_used_at, revoked_at
FROM oauth_tokens
WHERE account_id = $1
ORDER BY issued_at DESC
`

func (q *Queries) ListOAuthTokensForAccount(ctx context.Context, accountID string) ([]OauthToken, error) {
	rows, err := q.db.Query(ctx, listOAuthTokensForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthToken
	for rows.Next() {
		var i OauthToken
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TokenHash,
			&i.Kind,
			&i.SessionID,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllOAuthTokensForAccount = `-- name: RevokeAllOAuthTokensForAccount :exec
UPDATE oauth_tokens
SET revoked_at = $1
WHERE account_id = $2 AND revoked_at IS NULL
`

type RevokeAllOAuthTokensForAccountParams struct {
	RevokedAt *time.Time `json:"revoked_at"`
	AccountID string     `json:"account_id"`
}

func (q *Queries) RevokeAllOAuthTokensForAccount(ctx context.Context, arg RevokeAllOAuthTokensForAccountParams) error {
	_, err := q.db.Exec(ctx, revokeAllOAuthTokensForAccount, arg.RevokedAt, arg.AccountID)
	return err
}

const revokeBearersForSession = `-- name: RevokeBearersForSession :exec
UPDATE oauth_tokens
   SET revoked_at = $1
 WHERE session_id = $2
   AND revoked_at IS NULL
`

type RevokeBearersForSessionParams struct {
	RevokedAt *time.Time  `json:"revoked_at"`
	SessionID pgtype.Text `json:"session_id"`
}

// Marks every bearer (any kind) associated with a session as revoked.
// Used by the session destruction routine in session-lifecycle feature
// as the first step of the cascade: revoke bearers, delete dependent
// rows, delete session row, cascade.
func (q *Queries) RevokeBearersForSession(ctx context.Context, arg RevokeBearersForSessionParams) error {
	_, err := q.db.Exec(ctx, revokeBearersForSession, arg.RevokedAt, arg.SessionID)
	return err
}

const revokeOAuthToken = `-- name: RevokeOAuthToken :exec
UPDATE oauth_tokens
SET revoked_at = $1
WHERE id = $2
`

type RevokeOAuthTokenParams struct {
	RevokedAt *time.Time `json:"revoked_at"`
	ID        string     `json:"id"`
}

func (q *Queries) RevokeOAuthToken(ctx context.Context, arg RevokeOAuthTokenParams) error {
	_, err := q.db.Exec(ctx, revokeOAuthToken, arg.RevokedAt, arg.ID)
	return err
}

const touchOAuthTokenLastUsed = `-- name: TouchOAuthTokenLastUsed :exec
UPDATE oauth_tokens
SET last_used_at = $1
WHERE id = $2
`

type TouchOAuthTokenLastUsedParams struct {
	LastUsedAt *time.Time `json:"last_used_at"`
	ID         string     `json:"id"`
}

func (q *Queries) TouchOAuthTokenLastUsed(ctx context.Context, arg TouchOAuthTokenLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchOAuthTokenLastUsed, arg.LastUsedAt, arg.ID)
	return err
}
