// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package pgstore

import (
	"context"
	"time"
)

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (id, name, slug, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, created_at
`

type CreateOrgParams struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, name, slug, created_at
FROM orgs
WHERE id = $1
`

func (q *Queries) GetOrgByID(ctx context.Context, id string) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgByID, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgBySlug = `-- name: GetOrgBySlug :one
SELECT id, name, slug, created_at
FROM orgs
WHERE slug = $1
`

func (q *Queries) GetOrgBySlug(ctx context.Context, slug string) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgBySlug, slug)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}
