// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: presence.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPresenceForSession = `-- name: ListPresenceForSession :many
SELECT org_id, session_id, account_id, ref, current_sha, last_active_at
FROM presence
WHERE session_id = $1
ORDER BY account_id, ref
`

func (q *Queries) ListPresenceForSession(ctx context.Context, sessionID string) ([]Presence, error) {
	rows, err := q.db.Query(ctx, listPresenceForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Presence
	for rows.Next() {
		var i Presence
		if err := rows.Scan(
			&i.OrgID,
			&i.SessionID,
			&i.AccountID,
			&i.Ref,
			&i.CurrentSha,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPresence = `-- name: UpsertPresence :exec
INSERT INTO presence (org_id, session_id, account_id, ref, current_sha, last_active_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT(session_id, account_id, ref) DO UPDATE SET
    current_sha = EXCLUDED.current_sha,
    last_active_at = EXCLUDED.last_active_at
`

type UpsertPresenceParams struct {
	OrgID        string             `json:"org_id"`
	SessionID    string             `json:"session_id"`
	AccountID    string             `json:"account_id"`
	Ref          string             `json:"ref"`
	CurrentSha   string             `json:"current_sha"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
}

func (q *Queries) UpsertPresence(ctx context.Context, arg UpsertPresenceParams) error {
	_, err := q.db.Exec(ctx, upsertPresence,
		arg.OrgID,
		arg.SessionID,
		arg.AccountID,
		arg.Ref,
		arg.CurrentSha,
		arg.LastActiveAt,
	)
	return err
}
