// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package pgstore

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error
	AddSessionMember(ctx context.Context, arg AddSessionMemberParams) error
	AllocateNextSeq(ctx context.Context, sessionID string) (int32, error)
	AllocateNextSeqN(ctx context.Context, arg AllocateNextSeqNParams) (int32, error)
	CleanupExpiredOAuthState(ctx context.Context, expiresAt time.Time) error
	ClearFinalizeLock(ctx context.Context, arg ClearFinalizeLockParams) error
	ConsumeMagicLinkToken(ctx context.Context, arg ConsumeMagicLinkTokenParams) error
	ConsumeOAuthState(ctx context.Context, nonce string) (OauthState, error)
	CountSessionMembers(ctx context.Context, arg CountSessionMembersParams) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	// Creates an anonymous account for a playground session participant.
	// The synthetic email satisfies the NOT NULL UNIQUE constraint without
	// requiring schema relaxation; the @playground.local suffix and the
	// random ID prefix guarantee uniqueness.
	CreateAnonymousAccount(ctx context.Context, arg CreateAnonymousAccountParams) (Account, error)
	// Inserts an anonymous-session-scoped bearer row. The session_id FK
	// ensures the bearer is cascade-deleted when the session is destroyed
	// (ON DELETE CASCADE). expires_at is set by the caller, typically to
	// the session's hard-cap deadline.
	CreateAnonymousBearer(ctx context.Context, arg CreateAnonymousBearerParams) (OauthToken, error)
	CreateMagicLinkToken(ctx context.Context, arg CreateMagicLinkTokenParams) (MagicLinkToken, error)
	CreateOAuthToken(ctx context.Context, arg CreateOAuthTokenParams) (OauthToken, error)
	CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error)
	// Inserts an org row with org_protected=true. Used at startup by the
	// playground provisioning hook for the reserved `playground` org.
	// Slug uniqueness is enforced by the existing UNIQUE constraint on orgs.slug.
	CreateProtectedOrg(ctx context.Context, arg CreateProtectedOrgParams) (Org, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteReleasedLeasesOlderThan(ctx context.Context, releasedAt *time.Time) error
	DeleteSession(ctx context.Context, arg DeleteSessionParams) error
	EnsureEventSeqRow(ctx context.Context, sessionID string) error
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetAccountByGitHubUserID(ctx context.Context, githubUserID pgtype.Text) (Account, error)
	GetAccountByID(ctx context.Context, id string) (Account, error)
	GetActiveFinalizeLockForSession(ctx context.Context, sessionID string) (FinalizeLock, error)
	GetArchivedSession(ctx context.Context, arg GetArchivedSessionParams) (ArchivedSession, error)
	GetCommentByID(ctx context.Context, id string) (Comment, error)
	GetConflictEventByID(ctx context.Context, id string) (ConflictEvent, error)
	GetFinalizeLockByID(ctx context.Context, id string) (FinalizeLock, error)
	GetMagicLinkTokenByHash(ctx context.Context, tokenHash string) (MagicLinkToken, error)
	GetOAuthTokenByHash(ctx context.Context, tokenHash string) (OauthToken, error)
	GetOrgByID(ctx context.Context, id string) (Org, error)
	GetOrgBySlug(ctx context.Context, slug string) (Org, error)
	GetOrgInviteByID(ctx context.Context, id string) (OrgInvite, error)
	GetOrgInviteByTokenHash(ctx context.Context, tokenHash string) (OrgInvite, error)
	GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrgMember, error)
	GetOrgSessionInvitePolicy(ctx context.Context, id string) (string, error)
	GetRefMode(ctx context.Context, arg GetRefModeParams) (RefMode, error)
	GetSession(ctx context.Context, arg GetSessionParams) (Session, error)
	GetSessionInviteByID(ctx context.Context, id string) (SessionInvite, error)
	GetSessionInviteByTokenHash(ctx context.Context, tokenHash string) (SessionInvite, error)
	GetSessionMember(ctx context.Context, arg GetSessionMemberParams) (SessionMember, error)
	GetTombstone(ctx context.Context, sessionID string) (Tombstone, error)
	InsertArchivedSession(ctx context.Context, arg InsertArchivedSessionParams) error
	InsertComment(ctx context.Context, arg InsertCommentParams) error
	InsertConflictEvent(ctx context.Context, arg InsertConflictEventParams) error
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertFinalizeLock(ctx context.Context, arg InsertFinalizeLockParams) error
	InsertLease(ctx context.Context, arg InsertLeaseParams) (Lease, error)
	InsertOAuthState(ctx context.Context, arg InsertOAuthStateParams) error
	InsertOrgInvite(ctx context.Context, arg InsertOrgInviteParams) (OrgInvite, error)
	InsertSessionInvite(ctx context.Context, arg InsertSessionInviteParams) (SessionInvite, error)
	IssueLeaseFencingToken(ctx context.Context) (int64, error)
	ListCommentsForSession(ctx context.Context, arg ListCommentsForSessionParams) ([]Comment, error)
	ListEventsSince(ctx context.Context, arg ListEventsSinceParams) ([]Event, error)
	ListEventsSinceForDigest(ctx context.Context, arg ListEventsSinceForDigestParams) ([]Event, error)
	ListOAuthTokensForAccount(ctx context.Context, accountID string) ([]OauthToken, error)
	ListOpenConflictEventsForSession(ctx context.Context, sessionID string) ([]ConflictEvent, error)
	ListOrgMembers(ctx context.Context, orgID string) ([]ListOrgMembersRow, error)
	ListOrgsForAccount(ctx context.Context, accountID string) ([]Org, error)
	ListPendingOrgInvitesForEmail(ctx context.Context, arg ListPendingOrgInvitesForEmailParams) ([]OrgInvite, error)
	ListPendingOrgInvitesForOrg(ctx context.Context, arg ListPendingOrgInvitesForOrgParams) ([]OrgInvite, error)
	ListPendingSessionInvitesForSession(ctx context.Context, arg ListPendingSessionInvitesForSessionParams) ([]SessionInvite, error)
	ListPresenceForSession(ctx context.Context, sessionID string) ([]Presence, error)
	ListRefModesForSession(ctx context.Context, sessionID string) ([]RefMode, error)
	ListSessionMembers(ctx context.Context, arg ListSessionMembersParams) ([]SessionMember, error)
	// Intentional cross-org exception: returns sessions across all orgs for the
	// authenticated account. The caller receives org_id on each row so it can
	// route further org-scoped queries correctly. This is the only query in this
	// file that does not restrict by org_id in WHERE.
	ListSessionMembershipsForAccount(ctx context.Context, accountID string) ([]ListSessionMembershipsForAccountRow, error)
	ListSessionsForOrg(ctx context.Context, orgID string) ([]Session, error)
	ListSessionsForOrgWithCursor(ctx context.Context, arg ListSessionsForOrgWithCursorParams) ([]Session, error)
	MarkConflictEventResolved(ctx context.Context, arg MarkConflictEventResolvedParams) error
	MarkLeaseReleased(ctx context.Context, sessionID string) error
	MarkOrgInviteAccepted(ctx context.Context, arg MarkOrgInviteAcceptedParams) error
	MarkSessionInviteAccepted(ctx context.Context, arg MarkSessionInviteAcceptedParams) error
	NicknameTakenInSession(ctx context.Context, arg NicknameTakenInSessionParams) (bool, error)
	RecordTombstone(ctx context.Context, arg RecordTombstoneParams) error
	ReleaseFinalizeLock(ctx context.Context, arg ReleaseFinalizeLockParams) error
	RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error
	RemoveSessionMember(ctx context.Context, arg RemoveSessionMemberParams) error
	ResetSessionIdleTimer(ctx context.Context, arg ResetSessionIdleTimerParams) error
	ResolveComment(ctx context.Context, arg ResolveCommentParams) error
	RevokeAllOAuthTokensForAccount(ctx context.Context, arg RevokeAllOAuthTokensForAccountParams) error
	// Marks every bearer (any kind) associated with a session as revoked.
	// Used by the session destruction routine in session-lifecycle feature
	// as the first step of the cascade: revoke bearers, delete dependent
	// rows, delete session row, cascade.
	RevokeBearersForSession(ctx context.Context, arg RevokeBearersForSessionParams) error
	RevokeOAuthToken(ctx context.Context, arg RevokeOAuthTokenParams) error
	SetFinalizeLock(ctx context.Context, arg SetFinalizeLockParams) error
	SetSessionBaseSHA(ctx context.Context, arg SetSessionBaseSHAParams) error
	SetSessionEndReason(ctx context.Context, arg SetSessionEndReasonParams) error
	SupersedeFinalizeLock(ctx context.Context, arg SupersedeFinalizeLockParams) error
	TouchFinalizeLock(ctx context.Context, arg TouchFinalizeLockParams) error
	TouchOAuthTokenLastUsed(ctx context.Context, arg TouchOAuthTokenLastUsedParams) error
	UpdateAccountDisplayName(ctx context.Context, arg UpdateAccountDisplayNameParams) error
	UpdateFinalizeLockCuration(ctx context.Context, arg UpdateFinalizeLockCurationParams) error
	UpdateLeaseHeartbeat(ctx context.Context, sessionID string) error
	UpdateOrgSessionInvitePolicy(ctx context.Context, arg UpdateOrgSessionInvitePolicyParams) error
	UpdateSessionGoalScopeMode(ctx context.Context, arg UpdateSessionGoalScopeModeParams) error
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error
	UpsertPresence(ctx context.Context, arg UpsertPresenceParams) error
	UpsertRefMode(ctx context.Context, arg UpsertRefModeParams) error
}

var _ Querier = (*Queries)(nil)
