// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: ref_modes.sql

package pgstore

import (
	"context"
)

const getRefMode = `-- name: GetRefMode :one
SELECT session_id, ref, mode
FROM ref_modes
WHERE session_id = $1 AND ref = $2
`

type GetRefModeParams struct {
	SessionID string `json:"session_id"`
	Ref       string `json:"ref"`
}

func (q *Queries) GetRefMode(ctx context.Context, arg GetRefModeParams) (RefMode, error) {
	row := q.db.QueryRow(ctx, getRefMode, arg.SessionID, arg.Ref)
	var i RefMode
	err := row.Scan(&i.SessionID, &i.Ref, &i.Mode)
	return i, err
}

const listRefModesForSession = `-- name: ListRefModesForSession :many
SELECT session_id, ref, mode
FROM ref_modes
WHERE session_id = $1
ORDER BY ref ASC
`

func (q *Queries) ListRefModesForSession(ctx context.Context, sessionID string) ([]RefMode, error) {
	rows, err := q.db.Query(ctx, listRefModesForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefMode
	for rows.Next() {
		var i RefMode
		if err := rows.Scan(&i.SessionID, &i.Ref, &i.Mode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRefMode = `-- name: UpsertRefMode :exec
INSERT INTO ref_modes (session_id, ref, mode)
VALUES ($1, $2, $3)
ON CONFLICT (session_id, ref) DO UPDATE SET mode = excluded.mode
`

type UpsertRefModeParams struct {
	SessionID string `json:"session_id"`
	Ref       string `json:"ref"`
	Mode      string `json:"mode"`
}

func (q *Queries) UpsertRefMode(ctx context.Context, arg UpsertRefModeParams) error {
	_, err := q.db.Exec(ctx, upsertRefMode, arg.SessionID, arg.Ref, arg.Mode)
	return err
}
