// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resume_tokens.sql

package pgstore

import (
	"context"
	"time"
)

const consumeResumeToken = `-- name: ConsumeResumeToken :one
UPDATE resume_tokens
SET used_at = $1
WHERE token_hash = $2 AND used_at IS NULL AND expires_at > $3
RETURNING id, token_hash, session_id, org_id, account_id, issued_at, expires_at, used_at
`

type ConsumeResumeTokenParams struct {
	UsedAt    *time.Time `json:"used_at"`
	TokenHash string     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
}

func (q *Queries) ConsumeResumeToken(ctx context.Context, arg ConsumeResumeTokenParams) (ResumeToken, error) {
	row := q.db.QueryRow(ctx, consumeResumeToken, arg.UsedAt, arg.TokenHash, arg.ExpiresAt)
	var i ResumeToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.SessionID,
		&i.OrgID,
		&i.AccountID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const createResumeToken = `-- name: CreateResumeToken :one
INSERT INTO resume_tokens (id, token_hash, session_id, org_id, account_id, issued_at, expires_at, used_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, token_hash, session_id, org_id, account_id, issued_at, expires_at, used_at
`

type CreateResumeTokenParams struct {
	ID        string     `json:"id"`
	TokenHash string     `json:"token_hash"`
	SessionID string     `json:"session_id"`
	OrgID     string     `json:"org_id"`
	AccountID string     `json:"account_id"`
	IssuedAt  time.Time  `json:"issued_at"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
}

func (q *Queries) CreateResumeToken(ctx context.Context, arg CreateResumeTokenParams) (ResumeToken, error) {
	row := q.db.QueryRow(ctx, createResumeToken,
		arg.ID,
		arg.TokenHash,
		arg.SessionID,
		arg.OrgID,
		arg.AccountID,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.UsedAt,
	)
	var i ResumeToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.SessionID,
		&i.OrgID,
		&i.AccountID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getResumeTokenByHash = `-- name: GetResumeTokenByHash :one
SELECT id, token_hash, session_id, org_id, account_id, issued_at, expires_at, used_at
FROM resume_tokens
WHERE token_hash = $1
`

func (q *Queries) GetResumeTokenByHash(ctx context.Context, tokenHash string) (ResumeToken, error) {
	row := q.db.QueryRow(ctx, getResumeTokenByHash, tokenHash)
	var i ResumeToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.SessionID,
		&i.OrgID,
		&i.AccountID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}
