// Package pgstore — sessions_extra.go contains hand-written session queries
// that are not generated by sqlc because they are intentional cross-org
// exceptions or require dialect-specific SQL not supported by the shared sqlc
// configuration.
package pgstore

import (
	"context"
)

// getSessionByID is the SQL for a cross-org session lookup by primary key.
// Session IDs are UUIDs and globally unique across all orgs; this query is
// an intentional cross-org exception used by the LifecycleManager's
// OrgIDLookup function.
const getSessionByID = `
SELECT id, org_id, name, goal, writable_scope, default_mode, base_sha, status, created_at, ended_at, end_reason, finalize_locked_by_account_id
FROM sessions
WHERE id = $1
`

// GetSessionByID returns the session with the given ID regardless of org_id.
// This is an intentional cross-org exception: the LifecycleManager calls this
// once per lease lifetime to resolve the org_id needed for hydration. The
// returned row includes org_id so callers can route org-scoped operations.
func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Goal,
		&i.WritableScope,
		&i.DefaultMode,
		&i.BaseSha,
		&i.Status,
		&i.CreatedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.FinalizeLockedByAccountID,
	)
	if err != nil {
		return Session{}, err
	}
	return i, nil
}
