// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package pgstore

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, org_id, name, goal, writable_scope, default_mode, base_sha, status, created_at, ended_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, org_id, name, goal, writable_scope, default_mode, base_sha, status, created_at, ended_at
`

type CreateSessionParams struct {
	ID            string     `json:"id"`
	OrgID         string     `json:"org_id"`
	Name          string     `json:"name"`
	Goal          string     `json:"goal"`
	WritableScope string     `json:"writable_scope"`
	DefaultMode   string     `json:"default_mode"`
	BaseSha       *string    `json:"base_sha"`
	Status        string     `json:"status"`
	CreatedAt     time.Time  `json:"created_at"`
	EndedAt       *time.Time `json:"ended_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Goal,
		arg.WritableScope,
		arg.DefaultMode,
		arg.BaseSha,
		arg.Status,
		arg.CreatedAt,
		arg.EndedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Goal,
		&i.WritableScope,
		&i.DefaultMode,
		&i.BaseSha,
		&i.Status,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE org_id = $1 AND id = $2
`

type DeleteSessionParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.Exec(ctx, deleteSession, arg.OrgID, arg.ID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, org_id, name, goal, writable_scope, default_mode, base_sha, status, created_at, ended_at
FROM sessions
WHERE org_id = $1 AND id = $2
`

type GetSessionParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, arg.OrgID, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Goal,
		&i.WritableScope,
		&i.DefaultMode,
		&i.BaseSha,
		&i.Status,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}

const listSessionsForOrg = `-- name: ListSessionsForOrg :many
SELECT id, org_id, name, goal, writable_scope, default_mode, base_sha, status, created_at, ended_at
FROM sessions
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSessionsForOrg(ctx context.Context, orgID string) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Goal,
			&i.WritableScope,
			&i.DefaultMode,
			&i.BaseSha,
			&i.Status,
			&i.CreatedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionBaseSHA = `-- name: SetSessionBaseSHA :exec
UPDATE sessions
SET base_sha = $1
WHERE org_id = $2 AND id = $3
`

type SetSessionBaseSHAParams struct {
	BaseSha *string `json:"base_sha"`
	OrgID   string  `json:"org_id"`
	ID      string  `json:"id"`
}

func (q *Queries) SetSessionBaseSHA(ctx context.Context, arg SetSessionBaseSHAParams) error {
	_, err := q.db.Exec(ctx, setSessionBaseSHA, arg.BaseSha, arg.OrgID, arg.ID)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE sessions
SET status = $1
WHERE org_id = $2 AND id = $3
`

type UpdateSessionStatusParams struct {
	Status string `json:"status"`
	OrgID  string `json:"org_id"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSessionStatus, arg.Status, arg.OrgID, arg.ID)
	return err
}
