// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package pgstore

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearFinalizeLock = `-- name: ClearFinalizeLock :exec
UPDATE sessions
SET finalize_locked_by_account_id = NULL
WHERE org_id = $1 AND id = $2
`

type ClearFinalizeLockParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) ClearFinalizeLock(ctx context.Context, arg ClearFinalizeLockParams) error {
	_, err := q.db.Exec(ctx, clearFinalizeLock, arg.OrgID, arg.ID)
	return err
}

const countSessionMembers = `-- name: CountSessionMembers :one
SELECT COUNT(*) AS member_count
FROM session_members
WHERE org_id = $1 AND session_id = $2
`

type CountSessionMembersParams struct {
	OrgID     string `json:"org_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) CountSessionMembers(ctx context.Context, arg CountSessionMembersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionMembers, arg.OrgID, arg.SessionID)
	var member_count int64
	err := row.Scan(&member_count)
	return member_count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, org_id, name, goal, writable_scope, default_mode, base_sha, status, created_at, ended_at,
                      last_substantive_activity_at, hard_cap_at, idle_timeout_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, org_id, name, goal, writable_scope, default_mode, base_sha, status, created_at, ended_at, end_reason, finalize_locked_by_account_id, last_substantive_activity_at, hard_cap_at, idle_timeout_at
`

type CreateSessionParams struct {
	ID                        string             `json:"id"`
	OrgID                     string             `json:"org_id"`
	Name                      string             `json:"name"`
	Goal                      string             `json:"goal"`
	WritableScope             string             `json:"writable_scope"`
	DefaultMode               string             `json:"default_mode"`
	BaseSha                   *string            `json:"base_sha"`
	Status                    string             `json:"status"`
	CreatedAt                 time.Time          `json:"created_at"`
	EndedAt                   *time.Time         `json:"ended_at"`
	LastSubstantiveActivityAt pgtype.Timestamptz `json:"last_substantive_activity_at"`
	HardCapAt                 pgtype.Timestamptz `json:"hard_cap_at"`
	IdleTimeoutAt             pgtype.Timestamptz `json:"idle_timeout_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Goal,
		arg.WritableScope,
		arg.DefaultMode,
		arg.BaseSha,
		arg.Status,
		arg.CreatedAt,
		arg.EndedAt,
		arg.LastSubstantiveActivityAt,
		arg.HardCapAt,
		arg.IdleTimeoutAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Goal,
		&i.WritableScope,
		&i.DefaultMode,
		&i.BaseSha,
		&i.Status,
		&i.CreatedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.FinalizeLockedByAccountID,
		&i.LastSubstantiveActivityAt,
		&i.HardCapAt,
		&i.IdleTimeoutAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE org_id = $1 AND id = $2
`

type DeleteSessionParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.Exec(ctx, deleteSession, arg.OrgID, arg.ID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, org_id, name, goal, writable_scope, default_mode, base_sha, status, created_at, ended_at, end_reason,
       finalize_locked_by_account_id, last_substantive_activity_at, hard_cap_at, idle_timeout_at
FROM sessions
WHERE org_id = $1 AND id = $2
`

type GetSessionParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, arg.OrgID, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Goal,
		&i.WritableScope,
		&i.DefaultMode,
		&i.BaseSha,
		&i.Status,
		&i.CreatedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.FinalizeLockedByAccountID,
		&i.LastSubstantiveActivityAt,
		&i.HardCapAt,
		&i.IdleTimeoutAt,
	)
	return i, err
}

const getTombstone = `-- name: GetTombstone :one
SELECT session_id, org_id, members_count, commits_count, auto_merges_count,
       duration_seconds, end_reason, ended_at, expires_at
FROM tombstones
WHERE session_id = $1
`

func (q *Queries) GetTombstone(ctx context.Context, sessionID string) (Tombstone, error) {
	row := q.db.QueryRow(ctx, getTombstone, sessionID)
	var i Tombstone
	err := row.Scan(
		&i.SessionID,
		&i.OrgID,
		&i.MembersCount,
		&i.CommitsCount,
		&i.AutoMergesCount,
		&i.DurationSeconds,
		&i.EndReason,
		&i.EndedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listExpiredPlaygroundSessions = `-- name: ListExpiredPlaygroundSessions :many
SELECT id, org_id, name, goal, writable_scope, default_mode, base_sha, status, created_at, ended_at, end_reason,
       finalize_locked_by_account_id, last_substantive_activity_at, hard_cap_at, idle_timeout_at
FROM sessions
WHERE org_id = $1
  AND status = 'active'
  AND (hard_cap_at IS NOT NULL OR idle_timeout_at IS NOT NULL)
  AND (
        (hard_cap_at IS NOT NULL AND hard_cap_at <= $2)
     OR (idle_timeout_at IS NOT NULL AND idle_timeout_at <= $2)
  )
`

type ListExpiredPlaygroundSessionsParams struct {
	OrgID     string             `json:"org_id"`
	HardCapAt pgtype.Timestamptz `json:"hard_cap_at"`
}

// Returns active playground sessions where the hard cap or idle timer has elapsed.
func (q *Queries) ListExpiredPlaygroundSessions(ctx context.Context, arg ListExpiredPlaygroundSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listExpiredPlaygroundSessions, arg.OrgID, arg.HardCapAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Goal,
			&i.WritableScope,
			&i.DefaultMode,
			&i.BaseSha,
			&i.Status,
			&i.CreatedAt,
			&i.EndedAt,
			&i.EndReason,
			&i.FinalizeLockedByAccountID,
			&i.LastSubstantiveActivityAt,
			&i.HardCapAt,
			&i.IdleTimeoutAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForOrg = `-- name: ListSessionsForOrg :many
SELECT id, org_id, name, goal, writable_scope, default_mode, base_sha, status, created_at, ended_at, end_reason,
       finalize_locked_by_account_id, last_substantive_activity_at, hard_cap_at, idle_timeout_at
FROM sessions
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSessionsForOrg(ctx context.Context, orgID string) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Goal,
			&i.WritableScope,
			&i.DefaultMode,
			&i.BaseSha,
			&i.Status,
			&i.CreatedAt,
			&i.EndedAt,
			&i.EndReason,
			&i.FinalizeLockedByAccountID,
			&i.LastSubstantiveActivityAt,
			&i.HardCapAt,
			&i.IdleTimeoutAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForOrgWithCursor = `-- name: ListSessionsForOrgWithCursor :many
SELECT id, org_id, name, goal, writable_scope, default_mode, base_sha, status, created_at, ended_at, end_reason,
       finalize_locked_by_account_id, last_substantive_activity_at, hard_cap_at, idle_timeout_at
FROM sessions
WHERE org_id = $1
  AND (created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListSessionsForOrgWithCursorParams struct {
	OrgID     string    `json:"org_id"`
	CreatedAt time.Time `json:"created_at"`
	ID        string    `json:"id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListSessionsForOrgWithCursor(ctx context.Context, arg ListSessionsForOrgWithCursorParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsForOrgWithCursor,
		arg.OrgID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Goal,
			&i.WritableScope,
			&i.DefaultMode,
			&i.BaseSha,
			&i.Status,
			&i.CreatedAt,
			&i.EndedAt,
			&i.EndReason,
			&i.FinalizeLockedByAccountID,
			&i.LastSubstantiveActivityAt,
			&i.HardCapAt,
			&i.IdleTimeoutAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nicknameTakenInSession = `-- name: NicknameTakenInSession :one
SELECT COUNT(*) > 0 AS taken
FROM session_members sm
JOIN accounts a ON a.id = sm.account_id
WHERE sm.org_id = $1 AND sm.session_id = $2 AND a.display_name = $3
`

type NicknameTakenInSessionParams struct {
	OrgID       string `json:"org_id"`
	SessionID   string `json:"session_id"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) NicknameTakenInSession(ctx context.Context, arg NicknameTakenInSessionParams) (bool, error) {
	row := q.db.QueryRow(ctx, nicknameTakenInSession, arg.OrgID, arg.SessionID, arg.DisplayName)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const purgeExpiredTombstones = `-- name: PurgeExpiredTombstones :exec
DELETE FROM tombstones
WHERE expires_at <= $1
`

func (q *Queries) PurgeExpiredTombstones(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.Exec(ctx, purgeExpiredTombstones, expiresAt)
	return err
}

const recordTombstone = `-- name: RecordTombstone :exec
INSERT INTO tombstones (session_id, org_id, members_count, commits_count, auto_merges_count,
                        duration_seconds, end_reason, ended_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (session_id) DO NOTHING
`

type RecordTombstoneParams struct {
	SessionID       string     `json:"session_id"`
	OrgID           string     `json:"org_id"`
	MembersCount    int64      `json:"members_count"`
	CommitsCount    int64      `json:"commits_count"`
	AutoMergesCount int64      `json:"auto_merges_count"`
	DurationSeconds int64      `json:"duration_seconds"`
	EndReason       string     `json:"end_reason"`
	EndedAt         *time.Time `json:"ended_at"`
	ExpiresAt       time.Time  `json:"expires_at"`
}

func (q *Queries) RecordTombstone(ctx context.Context, arg RecordTombstoneParams) error {
	_, err := q.db.Exec(ctx, recordTombstone,
		arg.SessionID,
		arg.OrgID,
		arg.MembersCount,
		arg.CommitsCount,
		arg.AutoMergesCount,
		arg.DurationSeconds,
		arg.EndReason,
		arg.EndedAt,
		arg.ExpiresAt,
	)
	return err
}

const resetSessionIdleTimer = `-- name: ResetSessionIdleTimer :exec
UPDATE sessions
SET last_substantive_activity_at = $1, idle_timeout_at = $2
WHERE org_id = $3 AND id = $4
`

type ResetSessionIdleTimerParams struct {
	LastSubstantiveActivityAt pgtype.Timestamptz `json:"last_substantive_activity_at"`
	IdleTimeoutAt             pgtype.Timestamptz `json:"idle_timeout_at"`
	OrgID                     string             `json:"org_id"`
	ID                        string             `json:"id"`
}

func (q *Queries) ResetSessionIdleTimer(ctx context.Context, arg ResetSessionIdleTimerParams) error {
	_, err := q.db.Exec(ctx, resetSessionIdleTimer,
		arg.LastSubstantiveActivityAt,
		arg.IdleTimeoutAt,
		arg.OrgID,
		arg.ID,
	)
	return err
}

const setFinalizeLock = `-- name: SetFinalizeLock :exec
UPDATE sessions
SET finalize_locked_by_account_id = $1
WHERE org_id = $2 AND id = $3
`

type SetFinalizeLockParams struct {
	FinalizeLockedByAccountID pgtype.Text `json:"finalize_locked_by_account_id"`
	OrgID                     string      `json:"org_id"`
	ID                        string      `json:"id"`
}

func (q *Queries) SetFinalizeLock(ctx context.Context, arg SetFinalizeLockParams) error {
	_, err := q.db.Exec(ctx, setFinalizeLock, arg.FinalizeLockedByAccountID, arg.OrgID, arg.ID)
	return err
}

const setSessionBaseSHA = `-- name: SetSessionBaseSHA :exec
UPDATE sessions
SET base_sha = $1
WHERE org_id = $2 AND id = $3
`

type SetSessionBaseSHAParams struct {
	BaseSha *string `json:"base_sha"`
	OrgID   string  `json:"org_id"`
	ID      string  `json:"id"`
}

func (q *Queries) SetSessionBaseSHA(ctx context.Context, arg SetSessionBaseSHAParams) error {
	_, err := q.db.Exec(ctx, setSessionBaseSHA, arg.BaseSha, arg.OrgID, arg.ID)
	return err
}

const setSessionEndReason = `-- name: SetSessionEndReason :exec
UPDATE sessions
SET end_reason = $1, ended_at = $2
WHERE org_id = $3 AND id = $4
`

type SetSessionEndReasonParams struct {
	EndReason pgtype.Text `json:"end_reason"`
	EndedAt   *time.Time  `json:"ended_at"`
	OrgID     string      `json:"org_id"`
	ID        string      `json:"id"`
}

func (q *Queries) SetSessionEndReason(ctx context.Context, arg SetSessionEndReasonParams) error {
	_, err := q.db.Exec(ctx, setSessionEndReason,
		arg.EndReason,
		arg.EndedAt,
		arg.OrgID,
		arg.ID,
	)
	return err
}

const updateSessionGoalScopeMode = `-- name: UpdateSessionGoalScopeMode :exec
UPDATE sessions
SET goal = $1, writable_scope = $2, default_mode = $3
WHERE org_id = $4 AND id = $5
`

type UpdateSessionGoalScopeModeParams struct {
	Goal          string `json:"goal"`
	WritableScope string `json:"writable_scope"`
	DefaultMode   string `json:"default_mode"`
	OrgID         string `json:"org_id"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateSessionGoalScopeMode(ctx context.Context, arg UpdateSessionGoalScopeModeParams) error {
	_, err := q.db.Exec(ctx, updateSessionGoalScopeMode,
		arg.Goal,
		arg.WritableScope,
		arg.DefaultMode,
		arg.OrgID,
		arg.ID,
	)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE sessions
SET status = $1
WHERE org_id = $2 AND id = $3
`

type UpdateSessionStatusParams struct {
	Status string `json:"status"`
	OrgID  string `json:"org_id"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSessionStatus, arg.Status, arg.OrgID, arg.ID)
	return err
}
