// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: session_invites.sql

package pgstore

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionInviteByID = `-- name: GetSessionInviteByID :one
SELECT id, org_id, session_id, inviter_account_id, invitee_email, token_hash, created_at, expires_at, accepted_at, accepted_by_account_id FROM session_invites WHERE id = $1
`

func (q *Queries) GetSessionInviteByID(ctx context.Context, id string) (SessionInvite, error) {
	row := q.db.QueryRow(ctx, getSessionInviteByID, id)
	var i SessionInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SessionID,
		&i.InviterAccountID,
		&i.InviteeEmail,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedByAccountID,
	)
	return i, err
}

const getSessionInviteByTokenHash = `-- name: GetSessionInviteByTokenHash :one
SELECT id, org_id, session_id, inviter_account_id, invitee_email, token_hash, created_at, expires_at, accepted_at, accepted_by_account_id FROM session_invites WHERE token_hash = $1
`

func (q *Queries) GetSessionInviteByTokenHash(ctx context.Context, tokenHash string) (SessionInvite, error) {
	row := q.db.QueryRow(ctx, getSessionInviteByTokenHash, tokenHash)
	var i SessionInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SessionID,
		&i.InviterAccountID,
		&i.InviteeEmail,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedByAccountID,
	)
	return i, err
}

const insertSessionInvite = `-- name: InsertSessionInvite :one
INSERT INTO session_invites (id, org_id, session_id, inviter_account_id, invitee_email, token_hash, created_at, expires_at, accepted_at, accepted_by_account_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, org_id, session_id, inviter_account_id, invitee_email, token_hash, created_at, expires_at, accepted_at, accepted_by_account_id
`

type InsertSessionInviteParams struct {
	ID                  string      `json:"id"`
	OrgID               string      `json:"org_id"`
	SessionID           string      `json:"session_id"`
	InviterAccountID    string      `json:"inviter_account_id"`
	InviteeEmail        string      `json:"invitee_email"`
	TokenHash           string      `json:"token_hash"`
	CreatedAt           time.Time   `json:"created_at"`
	ExpiresAt           time.Time   `json:"expires_at"`
	AcceptedAt          *time.Time  `json:"accepted_at"`
	AcceptedByAccountID pgtype.Text `json:"accepted_by_account_id"`
}

func (q *Queries) InsertSessionInvite(ctx context.Context, arg InsertSessionInviteParams) (SessionInvite, error) {
	row := q.db.QueryRow(ctx, insertSessionInvite,
		arg.ID,
		arg.OrgID,
		arg.SessionID,
		arg.InviterAccountID,
		arg.InviteeEmail,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.AcceptedAt,
		arg.AcceptedByAccountID,
	)
	var i SessionInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SessionID,
		&i.InviterAccountID,
		&i.InviteeEmail,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedByAccountID,
	)
	return i, err
}

const listPendingSessionInvitesForSession = `-- name: ListPendingSessionInvitesForSession :many
SELECT id, org_id, session_id, inviter_account_id, invitee_email, token_hash, created_at, expires_at, accepted_at, accepted_by_account_id FROM session_invites
WHERE session_id = $1 AND accepted_at IS NULL AND expires_at > $2
ORDER BY created_at ASC
`

type ListPendingSessionInvitesForSessionParams struct {
	SessionID string    `json:"session_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) ListPendingSessionInvitesForSession(ctx context.Context, arg ListPendingSessionInvitesForSessionParams) ([]SessionInvite, error) {
	rows, err := q.db.Query(ctx, listPendingSessionInvitesForSession, arg.SessionID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionInvite
	for rows.Next() {
		var i SessionInvite
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SessionID,
			&i.InviterAccountID,
			&i.InviteeEmail,
			&i.TokenHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedByAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionInviteAccepted = `-- name: MarkSessionInviteAccepted :exec
UPDATE session_invites
SET accepted_at = $1, accepted_by_account_id = $2
WHERE id = $3 AND accepted_at IS NULL
`

type MarkSessionInviteAcceptedParams struct {
	AcceptedAt          *time.Time  `json:"accepted_at"`
	AcceptedByAccountID pgtype.Text `json:"accepted_by_account_id"`
	ID                  string      `json:"id"`
}

func (q *Queries) MarkSessionInviteAccepted(ctx context.Context, arg MarkSessionInviteAcceptedParams) error {
	_, err := q.db.Exec(ctx, markSessionInviteAccepted, arg.AcceptedAt, arg.AcceptedByAccountID, arg.ID)
	return err
}
