// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	// Details Optional structured context for the error. Shape is
	// code-specific; omitted when there is nothing to add.
	Details map[string]interface{} `json:"details,omitempty"`

	// Error machine-readable error code (e.g. "auth.invalid_token")
	Error string `json:"error"`

	// Message human-readable error message
	Message string `json:"message"`
}

// MagicLinkExchangeBody defines model for MagicLinkExchangeBody.
type MagicLinkExchangeBody struct {
	// Token Raw magic-link token from the URL query parameter
	Token string `json:"token"`
}

// MagicLinkRequestBody defines model for MagicLinkRequestBody.
type MagicLinkRequestBody struct {
	Email openapi_types.Email `json:"email"`
}

// OAuthCallbackBody defines model for OAuthCallbackBody.
type OAuthCallbackBody struct {
	// Code Authorization code from the provider
	Code string `json:"code"`

	// Provider OAuth provider name, e.g. "github"
	Provider string `json:"provider"`

	// State State nonce echoed back from the provider
	State string `json:"state"`
}

// OAuthStartBody defines model for OAuthStartBody.
type OAuthStartBody struct {
	// Provider OAuth provider name, e.g. "github"
	Provider string `json:"provider"`
}

// OAuthStartResponse defines model for OAuthStartResponse.
type OAuthStartResponse struct {
	// AuthorizeUrl Provider authorization URL the browser should be redirected to
	AuthorizeUrl string `json:"authorize_url"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessExpiresAt  time.Time `json:"access_expires_at"`
	AccessToken      string    `json:"access_token"`
	RefreshExpiresAt time.Time `json:"refresh_expires_at"`
	RefreshToken     string    `json:"refresh_token"`
}

// Forbidden defines model for Forbidden.
type Forbidden = ErrorEnvelope

// NotFound defines model for NotFound.
type NotFound = ErrorEnvelope

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorEnvelope

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// RefreshTokenJSONBody defines parameters for RefreshToken.
type RefreshTokenJSONBody struct {
	RefreshToken string `json:"refresh_token"`
}

// RevokeTokenJSONBody defines parameters for RevokeToken.
type RevokeTokenJSONBody struct {
	RevokeAll bool   `json:"revoke_all,omitempty"`
	Token     string `json:"token"`
}

// ExchangeMagicLinkJSONRequestBody defines body for ExchangeMagicLink for application/json ContentType.
type ExchangeMagicLinkJSONRequestBody = MagicLinkExchangeBody

// RequestMagicLinkJSONRequestBody defines body for RequestMagicLink for application/json ContentType.
type RequestMagicLinkJSONRequestBody = MagicLinkRequestBody

// OauthCallbackJSONRequestBody defines body for OauthCallback for application/json ContentType.
type OauthCallbackJSONRequestBody = OAuthCallbackBody

// StartOAuthJSONRequestBody defines body for StartOAuth for application/json ContentType.
type StartOAuthJSONRequestBody = OAuthStartBody

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody RefreshTokenJSONBody

// RevokeTokenJSONRequestBody defines body for RevokeToken for application/json ContentType.
type RevokeTokenJSONRequestBody RevokeTokenJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Exchange a magic-link token for a portal token pair
	// (POST /api/auth/magic-link/exchange)
	ExchangeMagicLink(w http.ResponseWriter, r *http.Request)
	// Request a magic-link sign-in email
	// (POST /api/auth/magic-link/request)
	RequestMagicLink(w http.ResponseWriter, r *http.Request)
	// Exchange OAuth authorization code for a portal token pair
	// (POST /api/auth/oauth/callback)
	OauthCallback(w http.ResponseWriter, r *http.Request)
	// Begin OAuth authorization flow — returns the provider authorize URL
	// (POST /api/auth/oauth/start)
	StartOAuth(w http.ResponseWriter, r *http.Request)
	// Exchange a refresh token for a new access+refresh pair
	// (POST /api/auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// Revoke a token (or all tokens for the account)
	// (POST /api/auth/revoke)
	RevokeToken(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Exchange a magic-link token for a portal token pair
// (POST /api/auth/magic-link/exchange)
func (_ Unimplemented) ExchangeMagicLink(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request a magic-link sign-in email
// (POST /api/auth/magic-link/request)
func (_ Unimplemented) RequestMagicLink(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Exchange OAuth authorization code for a portal token pair
// (POST /api/auth/oauth/callback)
func (_ Unimplemented) OauthCallback(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Begin OAuth authorization flow — returns the provider authorize URL
// (POST /api/auth/oauth/start)
func (_ Unimplemented) StartOAuth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Exchange a refresh token for a new access+refresh pair
// (POST /api/auth/refresh)
func (_ Unimplemented) RefreshToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke a token (or all tokens for the account)
// (POST /api/auth/revoke)
func (_ Unimplemented) RevokeToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ExchangeMagicLink operation middleware
func (siw *ServerInterfaceWrapper) ExchangeMagicLink(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExchangeMagicLink(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestMagicLink operation middleware
func (siw *ServerInterfaceWrapper) RequestMagicLink(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestMagicLink(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OauthCallback operation middleware
func (siw *ServerInterfaceWrapper) OauthCallback(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OauthCallback(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartOAuth operation middleware
func (siw *ServerInterfaceWrapper) StartOAuth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartOAuth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeToken operation middleware
func (siw *ServerInterfaceWrapper) RevokeToken(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/magic-link/exchange", wrapper.ExchangeMagicLink)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/magic-link/request", wrapper.RequestMagicLink)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/oauth/callback", wrapper.OauthCallback)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/oauth/start", wrapper.StartOAuth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/refresh", wrapper.RefreshToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/revoke", wrapper.RevokeToken)
	})

	return r
}

type ForbiddenJSONResponse ErrorEnvelope

type NotFoundJSONResponse ErrorEnvelope

type UnauthorizedJSONResponse ErrorEnvelope

type ExchangeMagicLinkRequestObject struct {
	Body *ExchangeMagicLinkJSONRequestBody
}

type ExchangeMagicLinkResponseObject interface {
	VisitExchangeMagicLinkResponse(w http.ResponseWriter) error
}

type ExchangeMagicLink200JSONResponse TokenPair

func (response ExchangeMagicLink200JSONResponse) VisitExchangeMagicLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ExchangeMagicLink401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ExchangeMagicLink401JSONResponse) VisitExchangeMagicLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RequestMagicLinkRequestObject struct {
	Body *RequestMagicLinkJSONRequestBody
}

type RequestMagicLinkResponseObject interface {
	VisitRequestMagicLinkResponse(w http.ResponseWriter) error
}

type RequestMagicLink204Response struct {
}

func (response RequestMagicLink204Response) VisitRequestMagicLinkResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RequestMagicLink500JSONResponse ErrorEnvelope

func (response RequestMagicLink500JSONResponse) VisitRequestMagicLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type OauthCallbackRequestObject struct {
	Body *OauthCallbackJSONRequestBody
}

type OauthCallbackResponseObject interface {
	VisitOauthCallbackResponse(w http.ResponseWriter) error
}

type OauthCallback200JSONResponse TokenPair

func (response OauthCallback200JSONResponse) VisitOauthCallbackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type OauthCallback400JSONResponse ErrorEnvelope

func (response OauthCallback400JSONResponse) VisitOauthCallbackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type OauthCallback401JSONResponse struct{ UnauthorizedJSONResponse }

func (response OauthCallback401JSONResponse) VisitOauthCallbackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StartOAuthRequestObject struct {
	Body *StartOAuthJSONRequestBody
}

type StartOAuthResponseObject interface {
	VisitStartOAuthResponse(w http.ResponseWriter) error
}

type StartOAuth200JSONResponse OAuthStartResponse

func (response StartOAuth200JSONResponse) VisitStartOAuthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StartOAuth400JSONResponse ErrorEnvelope

func (response StartOAuth400JSONResponse) VisitStartOAuthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type StartOAuth503JSONResponse ErrorEnvelope

func (response StartOAuth503JSONResponse) VisitStartOAuthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse TokenPair

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeTokenRequestObject struct {
	Body *RevokeTokenJSONRequestBody
}

type RevokeTokenResponseObject interface {
	VisitRevokeTokenResponse(w http.ResponseWriter) error
}

type RevokeToken204Response struct {
}

func (response RevokeToken204Response) VisitRevokeTokenResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeToken401JSONResponse) VisitRevokeTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Exchange a magic-link token for a portal token pair
	// (POST /api/auth/magic-link/exchange)
	ExchangeMagicLink(ctx context.Context, request ExchangeMagicLinkRequestObject) (ExchangeMagicLinkResponseObject, error)
	// Request a magic-link sign-in email
	// (POST /api/auth/magic-link/request)
	RequestMagicLink(ctx context.Context, request RequestMagicLinkRequestObject) (RequestMagicLinkResponseObject, error)
	// Exchange OAuth authorization code for a portal token pair
	// (POST /api/auth/oauth/callback)
	OauthCallback(ctx context.Context, request OauthCallbackRequestObject) (OauthCallbackResponseObject, error)
	// Begin OAuth authorization flow — returns the provider authorize URL
	// (POST /api/auth/oauth/start)
	StartOAuth(ctx context.Context, request StartOAuthRequestObject) (StartOAuthResponseObject, error)
	// Exchange a refresh token for a new access+refresh pair
	// (POST /api/auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// Revoke a token (or all tokens for the account)
	// (POST /api/auth/revoke)
	RevokeToken(ctx context.Context, request RevokeTokenRequestObject) (RevokeTokenResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ExchangeMagicLink operation middleware
func (sh *strictHandler) ExchangeMagicLink(w http.ResponseWriter, r *http.Request) {
	var request ExchangeMagicLinkRequestObject

	var body ExchangeMagicLinkJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExchangeMagicLink(ctx, request.(ExchangeMagicLinkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExchangeMagicLink")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExchangeMagicLinkResponseObject); ok {
		if err := validResponse.VisitExchangeMagicLinkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RequestMagicLink operation middleware
func (sh *strictHandler) RequestMagicLink(w http.ResponseWriter, r *http.Request) {
	var request RequestMagicLinkRequestObject

	var body RequestMagicLinkJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RequestMagicLink(ctx, request.(RequestMagicLinkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestMagicLink")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RequestMagicLinkResponseObject); ok {
		if err := validResponse.VisitRequestMagicLinkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// OauthCallback operation middleware
func (sh *strictHandler) OauthCallback(w http.ResponseWriter, r *http.Request) {
	var request OauthCallbackRequestObject

	var body OauthCallbackJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.OauthCallback(ctx, request.(OauthCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OauthCallback")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(OauthCallbackResponseObject); ok {
		if err := validResponse.VisitOauthCallbackResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartOAuth operation middleware
func (sh *strictHandler) StartOAuth(w http.ResponseWriter, r *http.Request) {
	var request StartOAuthRequestObject

	var body StartOAuthJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartOAuth(ctx, request.(StartOAuthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartOAuth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartOAuthResponseObject); ok {
		if err := validResponse.VisitStartOAuthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(w http.ResponseWriter, r *http.Request) {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeToken operation middleware
func (sh *strictHandler) RevokeToken(w http.ResponseWriter, r *http.Request) {
	var request RevokeTokenRequestObject

	var body RevokeTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeToken(ctx, request.(RevokeTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeTokenResponseObject); ok {
		if err := validResponse.VisitRevokeTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fndbhu7EX6VAXsuLFReOXUKFMpNncBpA5wTG7ZzFRk2xR1pGXPJzZBrRQ0E9CH6hH2SYrjU6m9lu6lj",
	"9NwYWi5/Ps58HH7f+rtQrqycRRu8GH4XhL5y1mN8eO9orPMcLT8oZwPawD9lVRmtZNDODr54F197VWAp",
	"+dcvhBMxFH8YrGYeNG/94JTI0am9R+MqFIvFoi9y9Ip0xZOJoZB1KNAGnh1zGNcBrAtQIZU6cMvEEYQC",
	"gfBrjZ5bXIUUoYhFX3x04b2rbf5ygFdAyNUBwREQeleTwgh9EuEs+uKT5b050v/AF4RXau+1nTIsbe+l",
	"0TmMURISBHeHVvCINBmvtTnf8LuoiOMbdEOIHIPUJv6Uea55DWnO17oEqnEbwlnV9AMfqFahJswhbv5b",
	"aNOJvG4Gl4WsELQfWeVyPPQVKj3R6g24lP5ZgZYHEPfi+Ba8ueBA5nk2sqIvwpyBCzf+gipw3OPUDfiN",
	"wEhVaIuHhDKXY5MgAK8LB5hNMxhFMmYpbDcxXiPRE32B32RZGUx03eyxguADaTtlCCV6L6e4C6KoS2m3",
	"ISx7r6+zzN2eJRb9yENNTK3Pacurda87wvKbnGr1q7Z3p99UIe0U37p8vpvxZsEd4BdyBiXPcGi0vWtg",
	"wYRcGbP56eJX+FojzaGSJEsMSI9ibhZ6EOlFc9S6gWIptYk/2qDVHumv6TFTrhR9MXFUyiCGqfujgYy9",
	"ukCdndSheCeNGUt1142IqbQbuZNUBOJpb+jWxq0id6/zrmD1RftuZ8YIpR0LVpbYh8TgqQ5FPR6JDTI1",
	"jV2L+CBDB+ZLbgbrrEJAVTiuzFLdPQX4VkDXOsbwLJfcG+LLIGlPxl8gIvvQPwz3It2hu5DbG+CmJrOL",
	"+3yJWG6QhI8TR3lMbuaRwBeuNlzHgTDXhIorY3CPwt9cvWsPV3wIz6WmDuhKofc3+K3ShP5GxourPU65",
	"DHgYdIldrEpD21Ky04FwQuiLH5p8OXbf7NsxWMeyPbrfsctOdLux48ODqiYd5pd8nTZBa65aJsbq6f1y",
	"W66SX2ve0/Z1yc0btzRo72s+dPPmtDkK0kDD8olxs2xkzwk92gDOgjQGLk4vr0BJY3wffnt3vvwpbQ5T",
	"HQ7dPdLh36+uzi9H9kB64J/wVnqtoJLezxzlvQzOLKb1KyTgagpSKVfb0Fy1UTdwEBqsq+wUIVSNGNF2",
	"4jpuD0bna5pIha0E+CJLj75Iu8vgUtupQUhSyk0gUNyvo5H1SPfIiiZgnMTDgZOVPuSaMkXbixtVRnNE",
	"GJMf2QNXoeU+8TmC6WWQqrGdAtUGPWg7srlTfnB5fvouK3MY1UdHxwh/Q8sqMykXkir4bGRH9qxCe3L+",
	"Ae6RvHZ2CMfZUXYMB8apO8zh3//8F6wDg1Jqa7RFyB1G/QJzDCPr64q3DcfZqzdQ6mkjaCGQnk7jPuGJ",
	"oHoR1fauDhpUvh57DNzZB5LaBt8bjuwhfPIIt7Y2hkXIkOOMt/Dx7ApuOVZD+NycpT6MBPcaievbdliq",
	"ocM0ID364S0cSCI553yVrNWOs1c9HvXRwe0Mx4Vzd9xrzJFatv/SKNFbkNa6EGPAr06MgaRRobZcH1dK",
	"OEsv3jA/gaUy4D3SfMYasRGEOsQav8kv0RcpZ2IojrKj7BUXk8QRMRQxYqIvKhmKeJQHstIDrqCDle4Z",
	"YNJOsVw6H8tW60c+5GIoluqqFTGiv7QMy1vtWYxAt5xbbJY/zmxsWPN4fzo6ejYQq+ujw4lcNZVEakrl",
	"jAP++ujVvklblIMN57ReacXw83Vf+LosJc3Xgg2yQ5w6ArksnaHFEufrzG3K0v7UJjn6Ypldl79PSuzr",
	"3cobJ4MYlqhtIV4aB47Aa4M2mDmXeKy4qOgJuypCz6fuzrqZ7XHK/vyMhHnUvn7gCh+9Y1PxG4d00GDP",
	"0Wg+6zCR2tSEvQfJkcK3yQ2vp/ZQ2yYYW1xw8a9KGn8/D87kmhX4SSTYtRu/g6P9ojxp/LEjaGRaDn5l",
	"Wvrc3tqBUvtSBlX8xPrTSDPZYfWeVIUa5nn2EvtpF61GXOhncm7lv16YcB12qiPvJztGiVDmUXW0dmlp",
	"kl6clJ+aqsnkq61ydqKn8eNXayNjNT1+OUCtv2ThuQaIpWahfSqyD1L8LU617eQ3G5EoeAlDTdZvfBho",
	"+8aPQ1t0TwbroZs2drhqTduPkX3T0P6XxnGze4cB/P8pxx9xtlFbfqLMSlHZ0FgWZ9D46D8uX3fUOMJ7",
	"d4cP5ZzfP3fKec4badK3l4msTRDDiTQe24SOnTMo438TnkiN/4USHRqNd66Wdwa7qYDPksPNzxGfrxdb",
	"8ohjAzKlkiWhNOmO8q1JT/6/12zuscljOfHxbfzeFT8M+OFg8L1wPizYg0nS7DpjNIpEhDYxwjglDTcP",
	"//L69fHOp5Lz5h7lDtHx873KyK4X/wkAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
