// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for CommentAddedPayloadAuthorKind.
const (
	Agent CommentAddedPayloadAuthorKind = "agent"
	Human CommentAddedPayloadAuthorKind = "human"
)

// Valid indicates whether the value is a known member of the CommentAddedPayloadAuthorKind enum.
func (e CommentAddedPayloadAuthorKind) Valid() bool {
	switch e {
	case Agent:
		return true
	case Human:
		return true
	default:
		return false
	}
}

// Defines values for CommentAddedPayloadKind.
const (
	ActionRequest CommentAddedPayloadKind = "action-request"
	Fyi           CommentAddedPayloadKind = "fyi"
	Question      CommentAddedPayloadKind = "question"
	Suggestion    CommentAddedPayloadKind = "suggestion"
)

// Valid indicates whether the value is a known member of the CommentAddedPayloadKind enum.
func (e CommentAddedPayloadKind) Valid() bool {
	switch e {
	case ActionRequest:
		return true
	case Fyi:
		return true
	case Question:
		return true
	case Suggestion:
		return true
	default:
		return false
	}
}

// Defines values for ConflictDetectedPayloadStatus.
const (
	Abandoned ConflictDetectedPayloadStatus = "abandoned"
	Open      ConflictDetectedPayloadStatus = "open"
	Resolved  ConflictDetectedPayloadStatus = "resolved"
)

// Valid indicates whether the value is a known member of the ConflictDetectedPayloadStatus enum.
func (e ConflictDetectedPayloadStatus) Valid() bool {
	switch e {
	case Abandoned:
		return true
	case Open:
		return true
	case Resolved:
		return true
	default:
		return false
	}
}

// Defines values for EventEnvelopeType.
const (
	CommentAdded      EventEnvelopeType = "comment.added"
	CommentResolved   EventEnvelopeType = "comment.resolved"
	CommitArrived     EventEnvelopeType = "commit.arrived"
	ConflictDetected  EventEnvelopeType = "conflict.detected"
	ConflictResolved  EventEnvelopeType = "conflict.resolved"
	MergeSucceeded    EventEnvelopeType = "merge.succeeded"
	ModeChanged       EventEnvelopeType = "mode.changed"
	PresenceUpdated   EventEnvelopeType = "presence.updated"
	RefForked         EventEnvelopeType = "ref.forked"
	SessionEnded      EventEnvelopeType = "session.ended"
	SessionFinalizing EventEnvelopeType = "session.finalizing"
	TurnEnded         EventEnvelopeType = "turn.ended"
)

// Valid indicates whether the value is a known member of the EventEnvelopeType enum.
func (e EventEnvelopeType) Valid() bool {
	switch e {
	case CommentAdded:
		return true
	case CommentResolved:
		return true
	case CommitArrived:
		return true
	case ConflictDetected:
		return true
	case ConflictResolved:
		return true
	case MergeSucceeded:
		return true
	case ModeChanged:
		return true
	case PresenceUpdated:
		return true
	case RefForked:
		return true
	case SessionEnded:
		return true
	case SessionFinalizing:
		return true
	case TurnEnded:
		return true
	default:
		return false
	}
}

// Defines values for EventEnvelopeVersion.
const (
	N1 EventEnvelopeVersion = 1
)

// Valid indicates whether the value is a known member of the EventEnvelopeVersion enum.
func (e EventEnvelopeVersion) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for SessionEndedPayloadReason.
const (
	Abandon  SessionEndedPayloadReason = "abandon"
	Finalize SessionEndedPayloadReason = "finalize"
	Timeout  SessionEndedPayloadReason = "timeout"
)

// Valid indicates whether the value is a known member of the SessionEndedPayloadReason enum.
func (e SessionEndedPayloadReason) Valid() bool {
	switch e {
	case Abandon:
		return true
	case Finalize:
		return true
	case Timeout:
		return true
	default:
		return false
	}
}

// AcceptInviteBody defines model for AcceptInviteBody.
type AcceptInviteBody struct {
	// Token Raw invite token from the email link query parameter
	Token string `json:"token"`
}

// CommentAddedPayload A comment was posted in the session. Payload is the full comment per PROTOCOL.md comment schema. PROTOCOL.md canonical fields: id, session_id, author_id, author_kind, anchor, body, addressed_to, kind, created_at, resolved_at, resolved_by, resolution_note.
type CommentAddedPayload struct {
	// AddressedTo Addressing token (e.g. "@user", "@user/branch", "@all-agents")
	AddressedTo string        `json:"addressed_to,omitempty"`
	Anchor      CommentAnchor `json:"anchor"`

	// AuthorId Account ID of the comment author
	AuthorId string `json:"author_id"`

	// AuthorKind Whether the author is a human or an agent
	AuthorKind CommentAddedPayloadAuthorKind `json:"author_kind"`

	// Body Comment body in markdown
	Body string `json:"body"`

	// CreatedAt ISO-8601 timestamp of creation
	CreatedAt time.Time `json:"created_at"`

	// Id Comment ID (UUID)
	Id string `json:"id"`

	// Kind Comment kind
	Kind CommentAddedPayloadKind `json:"kind"`

	// ResolutionNote Optional resolution note
	ResolutionNote string `json:"resolution_note,omitempty"`

	// ResolvedAt ISO-8601 timestamp when resolved; null if open
	ResolvedAt time.Time `json:"resolved_at,omitempty"`

	// ResolvedBy Account ID of resolver; null if open
	ResolvedBy string `json:"resolved_by,omitempty"`

	// SessionId Session the comment belongs to
	SessionId string `json:"session_id"`
}

// CommentAddedPayloadAuthorKind Whether the author is a human or an agent
type CommentAddedPayloadAuthorKind string

// CommentAddedPayloadKind Comment kind
type CommentAddedPayloadKind string

// CommentAnchor defines model for CommentAnchor.
type CommentAnchor struct {
	// CommitSha The commit being commented on
	CommitSha string `json:"commit_sha"`

	// FilePath File within the commit's tree; null for commit-level comments
	FilePath string `json:"file_path,omitempty"`

	// LineRange 1-indexed line range; null for file-level or commit-level comments
	LineRange ConflictFileRange `json:"line_range,omitempty"`
}

// CommentResolvedPayload A comment was marked resolved. PROTOCOL.md canonical fields: comment_id, resolved_by, note.
type CommentResolvedPayload struct {
	// CommentId The comment ID that was resolved
	CommentId string `json:"comment_id"`

	// Note Optional resolution note
	Note string `json:"note,omitempty"`

	// ResolvedBy Account ID of the user who resolved the comment
	ResolvedBy string `json:"resolved_by"`
}

// CommitArrivedPayload A commit was pushed to a session ref. PROTOCOL.md canonical fields: ref, sha, author_id, summary.
type CommitArrivedPayload struct {
	// AuthorId Account ID of the commit author
	AuthorId string `json:"author_id"`

	// Ref The session ref the commit landed on (e.g. jam/<session>/<user>/<branch>)
	Ref string `json:"ref"`

	// Sha The commit SHA that arrived
	Sha string `json:"sha"`

	// Summary One-line summary of the commit message
	Summary string `json:"summary"`
}

// ConflictDetectedPayload Auto-merger detected a three-way merge conflict. Payload is the full conflict event per PROTOCOL.md conflict event schema. PROTOCOL.md canonical fields: id, session_id, source_commit_sha, source_ref, draft_tip_sha, ancestor_sha, conflicts, addressed_to, status, resolving_commit_sha, resolved_at, created_at.
type ConflictDetectedPayload struct {
	// AddressedTo Addressing tokens for impacted participants (e.g. "@user/branch")
	AddressedTo []string `json:"addressed_to"`

	// AncestorSha The common ancestor commit SHA
	AncestorSha string `json:"ancestor_sha"`

	// Conflicts Per-file conflict details
	Conflicts []ConflictFile `json:"conflicts"`

	// CreatedAt ISO-8601 timestamp when the conflict was detected
	CreatedAt time.Time `json:"created_at"`

	// DraftTipSha The draft tip at the time of the failed merge attempt
	DraftTipSha string `json:"draft_tip_sha"`

	// Id Conflict event ID (UUID)
	Id string `json:"id"`

	// ResolvedAt ISO-8601 timestamp when the conflict was resolved
	ResolvedAt time.Time `json:"resolved_at,omitempty"`

	// ResolvingCommitSha Set when a Resolves-Conflict trailer matches this event
	ResolvingCommitSha string `json:"resolving_commit_sha,omitempty"`

	// SessionId Session the conflict belongs to
	SessionId string `json:"session_id"`

	// SourceCommitSha The commit that could not be merged
	SourceCommitSha string `json:"source_commit_sha"`

	// SourceRef The ref the source commit came from
	SourceRef string `json:"source_ref"`

	// Status Current status of this conflict
	Status ConflictDetectedPayloadStatus `json:"status"`
}

// ConflictDetectedPayloadStatus Current status of this conflict
type ConflictDetectedPayloadStatus string

// ConflictFile defines model for ConflictFile.
type ConflictFile struct {
	// File File path within the repository
	File string `json:"file"`

	// Ranges Line ranges in conflict within this file
	Ranges []ConflictFileRange `json:"ranges"`
}

// ConflictFileRange defines model for ConflictFileRange.
type ConflictFileRange struct {
	// End End line (1-indexed) of the conflict range
	End int `json:"end"`

	// Start Start line (1-indexed) of the conflict range
	Start int `json:"start"`
}

// ConflictResolvedPayload A conflict has been resolved via a commit with a matching Resolves-Conflict trailer. PROTOCOL.md canonical fields: event_id, resolving_commit_sha.
type ConflictResolvedPayload struct {
	// EventId The conflict event ID that was resolved
	EventId string `json:"event_id"`

	// ResolvingCommitSha The commit SHA that resolved the conflict
	ResolvingCommitSha string `json:"resolving_commit_sha"`
}

// CreateOrgBody defines model for CreateOrgBody.
type CreateOrgBody struct {
	// Name Desired org name; used to derive the slug
	Name string `json:"name"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	// Details Optional structured context for the error. Shape is
	// code-specific; omitted when there is nothing to add.
	Details map[string]interface{} `json:"details,omitempty"`

	// Error machine-readable error code (e.g. "auth.invalid_token")
	Error string `json:"error"`

	// Message human-readable error message
	Message string `json:"message"`
}

// EventEnvelope defines model for EventEnvelope.
type EventEnvelope struct {
	Payload EventEnvelope_Payload `json:"payload"`

	// Seq Monotonic per-session sequence number
	Seq int64 `json:"seq"`

	// SessionId Session this event belongs to
	SessionId string `json:"session_id"`

	// Timestamp ISO-8601 timestamp of event emission
	Timestamp time.Time `json:"timestamp"`

	// Type Event type; used as discriminator for payload
	Type EventEnvelopeType `json:"type"`

	// Version Envelope version; always 1
	Version EventEnvelopeVersion `json:"version"`
}

// EventEnvelope_Payload defines model for EventEnvelope.Payload.
type EventEnvelope_Payload struct {
	union json.RawMessage
}

// EventEnvelopeType Event type; used as discriminator for payload
type EventEnvelopeType string

// EventEnvelopeVersion Envelope version; always 1
type EventEnvelopeVersion int

// InviteBody defines model for InviteBody.
type InviteBody struct {
	// Email Email address to invite
	Email openapi_types.Email `json:"email"`
}

// InviteRef defines model for InviteRef.
type InviteRef struct {
	// ExpiresAt ISO-8601 timestamp when the invite expires
	ExpiresAt time.Time `json:"expires_at"`

	// Id Invite ID
	Id string `json:"id"`

	// RecipientEmail Email address the invite was sent to
	RecipientEmail openapi_types.Email `json:"recipient_email"`
}

// MagicLinkExchangeBody defines model for MagicLinkExchangeBody.
type MagicLinkExchangeBody struct {
	// Token Raw magic-link token from the URL query parameter
	Token string `json:"token"`
}

// MagicLinkRequestBody defines model for MagicLinkRequestBody.
type MagicLinkRequestBody struct {
	Email openapi_types.Email `json:"email"`
}

// MeOrgMembership defines model for MeOrgMembership.
type MeOrgMembership struct {
	// Id Org UUID
	Id string `json:"id"`

	// Name Org display name
	Name string `json:"name"`

	// Role The authenticated account's role in this org
	Role string `json:"role"`

	// Slug URL-safe org slug
	Slug string `json:"slug"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	// DisplayName Human-readable display name
	DisplayName string `json:"display_name"`

	// Email Verified email address
	Email openapi_types.Email `json:"email"`

	// Id Account UUID
	Id string `json:"id"`

	// Orgs All org memberships for this account
	Orgs []MeOrgMembership `json:"orgs"`
}

// MemberRef defines model for MemberRef.
type MemberRef struct {
	// AccountId Account UUID
	AccountId string `json:"account_id"`

	// DisplayName Member's display name
	DisplayName string `json:"display_name"`

	// Email Member's email address
	Email openapi_types.Email `json:"email"`

	// JoinedAt ISO-8601 timestamp when the member joined the org
	JoinedAt time.Time `json:"joined_at"`

	// Role Member's role in the org
	Role string `json:"role"`
}

// MergeSucceededPayload Auto-merger successfully merged a source commit into the draft tip. PROTOCOL.md canonical fields: source_sha, draft_sha, merge_commit_sha.
type MergeSucceededPayload struct {
	// DraftSha The draft tip SHA after the merge
	DraftSha string `json:"draft_sha"`

	// MergeCommitSha The merge commit SHA created by the auto-merger
	MergeCommitSha string `json:"merge_commit_sha"`

	// SourceSha The source commit SHA that was merged
	SourceSha string `json:"source_sha"`
}

// ModeChangedPayload A ref's collaboration mode was changed. PROTOCOL.md canonical fields: ref, old_mode, new_mode.
type ModeChangedPayload struct {
	// NewMode The new mode
	NewMode string `json:"new_mode"`

	// OldMode The previous mode
	OldMode string `json:"old_mode"`

	// Ref The ref whose mode changed
	Ref string `json:"ref"`
}

// OAuthCallbackBody defines model for OAuthCallbackBody.
type OAuthCallbackBody struct {
	// Code Authorization code from the provider
	Code string `json:"code"`

	// Provider OAuth provider name, e.g. "github"
	Provider string `json:"provider"`

	// State State nonce echoed back from the provider
	State string `json:"state"`
}

// OAuthStartBody defines model for OAuthStartBody.
type OAuthStartBody struct {
	// Provider OAuth provider name, e.g. "github"
	Provider string `json:"provider"`
}

// OAuthStartResponse defines model for OAuthStartResponse.
type OAuthStartResponse struct {
	// AuthorizeUrl Provider authorization URL the browser should be redirected to
	AuthorizeUrl string `json:"authorize_url"`
}

// OrgRef defines model for OrgRef.
type OrgRef struct {
	// Id Org UUID
	Id string `json:"id"`

	// Name Org display name
	Name string `json:"name"`

	// Slug URL-safe org slug
	Slug string `json:"slug"`
}

// PresenceUpdatedPayload A participant's presence (active ref + tip SHA) was updated. PROTOCOL.md canonical fields: user_id, ref, current_sha, last_active.
type PresenceUpdatedPayload struct {
	// CurrentSha The current tip SHA of the participant's ref
	CurrentSha string `json:"current_sha"`

	// LastActive ISO-8601 timestamp of last participant activity
	LastActive time.Time `json:"last_active"`

	// Ref The ref the participant is currently on
	Ref string `json:"ref"`

	// UserId Account ID of the participant
	UserId string `json:"user_id"`
}

// RefForkedPayload A participant forked a new session ref. PROTOCOL.md canonical fields: ref, parent_sha, mode.
type RefForkedPayload struct {
	// Mode The collaboration mode of the new ref (sync or isolated)
	Mode string `json:"mode"`

	// ParentSha The commit SHA the new ref was parented at
	ParentSha string `json:"parent_sha"`

	// Ref The new ref name (e.g. jam/<session>/<user>/<branch>)
	Ref string `json:"ref"`
}

// SessionEndedPayload A session has ended (finalized, abandoned, or timed out). PROTOCOL.md canonical fields: reason.
type SessionEndedPayload struct {
	// Reason The reason the session ended
	Reason SessionEndedPayloadReason `json:"reason"`
}

// SessionEndedPayloadReason The reason the session ended
type SessionEndedPayloadReason string

// SessionFinalizingPayload A session has entered the finalizing state. PROTOCOL.md canonical fields: by_user_id.
type SessionFinalizingPayload struct {
	// ByUserId Account ID of the participant who initiated finalization
	ByUserId string `json:"by_user_id"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessExpiresAt  time.Time `json:"access_expires_at"`
	AccessToken      string    `json:"access_token"`
	RefreshExpiresAt time.Time `json:"refresh_expires_at"`
	RefreshToken     string    `json:"refresh_token"`
}

// TurnEndedPayload A participant's turn ended; they yielded control back to the human. PROTOCOL.md canonical fields: user_id, ref, final_sha.
type TurnEndedPayload struct {
	// FinalSha The final commit SHA on the ref at turn end
	FinalSha string `json:"final_sha"`

	// Ref The ref the participant was working on
	Ref string `json:"ref"`

	// UserId Account ID of the participant whose turn ended
	UserId string `json:"user_id"`
}

// Forbidden defines model for Forbidden.
type Forbidden = ErrorEnvelope

// NotFound defines model for NotFound.
type NotFound = ErrorEnvelope

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorEnvelope

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// RefreshTokenJSONBody defines parameters for RefreshToken.
type RefreshTokenJSONBody struct {
	RefreshToken string `json:"refresh_token"`
}

// RevokeTokenJSONBody defines parameters for RevokeToken.
type RevokeTokenJSONBody struct {
	RevokeAll bool   `json:"revoke_all,omitempty"`
	Token     string `json:"token"`
}

// ExchangeMagicLinkJSONRequestBody defines body for ExchangeMagicLink for application/json ContentType.
type ExchangeMagicLinkJSONRequestBody = MagicLinkExchangeBody

// RequestMagicLinkJSONRequestBody defines body for RequestMagicLink for application/json ContentType.
type RequestMagicLinkJSONRequestBody = MagicLinkRequestBody

// OauthCallbackJSONRequestBody defines body for OauthCallback for application/json ContentType.
type OauthCallbackJSONRequestBody = OAuthCallbackBody

// StartOAuthJSONRequestBody defines body for StartOAuth for application/json ContentType.
type StartOAuthJSONRequestBody = OAuthStartBody

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody RefreshTokenJSONBody

// RevokeTokenJSONRequestBody defines body for RevokeToken for application/json ContentType.
type RevokeTokenJSONRequestBody RevokeTokenJSONBody

// CreateOrgJSONRequestBody defines body for CreateOrg for application/json ContentType.
type CreateOrgJSONRequestBody = CreateOrgBody

// CreateOrgInviteJSONRequestBody defines body for CreateOrgInvite for application/json ContentType.
type CreateOrgInviteJSONRequestBody = InviteBody

// AcceptOrgInviteJSONRequestBody defines body for AcceptOrgInvite for application/json ContentType.
type AcceptOrgInviteJSONRequestBody = AcceptInviteBody

// AsCommitArrivedPayload returns the union data inside the EventEnvelope_Payload as a CommitArrivedPayload
func (t EventEnvelope_Payload) AsCommitArrivedPayload() (CommitArrivedPayload, error) {
	var body CommitArrivedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCommitArrivedPayload overwrites any union data inside the EventEnvelope_Payload as the provided CommitArrivedPayload
func (t *EventEnvelope_Payload) FromCommitArrivedPayload(v CommitArrivedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCommitArrivedPayload performs a merge with any union data inside the EventEnvelope_Payload, using the provided CommitArrivedPayload
func (t *EventEnvelope_Payload) MergeCommitArrivedPayload(v CommitArrivedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMergeSucceededPayload returns the union data inside the EventEnvelope_Payload as a MergeSucceededPayload
func (t EventEnvelope_Payload) AsMergeSucceededPayload() (MergeSucceededPayload, error) {
	var body MergeSucceededPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMergeSucceededPayload overwrites any union data inside the EventEnvelope_Payload as the provided MergeSucceededPayload
func (t *EventEnvelope_Payload) FromMergeSucceededPayload(v MergeSucceededPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMergeSucceededPayload performs a merge with any union data inside the EventEnvelope_Payload, using the provided MergeSucceededPayload
func (t *EventEnvelope_Payload) MergeMergeSucceededPayload(v MergeSucceededPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConflictDetectedPayload returns the union data inside the EventEnvelope_Payload as a ConflictDetectedPayload
func (t EventEnvelope_Payload) AsConflictDetectedPayload() (ConflictDetectedPayload, error) {
	var body ConflictDetectedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConflictDetectedPayload overwrites any union data inside the EventEnvelope_Payload as the provided ConflictDetectedPayload
func (t *EventEnvelope_Payload) FromConflictDetectedPayload(v ConflictDetectedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConflictDetectedPayload performs a merge with any union data inside the EventEnvelope_Payload, using the provided ConflictDetectedPayload
func (t *EventEnvelope_Payload) MergeConflictDetectedPayload(v ConflictDetectedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConflictResolvedPayload returns the union data inside the EventEnvelope_Payload as a ConflictResolvedPayload
func (t EventEnvelope_Payload) AsConflictResolvedPayload() (ConflictResolvedPayload, error) {
	var body ConflictResolvedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConflictResolvedPayload overwrites any union data inside the EventEnvelope_Payload as the provided ConflictResolvedPayload
func (t *EventEnvelope_Payload) FromConflictResolvedPayload(v ConflictResolvedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConflictResolvedPayload performs a merge with any union data inside the EventEnvelope_Payload, using the provided ConflictResolvedPayload
func (t *EventEnvelope_Payload) MergeConflictResolvedPayload(v ConflictResolvedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCommentAddedPayload returns the union data inside the EventEnvelope_Payload as a CommentAddedPayload
func (t EventEnvelope_Payload) AsCommentAddedPayload() (CommentAddedPayload, error) {
	var body CommentAddedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCommentAddedPayload overwrites any union data inside the EventEnvelope_Payload as the provided CommentAddedPayload
func (t *EventEnvelope_Payload) FromCommentAddedPayload(v CommentAddedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCommentAddedPayload performs a merge with any union data inside the EventEnvelope_Payload, using the provided CommentAddedPayload
func (t *EventEnvelope_Payload) MergeCommentAddedPayload(v CommentAddedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCommentResolvedPayload returns the union data inside the EventEnvelope_Payload as a CommentResolvedPayload
func (t EventEnvelope_Payload) AsCommentResolvedPayload() (CommentResolvedPayload, error) {
	var body CommentResolvedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCommentResolvedPayload overwrites any union data inside the EventEnvelope_Payload as the provided CommentResolvedPayload
func (t *EventEnvelope_Payload) FromCommentResolvedPayload(v CommentResolvedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCommentResolvedPayload performs a merge with any union data inside the EventEnvelope_Payload, using the provided CommentResolvedPayload
func (t *EventEnvelope_Payload) MergeCommentResolvedPayload(v CommentResolvedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRefForkedPayload returns the union data inside the EventEnvelope_Payload as a RefForkedPayload
func (t EventEnvelope_Payload) AsRefForkedPayload() (RefForkedPayload, error) {
	var body RefForkedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRefForkedPayload overwrites any union data inside the EventEnvelope_Payload as the provided RefForkedPayload
func (t *EventEnvelope_Payload) FromRefForkedPayload(v RefForkedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRefForkedPayload performs a merge with any union data inside the EventEnvelope_Payload, using the provided RefForkedPayload
func (t *EventEnvelope_Payload) MergeRefForkedPayload(v RefForkedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsModeChangedPayload returns the union data inside the EventEnvelope_Payload as a ModeChangedPayload
func (t EventEnvelope_Payload) AsModeChangedPayload() (ModeChangedPayload, error) {
	var body ModeChangedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromModeChangedPayload overwrites any union data inside the EventEnvelope_Payload as the provided ModeChangedPayload
func (t *EventEnvelope_Payload) FromModeChangedPayload(v ModeChangedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeModeChangedPayload performs a merge with any union data inside the EventEnvelope_Payload, using the provided ModeChangedPayload
func (t *EventEnvelope_Payload) MergeModeChangedPayload(v ModeChangedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTurnEndedPayload returns the union data inside the EventEnvelope_Payload as a TurnEndedPayload
func (t EventEnvelope_Payload) AsTurnEndedPayload() (TurnEndedPayload, error) {
	var body TurnEndedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTurnEndedPayload overwrites any union data inside the EventEnvelope_Payload as the provided TurnEndedPayload
func (t *EventEnvelope_Payload) FromTurnEndedPayload(v TurnEndedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTurnEndedPayload performs a merge with any union data inside the EventEnvelope_Payload, using the provided TurnEndedPayload
func (t *EventEnvelope_Payload) MergeTurnEndedPayload(v TurnEndedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPresenceUpdatedPayload returns the union data inside the EventEnvelope_Payload as a PresenceUpdatedPayload
func (t EventEnvelope_Payload) AsPresenceUpdatedPayload() (PresenceUpdatedPayload, error) {
	var body PresenceUpdatedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPresenceUpdatedPayload overwrites any union data inside the EventEnvelope_Payload as the provided PresenceUpdatedPayload
func (t *EventEnvelope_Payload) FromPresenceUpdatedPayload(v PresenceUpdatedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePresenceUpdatedPayload performs a merge with any union data inside the EventEnvelope_Payload, using the provided PresenceUpdatedPayload
func (t *EventEnvelope_Payload) MergePresenceUpdatedPayload(v PresenceUpdatedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSessionFinalizingPayload returns the union data inside the EventEnvelope_Payload as a SessionFinalizingPayload
func (t EventEnvelope_Payload) AsSessionFinalizingPayload() (SessionFinalizingPayload, error) {
	var body SessionFinalizingPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSessionFinalizingPayload overwrites any union data inside the EventEnvelope_Payload as the provided SessionFinalizingPayload
func (t *EventEnvelope_Payload) FromSessionFinalizingPayload(v SessionFinalizingPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSessionFinalizingPayload performs a merge with any union data inside the EventEnvelope_Payload, using the provided SessionFinalizingPayload
func (t *EventEnvelope_Payload) MergeSessionFinalizingPayload(v SessionFinalizingPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSessionEndedPayload returns the union data inside the EventEnvelope_Payload as a SessionEndedPayload
func (t EventEnvelope_Payload) AsSessionEndedPayload() (SessionEndedPayload, error) {
	var body SessionEndedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSessionEndedPayload overwrites any union data inside the EventEnvelope_Payload as the provided SessionEndedPayload
func (t *EventEnvelope_Payload) FromSessionEndedPayload(v SessionEndedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSessionEndedPayload performs a merge with any union data inside the EventEnvelope_Payload, using the provided SessionEndedPayload
func (t *EventEnvelope_Payload) MergeSessionEndedPayload(v SessionEndedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EventEnvelope_Payload) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EventEnvelope_Payload) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Exchange a magic-link token for a portal token pair
	// (POST /api/auth/magic-link/exchange)
	ExchangeMagicLink(w http.ResponseWriter, r *http.Request)
	// Request a magic-link sign-in email
	// (POST /api/auth/magic-link/request)
	RequestMagicLink(w http.ResponseWriter, r *http.Request)
	// Exchange OAuth authorization code for a portal token pair
	// (POST /api/auth/oauth/callback)
	OauthCallback(w http.ResponseWriter, r *http.Request)
	// Begin OAuth authorization flow — returns the provider authorize URL
	// (POST /api/auth/oauth/start)
	StartOAuth(w http.ResponseWriter, r *http.Request)
	// Exchange a refresh token for a new access+refresh pair
	// (POST /api/auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// Revoke a token (or all tokens for the account)
	// (POST /api/auth/revoke)
	RevokeToken(w http.ResponseWriter, r *http.Request)
	// Return the authenticated account's profile and org memberships
	// (GET /api/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Create a new org; the authenticated account becomes its creator
	// (POST /api/orgs)
	CreateOrg(w http.ResponseWriter, r *http.Request)
	// Create an org invite (requires creator role); sends email to recipient
	// (POST /api/orgs/{orgID}/invites)
	CreateOrgInvite(w http.ResponseWriter, r *http.Request, orgID string)
	// Accept a pending org invite (requires Bearer; verifies token + recipient email)
	// (POST /api/orgs/{orgID}/invites/{inviteID}/accept)
	AcceptOrgInvite(w http.ResponseWriter, r *http.Request, orgID string, inviteID string)
	// List members of an org (requires creator or member role)
	// (GET /api/orgs/{orgID}/members)
	ListOrgMembers(w http.ResponseWriter, r *http.Request, orgID string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Exchange a magic-link token for a portal token pair
// (POST /api/auth/magic-link/exchange)
func (_ Unimplemented) ExchangeMagicLink(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request a magic-link sign-in email
// (POST /api/auth/magic-link/request)
func (_ Unimplemented) RequestMagicLink(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Exchange OAuth authorization code for a portal token pair
// (POST /api/auth/oauth/callback)
func (_ Unimplemented) OauthCallback(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Begin OAuth authorization flow — returns the provider authorize URL
// (POST /api/auth/oauth/start)
func (_ Unimplemented) StartOAuth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Exchange a refresh token for a new access+refresh pair
// (POST /api/auth/refresh)
func (_ Unimplemented) RefreshToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke a token (or all tokens for the account)
// (POST /api/auth/revoke)
func (_ Unimplemented) RevokeToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Return the authenticated account's profile and org memberships
// (GET /api/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new org; the authenticated account becomes its creator
// (POST /api/orgs)
func (_ Unimplemented) CreateOrg(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an org invite (requires creator role); sends email to recipient
// (POST /api/orgs/{orgID}/invites)
func (_ Unimplemented) CreateOrgInvite(w http.ResponseWriter, r *http.Request, orgID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Accept a pending org invite (requires Bearer; verifies token + recipient email)
// (POST /api/orgs/{orgID}/invites/{inviteID}/accept)
func (_ Unimplemented) AcceptOrgInvite(w http.ResponseWriter, r *http.Request, orgID string, inviteID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List members of an org (requires creator or member role)
// (GET /api/orgs/{orgID}/members)
func (_ Unimplemented) ListOrgMembers(w http.ResponseWriter, r *http.Request, orgID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ExchangeMagicLink operation middleware
func (siw *ServerInterfaceWrapper) ExchangeMagicLink(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExchangeMagicLink(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestMagicLink operation middleware
func (siw *ServerInterfaceWrapper) RequestMagicLink(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestMagicLink(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OauthCallback operation middleware
func (siw *ServerInterfaceWrapper) OauthCallback(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OauthCallback(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartOAuth operation middleware
func (siw *ServerInterfaceWrapper) StartOAuth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartOAuth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeToken operation middleware
func (siw *ServerInterfaceWrapper) RevokeToken(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrg operation middleware
func (siw *ServerInterfaceWrapper) CreateOrg(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrg(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrgInvite operation middleware
func (siw *ServerInterfaceWrapper) CreateOrgInvite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "orgID" -------------
	var orgID string

	err = runtime.BindStyledParameterWithOptions("simple", "orgID", chi.URLParam(r, "orgID"), &orgID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orgID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrgInvite(w, r, orgID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptOrgInvite operation middleware
func (siw *ServerInterfaceWrapper) AcceptOrgInvite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "orgID" -------------
	var orgID string

	err = runtime.BindStyledParameterWithOptions("simple", "orgID", chi.URLParam(r, "orgID"), &orgID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orgID", Err: err})
		return
	}

	// ------------- Path parameter "inviteID" -------------
	var inviteID string

	err = runtime.BindStyledParameterWithOptions("simple", "inviteID", chi.URLParam(r, "inviteID"), &inviteID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "inviteID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptOrgInvite(w, r, orgID, inviteID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrgMembers operation middleware
func (siw *ServerInterfaceWrapper) ListOrgMembers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "orgID" -------------
	var orgID string

	err = runtime.BindStyledParameterWithOptions("simple", "orgID", chi.URLParam(r, "orgID"), &orgID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orgID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrgMembers(w, r, orgID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/magic-link/exchange", wrapper.ExchangeMagicLink)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/magic-link/request", wrapper.RequestMagicLink)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/oauth/callback", wrapper.OauthCallback)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/oauth/start", wrapper.StartOAuth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/refresh", wrapper.RefreshToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/revoke", wrapper.RevokeToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/orgs", wrapper.CreateOrg)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/orgs/{orgID}/invites", wrapper.CreateOrgInvite)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/orgs/{orgID}/invites/{inviteID}/accept", wrapper.AcceptOrgInvite)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/orgs/{orgID}/members", wrapper.ListOrgMembers)
	})

	return r
}

type ForbiddenJSONResponse ErrorEnvelope

type NotFoundJSONResponse ErrorEnvelope

type UnauthorizedJSONResponse ErrorEnvelope

type ExchangeMagicLinkRequestObject struct {
	Body *ExchangeMagicLinkJSONRequestBody
}

type ExchangeMagicLinkResponseObject interface {
	VisitExchangeMagicLinkResponse(w http.ResponseWriter) error
}

type ExchangeMagicLink200JSONResponse TokenPair

func (response ExchangeMagicLink200JSONResponse) VisitExchangeMagicLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ExchangeMagicLink401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ExchangeMagicLink401JSONResponse) VisitExchangeMagicLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RequestMagicLinkRequestObject struct {
	Body *RequestMagicLinkJSONRequestBody
}

type RequestMagicLinkResponseObject interface {
	VisitRequestMagicLinkResponse(w http.ResponseWriter) error
}

type RequestMagicLink204Response struct {
}

func (response RequestMagicLink204Response) VisitRequestMagicLinkResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RequestMagicLink500JSONResponse ErrorEnvelope

func (response RequestMagicLink500JSONResponse) VisitRequestMagicLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type OauthCallbackRequestObject struct {
	Body *OauthCallbackJSONRequestBody
}

type OauthCallbackResponseObject interface {
	VisitOauthCallbackResponse(w http.ResponseWriter) error
}

type OauthCallback200JSONResponse TokenPair

func (response OauthCallback200JSONResponse) VisitOauthCallbackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type OauthCallback400JSONResponse ErrorEnvelope

func (response OauthCallback400JSONResponse) VisitOauthCallbackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type OauthCallback401JSONResponse struct{ UnauthorizedJSONResponse }

func (response OauthCallback401JSONResponse) VisitOauthCallbackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StartOAuthRequestObject struct {
	Body *StartOAuthJSONRequestBody
}

type StartOAuthResponseObject interface {
	VisitStartOAuthResponse(w http.ResponseWriter) error
}

type StartOAuth200JSONResponse OAuthStartResponse

func (response StartOAuth200JSONResponse) VisitStartOAuthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StartOAuth400JSONResponse ErrorEnvelope

func (response StartOAuth400JSONResponse) VisitStartOAuthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type StartOAuth503JSONResponse ErrorEnvelope

func (response StartOAuth503JSONResponse) VisitStartOAuthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse TokenPair

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeTokenRequestObject struct {
	Body *RevokeTokenJSONRequestBody
}

type RevokeTokenResponseObject interface {
	VisitRevokeTokenResponse(w http.ResponseWriter) error
}

type RevokeToken204Response struct {
}

func (response RevokeToken204Response) VisitRevokeTokenResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeToken401JSONResponse) VisitRevokeTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse MeResponse

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrgRequestObject struct {
	Body *CreateOrgJSONRequestBody
}

type CreateOrgResponseObject interface {
	VisitCreateOrgResponse(w http.ResponseWriter) error
}

type CreateOrg201JSONResponse OrgRef

func (response CreateOrg201JSONResponse) VisitCreateOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrg401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateOrg401JSONResponse) VisitCreateOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrgInviteRequestObject struct {
	OrgID string `json:"orgID"`
	Body  *CreateOrgInviteJSONRequestBody
}

type CreateOrgInviteResponseObject interface {
	VisitCreateOrgInviteResponse(w http.ResponseWriter) error
}

type CreateOrgInvite201JSONResponse InviteRef

func (response CreateOrgInvite201JSONResponse) VisitCreateOrgInviteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrgInvite401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateOrgInvite401JSONResponse) VisitCreateOrgInviteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrgInvite403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateOrgInvite403JSONResponse) VisitCreateOrgInviteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptOrgInviteRequestObject struct {
	OrgID    string `json:"orgID"`
	InviteID string `json:"inviteID"`
	Body     *AcceptOrgInviteJSONRequestBody
}

type AcceptOrgInviteResponseObject interface {
	VisitAcceptOrgInviteResponse(w http.ResponseWriter) error
}

type AcceptOrgInvite200JSONResponse OrgRef

func (response AcceptOrgInvite200JSONResponse) VisitAcceptOrgInviteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptOrgInvite401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AcceptOrgInvite401JSONResponse) VisitAcceptOrgInviteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptOrgInvite403JSONResponse struct{ ForbiddenJSONResponse }

func (response AcceptOrgInvite403JSONResponse) VisitAcceptOrgInviteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptOrgInvite409JSONResponse ErrorEnvelope

func (response AcceptOrgInvite409JSONResponse) VisitAcceptOrgInviteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrgMembersRequestObject struct {
	OrgID string `json:"orgID"`
}

type ListOrgMembersResponseObject interface {
	VisitListOrgMembersResponse(w http.ResponseWriter) error
}

type ListOrgMembers200JSONResponse []MemberRef

func (response ListOrgMembers200JSONResponse) VisitListOrgMembersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrgMembers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListOrgMembers401JSONResponse) VisitListOrgMembersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrgMembers403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListOrgMembers403JSONResponse) VisitListOrgMembersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Exchange a magic-link token for a portal token pair
	// (POST /api/auth/magic-link/exchange)
	ExchangeMagicLink(ctx context.Context, request ExchangeMagicLinkRequestObject) (ExchangeMagicLinkResponseObject, error)
	// Request a magic-link sign-in email
	// (POST /api/auth/magic-link/request)
	RequestMagicLink(ctx context.Context, request RequestMagicLinkRequestObject) (RequestMagicLinkResponseObject, error)
	// Exchange OAuth authorization code for a portal token pair
	// (POST /api/auth/oauth/callback)
	OauthCallback(ctx context.Context, request OauthCallbackRequestObject) (OauthCallbackResponseObject, error)
	// Begin OAuth authorization flow — returns the provider authorize URL
	// (POST /api/auth/oauth/start)
	StartOAuth(ctx context.Context, request StartOAuthRequestObject) (StartOAuthResponseObject, error)
	// Exchange a refresh token for a new access+refresh pair
	// (POST /api/auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// Revoke a token (or all tokens for the account)
	// (POST /api/auth/revoke)
	RevokeToken(ctx context.Context, request RevokeTokenRequestObject) (RevokeTokenResponseObject, error)
	// Return the authenticated account's profile and org memberships
	// (GET /api/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Create a new org; the authenticated account becomes its creator
	// (POST /api/orgs)
	CreateOrg(ctx context.Context, request CreateOrgRequestObject) (CreateOrgResponseObject, error)
	// Create an org invite (requires creator role); sends email to recipient
	// (POST /api/orgs/{orgID}/invites)
	CreateOrgInvite(ctx context.Context, request CreateOrgInviteRequestObject) (CreateOrgInviteResponseObject, error)
	// Accept a pending org invite (requires Bearer; verifies token + recipient email)
	// (POST /api/orgs/{orgID}/invites/{inviteID}/accept)
	AcceptOrgInvite(ctx context.Context, request AcceptOrgInviteRequestObject) (AcceptOrgInviteResponseObject, error)
	// List members of an org (requires creator or member role)
	// (GET /api/orgs/{orgID}/members)
	ListOrgMembers(ctx context.Context, request ListOrgMembersRequestObject) (ListOrgMembersResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ExchangeMagicLink operation middleware
func (sh *strictHandler) ExchangeMagicLink(w http.ResponseWriter, r *http.Request) {
	var request ExchangeMagicLinkRequestObject

	var body ExchangeMagicLinkJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExchangeMagicLink(ctx, request.(ExchangeMagicLinkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExchangeMagicLink")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExchangeMagicLinkResponseObject); ok {
		if err := validResponse.VisitExchangeMagicLinkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RequestMagicLink operation middleware
func (sh *strictHandler) RequestMagicLink(w http.ResponseWriter, r *http.Request) {
	var request RequestMagicLinkRequestObject

	var body RequestMagicLinkJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RequestMagicLink(ctx, request.(RequestMagicLinkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestMagicLink")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RequestMagicLinkResponseObject); ok {
		if err := validResponse.VisitRequestMagicLinkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// OauthCallback operation middleware
func (sh *strictHandler) OauthCallback(w http.ResponseWriter, r *http.Request) {
	var request OauthCallbackRequestObject

	var body OauthCallbackJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.OauthCallback(ctx, request.(OauthCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OauthCallback")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(OauthCallbackResponseObject); ok {
		if err := validResponse.VisitOauthCallbackResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartOAuth operation middleware
func (sh *strictHandler) StartOAuth(w http.ResponseWriter, r *http.Request) {
	var request StartOAuthRequestObject

	var body StartOAuthJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartOAuth(ctx, request.(StartOAuthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartOAuth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartOAuthResponseObject); ok {
		if err := validResponse.VisitStartOAuthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(w http.ResponseWriter, r *http.Request) {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeToken operation middleware
func (sh *strictHandler) RevokeToken(w http.ResponseWriter, r *http.Request) {
	var request RevokeTokenRequestObject

	var body RevokeTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeToken(ctx, request.(RevokeTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeTokenResponseObject); ok {
		if err := validResponse.VisitRevokeTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrg operation middleware
func (sh *strictHandler) CreateOrg(w http.ResponseWriter, r *http.Request) {
	var request CreateOrgRequestObject

	var body CreateOrgJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrg(ctx, request.(CreateOrgRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrg")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrgResponseObject); ok {
		if err := validResponse.VisitCreateOrgResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrgInvite operation middleware
func (sh *strictHandler) CreateOrgInvite(w http.ResponseWriter, r *http.Request, orgID string) {
	var request CreateOrgInviteRequestObject

	request.OrgID = orgID

	var body CreateOrgInviteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrgInvite(ctx, request.(CreateOrgInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrgInvite")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrgInviteResponseObject); ok {
		if err := validResponse.VisitCreateOrgInviteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AcceptOrgInvite operation middleware
func (sh *strictHandler) AcceptOrgInvite(w http.ResponseWriter, r *http.Request, orgID string, inviteID string) {
	var request AcceptOrgInviteRequestObject

	request.OrgID = orgID
	request.InviteID = inviteID

	var body AcceptOrgInviteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AcceptOrgInvite(ctx, request.(AcceptOrgInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AcceptOrgInvite")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AcceptOrgInviteResponseObject); ok {
		if err := validResponse.VisitAcceptOrgInviteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOrgMembers operation middleware
func (sh *strictHandler) ListOrgMembers(w http.ResponseWriter, r *http.Request, orgID string) {
	var request ListOrgMembersRequestObject

	request.OrgID = orgID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOrgMembers(ctx, request.(ListOrgMembersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOrgMembers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOrgMembersResponseObject); ok {
		if err := validResponse.VisitListOrgMembersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fz9btw4kn8VQjfA2Bh1257k5nbtf9aTjx0Dydiwnbs/xoHDlqq7OVaTCknZ0xsYuIe4J7wnWVSR+qZa",
	"bcfxzuaPwC3xo1j1Y7G+qC9Rola5kiCtiQ6/RBpMrqQB+vFW6ZlIU5D4I1HSgrT4J8/zTCTcCiX3fjeK",
	"XptkCSuOf32nYR4dRv+xV4+8596avTdaK/1G3kKmcoju7+/jKAWTaJHjYNFhxAu7BGlxdEjZrLBMKsty",
	"0Cth8clcaWaXwDR8LsDgE5WDJlKi+zj6Vdm3qpDp8xFcE6JVYYEpzTQYVegEiPQ5kXMfRx8krk1p8Q94",
	"RvJWwhghF0iWkLc8EymbAdegmVU3ICPs4QfDuY6TBHJ7Im+FhZ9VusZnuUYWW+Ew4bodfunMc87vcAJh",
	"wQ3M5lqtSFKw4iJjmZA37HMBes1yrvkKLOgojuw6h+gwMlYLuSBikJ9CI4t+83N9rJqp2e+QWGTmK7Va",
	"gbTHaQrpGV9niqd9mo5Z4pqxO25YrkhKQhJVBowRSk6Z782EoefzIsuqbjlodnZ+enn66vTddJVWzx3D",
	"pu13XCopEp6xuYAsNYdMpHE5zTX+7cTf/PNGSPwhk6XSMZupdB0znqYajIH02qqYuRaJBtwO19zGBK7s",
	"tvtjtvY/Clz7tVQWplcyijvCaw4e4Jd7i3BxMtyB6WLKrqK/FQb0VRSXf+7NNBLtn/Asm/AFwvIq2o3i",
	"SBZZxmcZRIdWF9CTcRy5BY9BuxSxa4zdSv4FKE8SVUjLTl4zNSc5lqJynaIQFbUM+gP+zxLsEpyqcQ0R",
	"IJwtixWXuJm4ZLTmKI5AFitEK72L4sg9/xiYcuZ3VHsuv1CSP8JzxfVNqu5kiOgaCf1xTi5OJ3/5af+A",
	"WbECY/kqR2ZQD2wQR3OlV9gxSrmFCbYKTRHib0niyWu28+HDyevdUMcwJ8uu9LZm1nwtojgi1emIM8Vi",
	"Uf3gCf4x8bo1yMsO2vsTn9IfPGvsC0Ytt0BoY5Ntxee7JchqMx4xHJ+JOR5Ng3zfnobZegzwvqnuzTw6",
	"Sa2f+nNcuHet7TSDTMmFYVaNKm+B4m6M39zA7d1XaQS/QzyUWmjfdAhU6qSt7JBmYa/NkvfXdunXJHBJ",
	"qPD8AtGeCG68ucjgOud22R/rrciA3Qm7FDWvhP3eMKsBvEjQbHHPJxncQnXEmG2ElAkJ15rLBaGcZ9np",
	"PDr8bUx7ynkmEovEnVPX+49d2+BgImQKf0CKpzMwmqFBLy7ZU7s19V0QNGSwQYLnHupbnuSoINHe8r3G",
	"zmHflQ7e1oE5dErWHYaB47WhXXJHUzlwCDvfUD+N6wZEJJ7Z7G6pKiqbe3p0IzfY0Z55SKLCHmstxuUp",
	"vGFWmCWSpBgv7SWmYT4mVg3zmJklbxlWplituF4HbZ+Hmg9ik/VAWy8EjsYKmiNlXKakXLxR9Ttf7V0V",
	"+/svEt+BfoB/RvZW84E3uOhR8PAd03IXvxw7sHInmuAYjnkBqEqYkIrwLTpcWoExfAGjQEKeOUrbZ0E5",
	"bxhPTo+9BguJ3QSpwqrJCvQCNEt9Y8aZXWqAyR1fM3rHEj/ekOHv3jK4Ddv/rdePcwOcb3hda8bqESE6",
	"1Xxur63I3SsuEzBWaferJMB0/QRjuS1Mqd+EXLTGb/kM9aH69R6CoYNCrHJO7M65tiIROZfWtJ2HymNA",
	"8AoLK+dLdhHoH3Ct+dp7CtXqh+GtZMWmBtyD5nPJv/5gZ6AneOLVQk7BcpGZJsHbnrihtTzQdCeT0m0y",
	"Tw/qyhLZW1vzLTiFWUhNmBU545ZmxLHKLT7nIoPUbx5uLaxyu73X0NouG52HR1ncPfY0TuGvMbrb+ydk",
	"GVtHAGfedDGTarFWI8s0W3GbLAGVizCOA09rkPvpNlnkcdRTNhsPCTogElVkKYWuZuDknm4YefAcLM8/",
	"HwrzMyR8BRQaCg5JSiyAo0Jr0rf03iFTmIoFDa/Suz0NGPAZl6mSkAacyFGHpc+91rq7u6ujr5rqJm4r",
	"1mqtW/g4Da3Sc3Hm/mnAIUFfpemVaMiVEVbpdXD7oe0fYP27yjEwTMjGZisHFob8hMcoSe+WdDVlRyp+",
	"dE/gGIvOSy+pzScIRSbeSO/47FSO0G5t2fiFOrermlVICwvQHq06oKsu8PHjx+2s3k0S0wI2rX0rD8pP",
	"veSGzaARsGC3gjNemeTCLhl36gsP+kENN2b4kM5reF1trRoyPsoeQ0qqe5xs5X1tp9JDpnLHW6q0zWY1",
	"Ui1iYOqgGEkJnOpFOOYu+SqwzV+DwTmZ0guGLY7QzyM/KgW08Z36zYoF4ucPvsoz2mXJatxSpwlDhLbz",
	"DT1CS5PJGZLCObhnjSbu1BtwhI3VRWILXBMlR/6wVboHcN4pu1jyHJgwVzJRKUxMDomYi+SIKZ8eKs0C",
	"ja3wEFs6WxXNZYe43pJo6D53VxzhDxMNPMUT25HAcN7KtEUnZurTKtdkEDsDt8HtXosQREsHqkcEhZS7",
	"JNTuVj1PmdsZmKILUVpyPW9Q0gjjpqRTgZSthOTW8WvF8xxHryMmU56mOMPmgH4zZxNXXastvLl3V9HF",
	"PsQ0Lf3aDd17cYn6hJ5WhvXIwdX1QxtDjK8grKtRDnoBU1MkCcAGBr7HZhdlq0Z3lcI0WeKJMtxXpfDK",
	"Nak75hoMyASmRY5W8mDnM9/ug2tWD6BhPp0rfTPc9Rzmb6lB3alMvYHcsFZv676RaajrXEieiX8Q+jb2",
	"f1s1rAexhR6Z/LLQ7Znvq5Nq/SvpYrdf7rsHWF4fv0rCVmHaACzv482dwjgY6zWE4G37dWE73q+/3bfs",
	"89CpeiAb5WB/N4x1CWBic4eBTTPWbRC4W3Zs0/iRXMrP/ZPlvZLKosHGctCTMmhp4HOBNDNZrGaUoK/c",
	"aCHtTy/DhvBWLmvpBI84rJWHv21+0w0KVOfwgCyne9BzCWgwfOeNKW5Y69wjgySvVEnpd3bOoL5GD500",
	"oaMj7hylgfOxpXU7yr+l3AL6PahBuxo5lG29BU3sDThRzkJgvsUR49kdXxt2ULPn4OO4nwOfo3oW3zyO",
	"ak7XuGgBLmS5bKpeoWKUwCqoRsW76GguulKWroklLMDf/JNpQkGMCm1u5FHLi1oNU33uwikdov/IhQbz",
	"4NCYr8fx3b+qAMBRx05et1iyf/DXH3+Clz9O9vf39yf/hf9x/G+//vdj2CVLRC7QTdpOHvVa0NkztEfV",
	"0wvH+2xt2uIm+0OCe88XInkn5M2bP9w2fHDd1ApHmFCFVKd26sP5uycsmqooPXd1FSNbpOZuYUB/K9y/",
	"R7f3PeBxY5Yi79MTguOpXrAPHx6OxoNgejboXeMUqTB5xtfkXW/hRMeRVqF43KUvIqrrGrlLOH5vGPZg",
	"ZSRN6bavTrHBcP6R/PreTB/O300MnwPFBB7n+tMm8Av2I9CqwrI79+WigVCA4911mLu/tB3bQUYfp5y9",
	"U7eQ8STI8AH98d+gxVxA6osPvSJpjfwITIdVY5k8fgwe90OTKL0IRGKPs4ykuqq2ivHREWFKPG0bhe3u",
	"ubEYLGGiZEpLsJ7aMDhw/OCB5sm9fhZ2bgaio/J78+QQrAZ+Ygj+roR8RJrMwYa53vTEKZvtTIKwXquW",
	"WCsx6OkwN/Go2mlAYhBqREWTA2HYhZzjjeUCZKYbMy+yzJcJpIx3EldCWkXrq7KlY+FvnyiiBLzLE9Gf",
	"NP5IHLxqPpawvfjlmPG59YWqNHQ4vtieMzxsWSBRBcF9aorN1mUdbMmyDQnBweHb/KyC7FTQNZBl7DoJ",
	"9Qxxg0eB9QWB0ff5A1kSDfPvDUtUlvGZcvcKGLpYRKd3s7aqTFJZeo0dYybhjv4KSbp8F2aZhDuaPHhK",
	"+PHDPXMNt0IVZrD7xrzt3VIZcMtueJZb1PZURMX1ykKyOD0u7PIVz7IZT27CZmgSXNuxv0LhBEPB+MpY",
	"zrW6FWkYnNW7vp2HQ1Z9Sf3HzMf3F8Iui9lV1FJo7uFQ/hqCGUELTCqZAINkqXBH8eRmG8I7TG40TByX",
	"3ZSDLKZkZJi/z8CRIeo3kztsUlb3Z64LHThxz0qKeQsk6EMhl2da3RnU9ksqcJgh1FOhXaHYFvXM7dmD",
	"a9CLoLnz7+TBPJ9fEeLgQMw0oKcbpWbfG1YGutgOT6y4dVrsh/KI3CXl7WNgY8objTKftJ7HLHGlJ+7o",
	"zrix126CYNlw3XYgv+zrWMqT29cEtJfiFGm/Bryee9vIKHZpDs6ou7Dr7c2+seKe5ujClAvM1gNF9J63",
	"2xTgNkYehVY5bOxPoaYg2pwLYa6XPNiMNuYir4zT6fzQeuWc13AasgmGT/WAWeLZhbSgUHbMWiZ02c+o",
	"DOEeLLarqdiiEKIenIq1qSuu3z4IMeUYqAG+SQl00B5pLNRFyoMICGVOAiAoZb3khlGknO34KDqkMasK",
	"zWJkP+6olKnC7o7DghslQzhwb4Y2IL5r3mRkZdC/umHlaauL4HwYXRV2vBjOT76BXf0M1SjPLGjvfNbp",
	"B6rqgzEuzdbXfpeHOFW/faBqoUsRQgoryNHxVJX35TZzqDFpiEuX6gbkGRc6GP4AY67bYf3tNLLvWgWT",
	"QxtQg1k+avCy79DofZe9pqXbOw6sMkhdkHfdXOuoAWAL7XfAEcp4zdYIHF9IpFXmLG7vwlNVzcPsAELG",
	"kLtevQzvVXrd1KmqrMicU8W1J/2rD2BUz3dK39B17yc8f707WLP4wQdyzaC+tCmBnBRa2PVFsoSV39F0",
	"Rx19gvrX2xLEKuefC0Rwt44MH7eutzNhTFFHMHKlLc+Yc3DmmbqbXklncloUCs8ydv7m4pIlPMtMzN6/",
	"Oiv/5DJlC2En6hb05JfLy7OLK7nDDcM/2c/ciITl3Jg7pdPdKTuV5S34HLS7feXjWw4+FIdFJjhaa34u",
	"rc3dLX4h54H7F0SdKfScJ1DVxv3OVwbM0q9uyi6EXGRVvAXlqWm9Sl9JA/oWNBOoinEQw3YUz8UE3ckF",
	"yF1aaJKJMg1uruSOykFiG/pNxOxOmXfE5YLpIqPi4CuZqsTsXZy9eYU7yh3U7O8gQZNypZ3IE2umV/JK",
	"nuYgj89OyrTxIXsx3Z++YDuZStC6+v///T/WJIytuJBUVJsqoMI+tgZ7JU2R47LZi+nBEVuJhTeNrBaL",
	"Ba2TbUnULlHVXdWOo8oUMwMWGxuruZDW7B5eyQn7YIB9Kkv6D5HP8In9enrJPiGvDtlvbn/E7IoK/6+i",
	"j5+qbt59OvQd/E9z+IntUBAe5bVCo/rF9GAXe/2q2Kc7mC2VusFWM+RU+fw7F9n/xLiUyhIP8NVxlvlL",
	"SoYVEl3jOhkw9S+o0IF9hwoFbkGv75agwVVKCkvuXRtfjTT9YbQ/3Z8eUDTKYSQ6jIhjZHrZJW3lPZ6L",
	"PXSe9+o85x74XCkdjsrQIVV9yOMkjQ6jMptaJS2juPzWRhnQeJIvaITTt/dtlUZXW+P2x1F+3N9/MiJq",
	"YyHwCY9Lp0m40F6dIcNf7h8MDVpRudf65EhT00aHv31s3PermE11391ktNKMl6rTVrTQeEHZlrf2B0Xr",
	"08/PJtlmunsrwb4M5DpwMPcVE5fQoUNjR2lmROZ8Xk7fToGUiXlVulDIG6nu5C6K7D+fEDCj3305QQ1P",
	"RdVO47vS4R1HewqZwL1Ot7sKDbsbweHZ18aGEQs5EdIxo4MFRf8nPrw7jINT3ogCfyMQ9CPN/wZb+1lx",
	"4grHlfZ1QqlzyFy8mnzZKhK8EoZuhXxD/eNMMx6I8m+lhRzyqps5YdhRlJkm+paYq0Pvzwy4QCQ9IPfj",
	"XoxcA0/J6qgi5WV8/NlB+cFpTQRfIRMl52JBt0KqDAJp0xfPR1CVWkDDs0FQWdnqlOxGiP8MCyGD+EZH",
	"hAxeDehjmVZOqGpLxWAduHt3etNJSw0uKxf9cWDvxqUeFCZoNw84gH8edfwr3LV0yzc0szxXWjaWhDvm",
	"oiY/lK8DOk7DrbqBTTLH908tchzzmmc+7TbnRWajwznPTH2JeaZUBpw+w7clNL4GEgEbDVeelGcGelMW",
	"nkSG7XDEbx/vO+YR8obx8ptpKMosa34fgYonnP+/WwvTpewWEBDh38G+h+gb7oJG4V7obPDRICHnyl0H",
	"7RSePQtXKd5kN5RO5lrRBxu4TPsEllwui+nCe6W6d/mNLIH2vc6tcH3wdIaAS0cHBHyqF2VxzzOI0jHB",
	"6zelF0fDUmUzSNQKDBPWsLL6tSXLvS9KL05e3++5iu9tZHtS1vJXNdSGaO7zhNLxAn/Rl77KxHpEU0Zd",
	"2cUNOXT13Mdvg6fG1YZnBlN9PSHsRAgLJaSOmh6yVayqqH8k1rDTi/FO9cdqH4VOSTrEXzPY8YytQEgl",
	"jrtHuKa0LOlsL20TSPe+uD/wkYsSDMPWfYH1XwTbeNO9j8AM5bL+DHuj9+na5/a7BtWtZ2IZHzqqtZ0q",
	"JN0xq4+vZ9sj2OOvzxpnIB5kzs0sefGwvepEzDjLQabuq8aBLfszjXDEbt0lAOMNsx/q3eo28O7ApvV2",
	"xKB19k4YW9fP/wvOla8A8JbXA8rK/f7FgJ5gkRtMzZsW2J9SzxOdnkCk1yv8vqanLyxQsTzpfLfmsWnI",
	"/3fip9pEyuSZw729L0tl7H0UR7dcCz7LnNiWXvVXnlSUqYRn+PjwLy9fvujlNs9c4AsbkL2bK01+0sf7",
	"fwYAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
