// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	// Details Optional structured context for the error. Shape is
	// code-specific; omitted when there is nothing to add.
	Details map[string]interface{} `json:"details,omitempty"`

	// Error machine-readable error code (e.g. "auth.invalid_token")
	Error string `json:"error"`

	// Message human-readable error message
	Message string `json:"message"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessExpiresAt  time.Time `json:"access_expires_at"`
	AccessToken      string    `json:"access_token"`
	RefreshExpiresAt time.Time `json:"refresh_expires_at"`
	RefreshToken     string    `json:"refresh_token"`
}

// Forbidden defines model for Forbidden.
type Forbidden = ErrorEnvelope

// NotFound defines model for NotFound.
type NotFound = ErrorEnvelope

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorEnvelope

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// RefreshTokenJSONBody defines parameters for RefreshToken.
type RefreshTokenJSONBody struct {
	RefreshToken string `json:"refresh_token"`
}

// RevokeTokenJSONBody defines parameters for RevokeToken.
type RevokeTokenJSONBody struct {
	RevokeAll bool   `json:"revoke_all,omitempty"`
	Token     string `json:"token"`
}

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody RefreshTokenJSONBody

// RevokeTokenJSONRequestBody defines body for RevokeToken for application/json ContentType.
type RevokeTokenJSONRequestBody RevokeTokenJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Exchange a refresh token for a new access+refresh pair
	// (POST /api/auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// Revoke a token (or all tokens for the account)
	// (POST /api/auth/revoke)
	RevokeToken(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Exchange a refresh token for a new access+refresh pair
// (POST /api/auth/refresh)
func (_ Unimplemented) RefreshToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke a token (or all tokens for the account)
// (POST /api/auth/revoke)
func (_ Unimplemented) RevokeToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeToken operation middleware
func (siw *ServerInterfaceWrapper) RevokeToken(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/refresh", wrapper.RefreshToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/revoke", wrapper.RevokeToken)
	})

	return r
}

type ForbiddenJSONResponse ErrorEnvelope

type NotFoundJSONResponse ErrorEnvelope

type UnauthorizedJSONResponse ErrorEnvelope

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse TokenPair

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeTokenRequestObject struct {
	Body *RevokeTokenJSONRequestBody
}

type RevokeTokenResponseObject interface {
	VisitRevokeTokenResponse(w http.ResponseWriter) error
}

type RevokeToken204Response struct {
}

func (response RevokeToken204Response) VisitRevokeTokenResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeToken401JSONResponse) VisitRevokeTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Exchange a refresh token for a new access+refresh pair
	// (POST /api/auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// Revoke a token (or all tokens for the account)
	// (POST /api/auth/revoke)
	RevokeToken(ctx context.Context, request RevokeTokenRequestObject) (RevokeTokenResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(w http.ResponseWriter, r *http.Request) {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeToken operation middleware
func (sh *strictHandler) RevokeToken(w http.ResponseWriter, r *http.Request) {
	var request RevokeTokenRequestObject

	var body RevokeTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeToken(ctx, request.(RevokeTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeTokenResponseObject); ok {
		if err := validResponse.VisitRevokeTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFbNctu2E3+VHfxzkOZPU3LtQ4c5ORmnzaG2pnZOpseGyJWIGASYXVC26tFMH6JP2CfpLEhJlq20SZvJ",
	"DR+L3d9+/RaPqvB14x26wCp7VITceMcYN+88TU1ZopNN4V1AF2Spm8aaQgfj3egj+3jNRYW1ltUrwpnK",
	"1P9GW82j7pZHp0SeTt0CrW9QrVarRJXIBZlGlKlM6TZU6IJoxxKmbQDnAzRItQlyMvMEoUIg/NQiy4lv",
	"kCIUtUrUmQ/vfOvK7wd4C4R8GxA8ASH7lgqM0GcRzipRH5z45sn8ht8RXm2YjZsLLOMW2poSpqgJCYK/",
	"Q6fkRa9MbO3qyx5VQxLfYLqCKDFoY+NSl6URG9pOnogEavE5hPOmkwMO1BahJSwhOv8QNulEsZvCRaUb",
	"BMO5K3yJB9xgYWameA2+T/99hU4ekEhJfCtxLnjQZZnmTiUqLAW48tOPWASJe1Tdgd8JjC4q4/CAUJd6",
	"ansIIHZhgOk8hTwWY9qH7SbGK1dDlSh80HVjsS/XXYktBA5k3Fwg1Mis5/gSRNXW2j2HsJZ+amedu8+Y",
	"WCWxDg1JaV31Lm/tXu8Jy6VommhDL7OsiwKZb/ChMYR8o2ONzjzVslKlDngQTI37PO2fdjCzx5cChDNC",
	"rv6V8vXbz2l/FoUdLM9fJ3u83IvuZeykY7BoyYTlhXROF7Suq07aUG1379Zu+UZ/asWn550hxzsNCYa5",
	"FeZbxr5oPAVt4Vz0wsz6+zR3E0JGF8A70NbCr6cXl1BoazmBX95O1kvtSpibcOAXSAc/X15OLnI30Ayy",
	"hDeaTQGNZr73VA5TOHfY22+QoGUk0EXhWxe6rooUIUHosG6zU4XQdLxj3My/rPCIjlua6QI33f5R14xc",
	"9d6lcGHc3CL0rOlnECj66yl3jLRAIa+AUQnDwOvGHEijztENo6OFNRIRwcS5G/gGncjEfQQzTOGkY183",
	"B2otMhiXu9IXPLqYnL5N6xLydjw+QvgJnQyUnqRIF4HT3OXuvEF3MnkPCyQ23mVwlI7TIxhYX9xhCX/+",
	"/gc8BQa1Ns4ah1B6jFQFSwy547YRt+EoPXwNtZl3swsCmfk8+glfCGoYUT33atCh4nbKGESYA2njAg+z",
	"3B3AB0a4da21wjeZxBlv4ez8Em4lVhlcdb2UQK5EKlfXt5tnPRtl/YN+y9ktDDSRXkq+aqHlo/RwKK/O",
	"PNze47Ty/k6kphKp9fmrbujcgnbOhxgDuTqxFvpxBK0rUQh5PfTS/uK11CfIVARcIC3vZRx03G9CZMvd",
	"+lKJ6nOmMjVOx+mhkElfIypTMWIqUY0OVWzlkW7MSJh91PNBpEjPkao23433pZR3J3C54Zj4GXjjy+VX",
	"jfhd/v1KntsV38NXO/KS8njw5J/3w3j8zX4k27my5zdyhvdrmokSiToeH35O4wbiaOfr9JR/VXZ1nShu",
	"61rTUmXq9KGotJsjaOij0psT5tHg8B462v//+rrDsUp2kr7wd/h3OZf7b51y0Xmjre0odKZbG1Q205Zx",
	"k9Cp9xZ1/Od+YWn8l5I43kPmuPCdQ7EtLQb8JjncnZ5X16udpHbxBt2nciCptLbb8Wam9ONq2Dn3T8rj",
	"UOF425Lt5xhno9Fj5TmshDI0GSHJGI2qL4RNYpT1hbZynP14fHz0YrJPurktAnFACRMJsuvVXwEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
