// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlitestore

import (
	"context"
	"database/sql"
	"time"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, email, display_name, github_user_id, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, email, display_name, github_user_id, created_at, is_anonymous
`

type CreateAccountParams struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	DisplayName  string         `json:"display_name"`
	GithubUserID sql.NullString `json:"github_user_id"`
	CreatedAt    time.Time      `json:"created_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.GithubUserID,
		arg.CreatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.GithubUserID,
		&i.CreatedAt,
		&i.IsAnonymous,
	)
	return i, err
}

const createAnonymousAccount = `-- name: CreateAnonymousAccount :one
INSERT INTO accounts (id, email, display_name, github_user_id, created_at, is_anonymous)
VALUES (?, ?, ?, NULL, ?, 1)
RETURNING id, email, display_name, github_user_id, created_at, is_anonymous
`

type CreateAnonymousAccountParams struct {
	ID          string    `json:"id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
	CreatedAt   time.Time `json:"created_at"`
}

// Creates an anonymous account for a playground session participant.
// The synthetic email satisfies the NOT NULL UNIQUE constraint without
// requiring schema relaxation; the @playground.local suffix and the
// random ID prefix guarantee uniqueness.
func (q *Queries) CreateAnonymousAccount(ctx context.Context, arg CreateAnonymousAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAnonymousAccount,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.CreatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.GithubUserID,
		&i.CreatedAt,
		&i.IsAnonymous,
	)
	return i, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, display_name, github_user_id, created_at, is_anonymous
FROM accounts
WHERE email = ?
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.GithubUserID,
		&i.CreatedAt,
		&i.IsAnonymous,
	)
	return i, err
}

const getAccountByGitHubUserID = `-- name: GetAccountByGitHubUserID :one
SELECT id, email, display_name, github_user_id, created_at, is_anonymous
FROM accounts
WHERE github_user_id = ?
`

func (q *Queries) GetAccountByGitHubUserID(ctx context.Context, githubUserID sql.NullString) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByGitHubUserID, githubUserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.GithubUserID,
		&i.CreatedAt,
		&i.IsAnonymous,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, display_name, github_user_id, created_at, is_anonymous
FROM accounts
WHERE id = ?
`

func (q *Queries) GetAccountByID(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.GithubUserID,
		&i.CreatedAt,
		&i.IsAnonymous,
	)
	return i, err
}

const updateAccountDisplayName = `-- name: UpdateAccountDisplayName :exec
UPDATE accounts
SET display_name = ?
WHERE id = ?
`

type UpdateAccountDisplayNameParams struct {
	DisplayName string `json:"display_name"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateAccountDisplayName(ctx context.Context, arg UpdateAccountDisplayNameParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountDisplayName, arg.DisplayName, arg.ID)
	return err
}
