// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package sqlitestore

import (
	"context"
	"database/sql"
	"time"
)

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, org_id, session_id, author_account_id, author_kind,
       anchor_commit_sha, anchor_file_path, anchor_line_start, anchor_line_end,
       body, addressed_to, kind, created_at, resolved_at, resolved_by_account_id, resolution_note
FROM comments
WHERE id = ?
`

func (q *Queries) GetCommentByID(ctx context.Context, id string) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SessionID,
		&i.AuthorAccountID,
		&i.AuthorKind,
		&i.AnchorCommitSha,
		&i.AnchorFilePath,
		&i.AnchorLineStart,
		&i.AnchorLineEnd,
		&i.Body,
		&i.AddressedTo,
		&i.Kind,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ResolvedByAccountID,
		&i.ResolutionNote,
	)
	return i, err
}

const insertComment = `-- name: InsertComment :exec
INSERT INTO comments (
    id, org_id, session_id, author_account_id, author_kind,
    anchor_commit_sha, anchor_file_path, anchor_line_start, anchor_line_end,
    body, addressed_to, kind, created_at, resolved_at, resolved_by_account_id, resolution_note
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCommentParams struct {
	ID                  string         `json:"id"`
	OrgID               string         `json:"org_id"`
	SessionID           string         `json:"session_id"`
	AuthorAccountID     string         `json:"author_account_id"`
	AuthorKind          string         `json:"author_kind"`
	AnchorCommitSha     string         `json:"anchor_commit_sha"`
	AnchorFilePath      sql.NullString `json:"anchor_file_path"`
	AnchorLineStart     sql.NullInt64  `json:"anchor_line_start"`
	AnchorLineEnd       sql.NullInt64  `json:"anchor_line_end"`
	Body                string         `json:"body"`
	AddressedTo         sql.NullString `json:"addressed_to"`
	Kind                string         `json:"kind"`
	CreatedAt           time.Time      `json:"created_at"`
	ResolvedAt          sql.NullTime   `json:"resolved_at"`
	ResolvedByAccountID sql.NullString `json:"resolved_by_account_id"`
	ResolutionNote      sql.NullString `json:"resolution_note"`
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) error {
	_, err := q.db.ExecContext(ctx, insertComment,
		arg.ID,
		arg.OrgID,
		arg.SessionID,
		arg.AuthorAccountID,
		arg.AuthorKind,
		arg.AnchorCommitSha,
		arg.AnchorFilePath,
		arg.AnchorLineStart,
		arg.AnchorLineEnd,
		arg.Body,
		arg.AddressedTo,
		arg.Kind,
		arg.CreatedAt,
		arg.ResolvedAt,
		arg.ResolvedByAccountID,
		arg.ResolutionNote,
	)
	return err
}

const listCommentsForSession = `-- name: ListCommentsForSession :many
SELECT id, org_id, session_id, author_account_id, author_kind,
       anchor_commit_sha, anchor_file_path, anchor_line_start, anchor_line_end,
       body, addressed_to, kind, created_at, resolved_at, resolved_by_account_id, resolution_note
FROM comments
WHERE session_id = ?
  AND (? = '' OR addressed_to LIKE '%' || ? || '%')
  AND (? = '' OR kind = ?)
  AND (? = 0 OR (? = 1 AND resolved_at IS NOT NULL) OR (? = 2 AND resolved_at IS NULL))
  AND (? = '' OR anchor_commit_sha = ?)
  AND (? = '' OR anchor_file_path = ?)
  AND created_at < ?
ORDER BY created_at DESC
LIMIT ?
`

type ListCommentsForSessionParams struct {
	SessionID       string         `json:"session_id"`
	Column2         interface{}    `json:"column_2"`
	Column3         sql.NullString `json:"column_3"`
	Column4         interface{}    `json:"column_4"`
	Kind            string         `json:"kind"`
	Column6         interface{}    `json:"column_6"`
	Column7         interface{}    `json:"column_7"`
	Column8         interface{}    `json:"column_8"`
	Column9         interface{}    `json:"column_9"`
	AnchorCommitSha string         `json:"anchor_commit_sha"`
	Column11        interface{}    `json:"column_11"`
	AnchorFilePath  sql.NullString `json:"anchor_file_path"`
	CreatedAt       time.Time      `json:"created_at"`
	Limit           int64          `json:"limit"`
}

func (q *Queries) ListCommentsForSession(ctx context.Context, arg ListCommentsForSessionParams) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsForSession,
		arg.SessionID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Kind,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.AnchorCommitSha,
		arg.Column11,
		arg.AnchorFilePath,
		arg.CreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SessionID,
			&i.AuthorAccountID,
			&i.AuthorKind,
			&i.AnchorCommitSha,
			&i.AnchorFilePath,
			&i.AnchorLineStart,
			&i.AnchorLineEnd,
			&i.Body,
			&i.AddressedTo,
			&i.Kind,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.ResolvedByAccountID,
			&i.ResolutionNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveComment = `-- name: ResolveComment :exec
UPDATE comments
SET resolved_at = ?,
    resolved_by_account_id = ?,
    resolution_note = ?
WHERE id = ? AND session_id = ? AND resolved_at IS NULL
`

type ResolveCommentParams struct {
	ResolvedAt          sql.NullTime   `json:"resolved_at"`
	ResolvedByAccountID sql.NullString `json:"resolved_by_account_id"`
	ResolutionNote      sql.NullString `json:"resolution_note"`
	ID                  string         `json:"id"`
	SessionID           string         `json:"session_id"`
}

func (q *Queries) ResolveComment(ctx context.Context, arg ResolveCommentParams) error {
	_, err := q.db.ExecContext(ctx, resolveComment,
		arg.ResolvedAt,
		arg.ResolvedByAccountID,
		arg.ResolutionNote,
		arg.ID,
		arg.SessionID,
	)
	return err
}
