// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conflict_events.sql

package sqlitestore

import (
	"context"
	"database/sql"
	"time"
)

const getConflictEventByID = `-- name: GetConflictEventByID :one
SELECT id, org_id, session_id, source_commit, draft_tip, ancestor,
       conflicts, addressed_to, status, resolving_commit_sha, created_at, resolved_at
FROM conflict_events
WHERE id = ?
`

func (q *Queries) GetConflictEventByID(ctx context.Context, id string) (ConflictEvent, error) {
	row := q.db.QueryRowContext(ctx, getConflictEventByID, id)
	var i ConflictEvent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SessionID,
		&i.SourceCommit,
		&i.DraftTip,
		&i.Ancestor,
		&i.Conflicts,
		&i.AddressedTo,
		&i.Status,
		&i.ResolvingCommitSha,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const insertConflictEvent = `-- name: InsertConflictEvent :exec
INSERT INTO conflict_events (
    id, org_id, session_id, source_commit, draft_tip, ancestor,
    conflicts, addressed_to, status, resolving_commit_sha, created_at, resolved_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertConflictEventParams struct {
	ID                 string         `json:"id"`
	OrgID              string         `json:"org_id"`
	SessionID          string         `json:"session_id"`
	SourceCommit       string         `json:"source_commit"`
	DraftTip           string         `json:"draft_tip"`
	Ancestor           string         `json:"ancestor"`
	Conflicts          string         `json:"conflicts"`
	AddressedTo        string         `json:"addressed_to"`
	Status             string         `json:"status"`
	ResolvingCommitSha sql.NullString `json:"resolving_commit_sha"`
	CreatedAt          time.Time      `json:"created_at"`
	ResolvedAt         sql.NullTime   `json:"resolved_at"`
}

func (q *Queries) InsertConflictEvent(ctx context.Context, arg InsertConflictEventParams) error {
	_, err := q.db.ExecContext(ctx, insertConflictEvent,
		arg.ID,
		arg.OrgID,
		arg.SessionID,
		arg.SourceCommit,
		arg.DraftTip,
		arg.Ancestor,
		arg.Conflicts,
		arg.AddressedTo,
		arg.Status,
		arg.ResolvingCommitSha,
		arg.CreatedAt,
		arg.ResolvedAt,
	)
	return err
}

const listOpenConflictEventsForSession = `-- name: ListOpenConflictEventsForSession :many
SELECT id, org_id, session_id, source_commit, draft_tip, ancestor,
       conflicts, addressed_to, status, resolving_commit_sha, created_at, resolved_at
FROM conflict_events
WHERE session_id = ? AND status = 'open'
ORDER BY created_at ASC
`

func (q *Queries) ListOpenConflictEventsForSession(ctx context.Context, sessionID string) ([]ConflictEvent, error) {
	rows, err := q.db.QueryContext(ctx, listOpenConflictEventsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConflictEvent
	for rows.Next() {
		var i ConflictEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SessionID,
			&i.SourceCommit,
			&i.DraftTip,
			&i.Ancestor,
			&i.Conflicts,
			&i.AddressedTo,
			&i.Status,
			&i.ResolvingCommitSha,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConflictEventResolved = `-- name: MarkConflictEventResolved :exec
UPDATE conflict_events
SET status = 'resolved',
    resolving_commit_sha = ?,
    resolved_at = ?
WHERE id = ? AND session_id = ? AND status = 'open'
`

type MarkConflictEventResolvedParams struct {
	ResolvingCommitSha sql.NullString `json:"resolving_commit_sha"`
	ResolvedAt         sql.NullTime   `json:"resolved_at"`
	ID                 string         `json:"id"`
	SessionID          string         `json:"session_id"`
}

func (q *Queries) MarkConflictEventResolved(ctx context.Context, arg MarkConflictEventResolvedParams) error {
	_, err := q.db.ExecContext(ctx, markConflictEventResolved,
		arg.ResolvingCommitSha,
		arg.ResolvedAt,
		arg.ID,
		arg.SessionID,
	)
	return err
}
