// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leases.sql

package sqlitestore

import (
	"context"
)

const insertLease = `-- name: InsertLease :one
INSERT INTO leases (session_id, pod_id, fencing_token, acquired_at, released_at, heartbeat_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP)
ON CONFLICT (session_id) DO UPDATE
    SET pod_id        = EXCLUDED.pod_id,
        fencing_token = EXCLUDED.fencing_token,
        acquired_at   = CURRENT_TIMESTAMP,
        released_at   = NULL,
        heartbeat_at  = CURRENT_TIMESTAMP
RETURNING session_id, pod_id, fencing_token, acquired_at, released_at, heartbeat_at
`

type InsertLeaseParams struct {
	SessionID    string `json:"session_id"`
	PodID        string `json:"pod_id"`
	FencingToken int64  `json:"fencing_token"`
}

func (q *Queries) InsertLease(ctx context.Context, arg InsertLeaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, insertLease, arg.SessionID, arg.PodID, arg.FencingToken)
	var i Lease
	err := row.Scan(
		&i.SessionID,
		&i.PodID,
		&i.FencingToken,
		&i.AcquiredAt,
		&i.ReleasedAt,
		&i.HeartbeatAt,
	)
	return i, err
}

const markLeaseReleased = `-- name: MarkLeaseReleased :exec
UPDATE leases
SET released_at = CURRENT_TIMESTAMP
WHERE session_id = ?
`

func (q *Queries) MarkLeaseReleased(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, markLeaseReleased, sessionID)
	return err
}

const updateLeaseHeartbeat = `-- name: UpdateLeaseHeartbeat :exec
UPDATE leases
SET heartbeat_at = CURRENT_TIMESTAMP
WHERE session_id = ?
`

func (q *Queries) UpdateLeaseHeartbeat(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, updateLeaseHeartbeat, sessionID)
	return err
}

