// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: magic_link_tokens.sql

package sqlitestore

import (
	"context"
	"time"
)

const consumeMagicLinkToken = `-- name: ConsumeMagicLinkToken :execrows
UPDATE magic_link_tokens
SET used_at = ?
WHERE id = ? AND used_at IS NULL
`

type ConsumeMagicLinkTokenParams struct {
	UsedAt *time.Time `json:"used_at"`
	ID     string     `json:"id"`
}

func (q *Queries) ConsumeMagicLinkToken(ctx context.Context, arg ConsumeMagicLinkTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeMagicLinkToken, arg.UsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createMagicLinkToken = `-- name: CreateMagicLinkToken :one
INSERT INTO magic_link_tokens (id, token_hash, email, issued_at, expires_at, used_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, token_hash, email, issued_at, expires_at, used_at
`

type CreateMagicLinkTokenParams struct {
	ID        string     `json:"id"`
	TokenHash string     `json:"token_hash"`
	Email     string     `json:"email"`
	IssuedAt  time.Time  `json:"issued_at"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
}

func (q *Queries) CreateMagicLinkToken(ctx context.Context, arg CreateMagicLinkTokenParams) (MagicLinkToken, error) {
	row := q.db.QueryRowContext(ctx, createMagicLinkToken,
		arg.ID,
		arg.TokenHash,
		arg.Email,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.UsedAt,
	)
	var i MagicLinkToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Email,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getMagicLinkTokenByHash = `-- name: GetMagicLinkTokenByHash :one
SELECT id, token_hash, email, issued_at, expires_at, used_at
FROM magic_link_tokens
WHERE token_hash = ?
`

func (q *Queries) GetMagicLinkTokenByHash(ctx context.Context, tokenHash string) (MagicLinkToken, error) {
	row := q.db.QueryRowContext(ctx, getMagicLinkTokenByHash, tokenHash)
	var i MagicLinkToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Email,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}
