// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitestore

import (
	"database/sql"
	"time"
)

type Account struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	DisplayName  string         `json:"display_name"`
	GithubUserID sql.NullString `json:"github_user_id"`
	CreatedAt    time.Time      `json:"created_at"`
}

type ArchivedSession struct {
	SessionID        string         `json:"session_id"`
	OrgID            string         `json:"org_id"`
	Name             string         `json:"name"`
	GoalText         string         `json:"goal_text"`
	MemberAccountIds string         `json:"member_account_ids"`
	EndedAt          *time.Time     `json:"ended_at"`
	ArchivedAt       time.Time      `json:"archived_at"`
	EndReason        string         `json:"end_reason"`
	FinalBranchName  sql.NullString `json:"final_branch_name"`
}

type Event struct {
	ID        string    `json:"id"`
	OrgID     string    `json:"org_id"`
	SessionID string    `json:"session_id"`
	Seq       int64     `json:"seq"`
	Type      string    `json:"type"`
	Payload   string    `json:"payload"`
	CreatedAt time.Time `json:"created_at"`
}

type EventSeq struct {
	SessionID string `json:"session_id"`
	Next      int64  `json:"next"`
}

type MagicLinkToken struct {
	ID        string     `json:"id"`
	TokenHash string     `json:"token_hash"`
	Email     string     `json:"email"`
	IssuedAt  time.Time  `json:"issued_at"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
}

type OauthState struct {
	Nonce       string    `json:"nonce"`
	Provider    string    `json:"provider"`
	RedirectUri string    `json:"redirect_uri"`
	CreatedAt   time.Time `json:"created_at"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type OauthToken struct {
	ID         string     `json:"id"`
	AccountID  string     `json:"account_id"`
	TokenHash  string     `json:"token_hash"`
	Kind       string     `json:"kind"`
	IssuedAt   time.Time  `json:"issued_at"`
	ExpiresAt  time.Time  `json:"expires_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
}

type Org struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}

type OrgInvite struct {
	ID                  string         `json:"id"`
	OrgID               string         `json:"org_id"`
	InviterAccountID    string         `json:"inviter_account_id"`
	RecipientEmail      string         `json:"recipient_email"`
	TokenHash           string         `json:"token_hash"`
	CreatedAt           time.Time      `json:"created_at"`
	ExpiresAt           time.Time      `json:"expires_at"`
	AcceptedAt          *time.Time     `json:"accepted_at"`
	AcceptedByAccountID sql.NullString `json:"accepted_by_account_id"`
}

type OrgMember struct {
	OrgID     string    `json:"org_id"`
	AccountID string    `json:"account_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type Presence struct {
	OrgID        string    `json:"org_id"`
	SessionID    string    `json:"session_id"`
	AccountID    string    `json:"account_id"`
	Ref          string    `json:"ref"`
	CurrentSha   string    `json:"current_sha"`
	LastActiveAt time.Time `json:"last_active_at"`
}

type RefMode struct {
	SessionID string `json:"session_id"`
	Ref       string `json:"ref"`
	Mode      string `json:"mode"`
}

type Session struct {
	ID                        string         `json:"id"`
	OrgID                     string         `json:"org_id"`
	Name                      string         `json:"name"`
	Goal                      string         `json:"goal"`
	WritableScope             string         `json:"writable_scope"`
	DefaultMode               string         `json:"default_mode"`
	BaseSha                   *string        `json:"base_sha"`
	Status                    string         `json:"status"`
	CreatedAt                 time.Time      `json:"created_at"`
	EndedAt                   *time.Time     `json:"ended_at"`
	EndReason                 sql.NullString `json:"end_reason"`
	FinalizeLockedByAccountID sql.NullString `json:"finalize_locked_by_account_id"`
}

type SessionMember struct {
	OrgID     string    `json:"org_id"`
	SessionID string    `json:"session_id"`
	AccountID string    `json:"account_id"`
	Role      string    `json:"role"`
	JoinedAt  time.Time `json:"joined_at"`
}
