// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlitestore

import (
	"database/sql"
	"time"
)

type Account struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	DisplayName  string         `json:"display_name"`
	GithubUserID sql.NullString `json:"github_user_id"`
	CreatedAt    time.Time      `json:"created_at"`
	IsAnonymous  int64          `json:"is_anonymous"`
}

type ArchivedSession struct {
	SessionID        string         `json:"session_id"`
	OrgID            string         `json:"org_id"`
	Name             string         `json:"name"`
	GoalText         string         `json:"goal_text"`
	MemberAccountIds string         `json:"member_account_ids"`
	EndedAt          *time.Time     `json:"ended_at"`
	ArchivedAt       time.Time      `json:"archived_at"`
	EndReason        string         `json:"end_reason"`
	FinalBranchName  sql.NullString `json:"final_branch_name"`
}

type Comment struct {
	ID                  string         `json:"id"`
	OrgID               string         `json:"org_id"`
	SessionID           string         `json:"session_id"`
	AuthorAccountID     string         `json:"author_account_id"`
	AuthorKind          string         `json:"author_kind"`
	AnchorCommitSha     string         `json:"anchor_commit_sha"`
	AnchorFilePath      sql.NullString `json:"anchor_file_path"`
	AnchorLineStart     sql.NullInt64  `json:"anchor_line_start"`
	AnchorLineEnd       sql.NullInt64  `json:"anchor_line_end"`
	Body                string         `json:"body"`
	AddressedTo         sql.NullString `json:"addressed_to"`
	Kind                string         `json:"kind"`
	CreatedAt           time.Time      `json:"created_at"`
	ResolvedAt          sql.NullTime   `json:"resolved_at"`
	ResolvedByAccountID sql.NullString `json:"resolved_by_account_id"`
	ResolutionNote      sql.NullString `json:"resolution_note"`
}

type ConflictEvent struct {
	ID                 string         `json:"id"`
	OrgID              string         `json:"org_id"`
	SessionID          string         `json:"session_id"`
	SourceCommit       string         `json:"source_commit"`
	DraftTip           string         `json:"draft_tip"`
	Ancestor           string         `json:"ancestor"`
	Conflicts          string         `json:"conflicts"`
	AddressedTo        string         `json:"addressed_to"`
	Status             string         `json:"status"`
	ResolvingCommitSha sql.NullString `json:"resolving_commit_sha"`
	CreatedAt          time.Time      `json:"created_at"`
	ResolvedAt         sql.NullTime   `json:"resolved_at"`
}

type Event struct {
	ID        string    `json:"id"`
	OrgID     string    `json:"org_id"`
	SessionID string    `json:"session_id"`
	Seq       int64     `json:"seq"`
	Type      string    `json:"type"`
	Payload   string    `json:"payload"`
	CreatedAt time.Time `json:"created_at"`
}

type EventSeq struct {
	SessionID string `json:"session_id"`
	Next      int64  `json:"next"`
}

type FinalizeLock struct {
	ID                  string         `json:"id"`
	OrgID               string         `json:"org_id"`
	SessionID           string         `json:"session_id"`
	AcquiredByAccountID string         `json:"acquired_by_account_id"`
	AcquiredAt          time.Time      `json:"acquired_at"`
	LastActivityAt      time.Time      `json:"last_activity_at"`
	SelectedCommitShas  string         `json:"selected_commit_shas"`
	TargetBranch        string         `json:"target_branch"`
	BaseSha             *string        `json:"base_sha"`
	Mode                string         `json:"mode"`
	CommitMessage       sql.NullString `json:"commit_message"`
	SupersededByLockID  sql.NullString `json:"superseded_by_lock_id"`
	ReleasedAt          *time.Time     `json:"released_at"`
}

type Lease struct {
	SessionID    string     `json:"session_id"`
	PodID        string     `json:"pod_id"`
	FencingToken int64      `json:"fencing_token"`
	AcquiredAt   time.Time  `json:"acquired_at"`
	ReleasedAt   *time.Time `json:"released_at"`
	HeartbeatAt  time.Time  `json:"heartbeat_at"`
}

type MagicLinkToken struct {
	ID        string     `json:"id"`
	TokenHash string     `json:"token_hash"`
	Email     string     `json:"email"`
	IssuedAt  time.Time  `json:"issued_at"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
}

type OauthState struct {
	Nonce       string    `json:"nonce"`
	Provider    string    `json:"provider"`
	RedirectUri string    `json:"redirect_uri"`
	CreatedAt   time.Time `json:"created_at"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type OauthToken struct {
	ID         string         `json:"id"`
	AccountID  string         `json:"account_id"`
	TokenHash  string         `json:"token_hash"`
	Kind       string         `json:"kind"`
	SessionID  sql.NullString `json:"session_id"`
	IssuedAt   time.Time      `json:"issued_at"`
	ExpiresAt  time.Time      `json:"expires_at"`
	LastUsedAt *time.Time     `json:"last_used_at"`
	RevokedAt  *time.Time     `json:"revoked_at"`
}

type Org struct {
	ID                  string    `json:"id"`
	Name                string    `json:"name"`
	Slug                string    `json:"slug"`
	CreatedAt           time.Time `json:"created_at"`
	SessionInvitePolicy string    `json:"session_invite_policy"`
	OrgProtected        int64     `json:"org_protected"`
}

type OrgInvite struct {
	ID                  string         `json:"id"`
	OrgID               string         `json:"org_id"`
	InviterAccountID    string         `json:"inviter_account_id"`
	RecipientEmail      string         `json:"recipient_email"`
	TokenHash           string         `json:"token_hash"`
	CreatedAt           time.Time      `json:"created_at"`
	ExpiresAt           time.Time      `json:"expires_at"`
	AcceptedAt          *time.Time     `json:"accepted_at"`
	AcceptedByAccountID sql.NullString `json:"accepted_by_account_id"`
}

type OrgMember struct {
	OrgID     string    `json:"org_id"`
	AccountID string    `json:"account_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type Presence struct {
	OrgID        string    `json:"org_id"`
	SessionID    string    `json:"session_id"`
	AccountID    string    `json:"account_id"`
	Ref          string    `json:"ref"`
	CurrentSha   string    `json:"current_sha"`
	LastActiveAt time.Time `json:"last_active_at"`
}

type RefMode struct {
	SessionID string `json:"session_id"`
	Ref       string `json:"ref"`
	Mode      string `json:"mode"`
}

type Session struct {
	ID                        string         `json:"id"`
	OrgID                     string         `json:"org_id"`
	Name                      string         `json:"name"`
	Goal                      string         `json:"goal"`
	WritableScope             string         `json:"writable_scope"`
	DefaultMode               string         `json:"default_mode"`
	BaseSha                   *string        `json:"base_sha"`
	Status                    string         `json:"status"`
	CreatedAt                 time.Time      `json:"created_at"`
	EndedAt                   *time.Time     `json:"ended_at"`
	EndReason                 sql.NullString `json:"end_reason"`
	FinalizeLockedByAccountID sql.NullString `json:"finalize_locked_by_account_id"`
	LastSubstantiveActivityAt sql.NullTime   `json:"last_substantive_activity_at"`
	HardCapAt                 sql.NullTime   `json:"hard_cap_at"`
	IdleTimeoutAt             sql.NullTime   `json:"idle_timeout_at"`
}

type SessionInvite struct {
	ID                  string         `json:"id"`
	OrgID               string         `json:"org_id"`
	SessionID           string         `json:"session_id"`
	InviterAccountID    string         `json:"inviter_account_id"`
	InviteeEmail        string         `json:"invitee_email"`
	TokenHash           string         `json:"token_hash"`
	CreatedAt           time.Time      `json:"created_at"`
	ExpiresAt           time.Time      `json:"expires_at"`
	AcceptedAt          *time.Time     `json:"accepted_at"`
	AcceptedByAccountID sql.NullString `json:"accepted_by_account_id"`
}

type SessionMember struct {
	OrgID     string    `json:"org_id"`
	SessionID string    `json:"session_id"`
	AccountID string    `json:"account_id"`
	Role      string    `json:"role"`
	JoinedAt  time.Time `json:"joined_at"`
}

type Tombstone struct {
	SessionID       string     `json:"session_id"`
	OrgID           string     `json:"org_id"`
	MembersCount    int64      `json:"members_count"`
	CommitsCount    int64      `json:"commits_count"`
	AutoMergesCount int64      `json:"auto_merges_count"`
	DurationSeconds int64      `json:"duration_seconds"`
	EndReason       string     `json:"end_reason"`
	EndedAt         *time.Time `json:"ended_at"`
	ExpiresAt       time.Time  `json:"expires_at"`
}
