// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: oauth_state.sql

package sqlitestore

import (
	"context"
	"time"
)

const cleanupExpiredOAuthState = `-- name: CleanupExpiredOAuthState :exec
DELETE FROM oauth_state WHERE expires_at < ?
`

func (q *Queries) CleanupExpiredOAuthState(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredOAuthState, expiresAt)
	return err
}

const consumeOAuthState = `-- name: ConsumeOAuthState :one
DELETE FROM oauth_state WHERE nonce = ? RETURNING nonce, provider, redirect_uri, created_at, expires_at
`

func (q *Queries) ConsumeOAuthState(ctx context.Context, nonce string) (OauthState, error) {
	row := q.db.QueryRowContext(ctx, consumeOAuthState, nonce)
	var i OauthState
	err := row.Scan(
		&i.Nonce,
		&i.Provider,
		&i.RedirectUri,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertOAuthState = `-- name: InsertOAuthState :exec
INSERT INTO oauth_state (nonce, provider, redirect_uri, created_at, expires_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertOAuthStateParams struct {
	Nonce       string    `json:"nonce"`
	Provider    string    `json:"provider"`
	RedirectUri string    `json:"redirect_uri"`
	CreatedAt   time.Time `json:"created_at"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) InsertOAuthState(ctx context.Context, arg InsertOAuthStateParams) error {
	_, err := q.db.ExecContext(ctx, insertOAuthState,
		arg.Nonce,
		arg.Provider,
		arg.RedirectUri,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}
