// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_tokens.sql

package sqlitestore

import (
	"context"
	"time"
)

const createOAuthToken = `-- name: CreateOAuthToken :one
INSERT INTO oauth_tokens (id, account_id, token_hash, kind, issued_at, expires_at, last_used_at, revoked_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, account_id, token_hash, kind, issued_at, expires_at, last_used_at, revoked_at
`

type CreateOAuthTokenParams struct {
	ID         string     `json:"id"`
	AccountID  string     `json:"account_id"`
	TokenHash  string     `json:"token_hash"`
	Kind       string     `json:"kind"`
	IssuedAt   time.Time  `json:"issued_at"`
	ExpiresAt  time.Time  `json:"expires_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
}

func (q *Queries) CreateOAuthToken(ctx context.Context, arg CreateOAuthTokenParams) (OauthToken, error) {
	row := q.db.QueryRowContext(ctx, createOAuthToken,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.Kind,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
		arg.RevokedAt,
	)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.Kind,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getOAuthTokenByHash = `-- name: GetOAuthTokenByHash :one
SELECT id, account_id, token_hash, kind, issued_at, expires_at, last_used_at, revoked_at
FROM oauth_tokens
WHERE token_hash = ?
`

func (q *Queries) GetOAuthTokenByHash(ctx context.Context, tokenHash string) (OauthToken, error) {
	row := q.db.QueryRowContext(ctx, getOAuthTokenByHash, tokenHash)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.Kind,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listOAuthTokensForAccount = `-- name: ListOAuthTokensForAccount :many
SELECT id, account_id, token_hash, kind, issued_at, expires_at, last_used_at, revoked_at
FROM oauth_tokens
WHERE account_id = ?
ORDER BY issued_at DESC
`

func (q *Queries) ListOAuthTokensForAccount(ctx context.Context, accountID string) ([]OauthToken, error) {
	rows, err := q.db.QueryContext(ctx, listOAuthTokensForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthToken
	for rows.Next() {
		var i OauthToken
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TokenHash,
			&i.Kind,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllOAuthTokensForAccount = `-- name: RevokeAllOAuthTokensForAccount :exec
UPDATE oauth_tokens
SET revoked_at = ?
WHERE account_id = ? AND revoked_at IS NULL
`

type RevokeAllOAuthTokensForAccountParams struct {
	RevokedAt *time.Time `json:"revoked_at"`
	AccountID string     `json:"account_id"`
}

func (q *Queries) RevokeAllOAuthTokensForAccount(ctx context.Context, arg RevokeAllOAuthTokensForAccountParams) error {
	_, err := q.db.ExecContext(ctx, revokeAllOAuthTokensForAccount, arg.RevokedAt, arg.AccountID)
	return err
}

const revokeOAuthToken = `-- name: RevokeOAuthToken :exec
UPDATE oauth_tokens
SET revoked_at = ?
WHERE id = ?
`

type RevokeOAuthTokenParams struct {
	RevokedAt *time.Time `json:"revoked_at"`
	ID        string     `json:"id"`
}

func (q *Queries) RevokeOAuthToken(ctx context.Context, arg RevokeOAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeOAuthToken, arg.RevokedAt, arg.ID)
	return err
}

const touchOAuthTokenLastUsed = `-- name: TouchOAuthTokenLastUsed :exec
UPDATE oauth_tokens
SET last_used_at = ?
WHERE id = ?
`

type TouchOAuthTokenLastUsedParams struct {
	LastUsedAt *time.Time `json:"last_used_at"`
	ID         string     `json:"id"`
}

func (q *Queries) TouchOAuthTokenLastUsed(ctx context.Context, arg TouchOAuthTokenLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, touchOAuthTokenLastUsed, arg.LastUsedAt, arg.ID)
	return err
}
