// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: org_members.sql

package sqlitestore

import (
	"context"
	"database/sql"
	"time"
)

const addOrgMember = `-- name: AddOrgMember :exec
INSERT INTO org_members (org_id, account_id, role, created_at)
VALUES (?, ?, ?, ?)
`

type AddOrgMemberParams struct {
	OrgID     string    `json:"org_id"`
	AccountID string    `json:"account_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error {
	_, err := q.db.ExecContext(ctx, addOrgMember,
		arg.OrgID,
		arg.AccountID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const getOrgMember = `-- name: GetOrgMember :one
SELECT org_id, account_id, role, created_at
FROM org_members
WHERE org_id = ? AND account_id = ?
`

type GetOrgMemberParams struct {
	OrgID     string `json:"org_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRowContext(ctx, getOrgMember, arg.OrgID, arg.AccountID)
	var i OrgMember
	err := row.Scan(
		&i.OrgID,
		&i.AccountID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT a.id, a.email, a.display_name, a.github_user_id, a.created_at,
       om.role, om.created_at AS joined_at
FROM accounts a
JOIN org_members om ON om.account_id = a.id
WHERE om.org_id = ?
ORDER BY om.created_at ASC
`

type ListOrgMembersRow struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	DisplayName  string         `json:"display_name"`
	GithubUserID sql.NullString `json:"github_user_id"`
	CreatedAt    time.Time      `json:"created_at"`
	Role         string         `json:"role"`
	JoinedAt     time.Time      `json:"joined_at"`
}

func (q *Queries) ListOrgMembers(ctx context.Context, orgID string) ([]ListOrgMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgMembersRow
	for rows.Next() {
		var i ListOrgMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.GithubUserID,
			&i.CreatedAt,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsForAccount = `-- name: ListOrgsForAccount :many
SELECT o.id, o.name, o.slug, o.created_at, o.session_invite_policy, o.org_protected
FROM orgs o
JOIN org_members om ON om.org_id = o.id
WHERE om.account_id = ?
ORDER BY o.created_at ASC
`

func (q *Queries) ListOrgsForAccount(ctx context.Context, accountID string) ([]Org, error) {
	rows, err := q.db.QueryContext(ctx, listOrgsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Org
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.SessionInvitePolicy,
			&i.OrgProtected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrgMember = `-- name: RemoveOrgMember :exec
DELETE FROM org_members
WHERE org_id = ? AND account_id = ?
`

type RemoveOrgMemberParams struct {
	OrgID     string `json:"org_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeOrgMember, arg.OrgID, arg.AccountID)
	return err
}
