// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: org_invites.sql

package sqlitestore

import (
	"context"
	"database/sql"
	"time"
)

const getOrgInviteByID = `-- name: GetOrgInviteByID :one
SELECT id, org_id, inviter_account_id, recipient_email, token_hash, created_at, expires_at, accepted_at, accepted_by_account_id FROM org_invites WHERE id = ?
`

func (q *Queries) GetOrgInviteByID(ctx context.Context, id string) (OrgInvite, error) {
	row := q.db.QueryRowContext(ctx, getOrgInviteByID, id)
	var i OrgInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.InviterAccountID,
		&i.RecipientEmail,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedByAccountID,
	)
	return i, err
}

const getOrgInviteByTokenHash = `-- name: GetOrgInviteByTokenHash :one
SELECT id, org_id, inviter_account_id, recipient_email, token_hash, created_at, expires_at, accepted_at, accepted_by_account_id FROM org_invites WHERE token_hash = ?
`

func (q *Queries) GetOrgInviteByTokenHash(ctx context.Context, tokenHash string) (OrgInvite, error) {
	row := q.db.QueryRowContext(ctx, getOrgInviteByTokenHash, tokenHash)
	var i OrgInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.InviterAccountID,
		&i.RecipientEmail,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedByAccountID,
	)
	return i, err
}

const insertOrgInvite = `-- name: InsertOrgInvite :one
INSERT INTO org_invites (id, org_id, inviter_account_id, recipient_email, token_hash, created_at, expires_at, accepted_at, accepted_by_account_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, org_id, inviter_account_id, recipient_email, token_hash, created_at, expires_at, accepted_at, accepted_by_account_id
`

type InsertOrgInviteParams struct {
	ID                  string         `json:"id"`
	OrgID               string         `json:"org_id"`
	InviterAccountID    string         `json:"inviter_account_id"`
	RecipientEmail      string         `json:"recipient_email"`
	TokenHash           string         `json:"token_hash"`
	CreatedAt           time.Time      `json:"created_at"`
	ExpiresAt           time.Time      `json:"expires_at"`
	AcceptedAt          *time.Time     `json:"accepted_at"`
	AcceptedByAccountID sql.NullString `json:"accepted_by_account_id"`
}

func (q *Queries) InsertOrgInvite(ctx context.Context, arg InsertOrgInviteParams) (OrgInvite, error) {
	row := q.db.QueryRowContext(ctx, insertOrgInvite,
		arg.ID,
		arg.OrgID,
		arg.InviterAccountID,
		arg.RecipientEmail,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.AcceptedAt,
		arg.AcceptedByAccountID,
	)
	var i OrgInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.InviterAccountID,
		&i.RecipientEmail,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedByAccountID,
	)
	return i, err
}

const listPendingOrgInvitesForEmail = `-- name: ListPendingOrgInvitesForEmail :many
SELECT id, org_id, inviter_account_id, recipient_email, token_hash, created_at, expires_at, accepted_at, accepted_by_account_id FROM org_invites
WHERE recipient_email = ? AND accepted_at IS NULL AND expires_at > ?
ORDER BY created_at ASC
`

type ListPendingOrgInvitesForEmailParams struct {
	RecipientEmail string    `json:"recipient_email"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) ListPendingOrgInvitesForEmail(ctx context.Context, arg ListPendingOrgInvitesForEmailParams) ([]OrgInvite, error) {
	rows, err := q.db.QueryContext(ctx, listPendingOrgInvitesForEmail, arg.RecipientEmail, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgInvite
	for rows.Next() {
		var i OrgInvite
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.InviterAccountID,
			&i.RecipientEmail,
			&i.TokenHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedByAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOrgInvitesForOrg = `-- name: ListPendingOrgInvitesForOrg :many
SELECT id, org_id, inviter_account_id, recipient_email, token_hash, created_at, expires_at, accepted_at, accepted_by_account_id FROM org_invites
WHERE org_id = ? AND accepted_at IS NULL AND expires_at > ?
ORDER BY created_at ASC
`

type ListPendingOrgInvitesForOrgParams struct {
	OrgID     string    `json:"org_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) ListPendingOrgInvitesForOrg(ctx context.Context, arg ListPendingOrgInvitesForOrgParams) ([]OrgInvite, error) {
	rows, err := q.db.QueryContext(ctx, listPendingOrgInvitesForOrg, arg.OrgID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgInvite
	for rows.Next() {
		var i OrgInvite
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.InviterAccountID,
			&i.RecipientEmail,
			&i.TokenHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedByAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrgInviteAccepted = `-- name: MarkOrgInviteAccepted :exec
UPDATE org_invites
SET accepted_at = ?, accepted_by_account_id = ?
WHERE id = ? AND accepted_at IS NULL
`

type MarkOrgInviteAcceptedParams struct {
	AcceptedAt          *time.Time     `json:"accepted_at"`
	AcceptedByAccountID sql.NullString `json:"accepted_by_account_id"`
	ID                  string         `json:"id"`
}

func (q *Queries) MarkOrgInviteAccepted(ctx context.Context, arg MarkOrgInviteAcceptedParams) error {
	_, err := q.db.ExecContext(ctx, markOrgInviteAccepted, arg.AcceptedAt, arg.AcceptedByAccountID, arg.ID)
	return err
}
