// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: orgs.sql

package sqlitestore

import (
	"context"
	"time"
)

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (id, name, slug, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, name, slug, created_at, session_invite_policy, org_protected
`

type CreateOrgParams struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRowContext(ctx, createOrg,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.SessionInvitePolicy,
		&i.OrgProtected,
	)
	return i, err
}

const createProtectedOrg = `-- name: CreateProtectedOrg :one
INSERT INTO orgs (id, name, slug, session_invite_policy, created_at, org_protected)
VALUES (?, ?, ?, 'open', ?, 1)
RETURNING id, name, slug, created_at, session_invite_policy, org_protected
`

type CreateProtectedOrgParams struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}

// Inserts an org row with org_protected=true. Used at startup by the
// playground provisioning hook for the reserved `playground` org.
// Slug uniqueness is enforced by the existing UNIQUE constraint on orgs.slug.
func (q *Queries) CreateProtectedOrg(ctx context.Context, arg CreateProtectedOrgParams) (Org, error) {
	row := q.db.QueryRowContext(ctx, createProtectedOrg,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.SessionInvitePolicy,
		&i.OrgProtected,
	)
	return i, err
}

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, name, slug, created_at, session_invite_policy, org_protected
FROM orgs
WHERE id = ?
`

func (q *Queries) GetOrgByID(ctx context.Context, id string) (Org, error) {
	row := q.db.QueryRowContext(ctx, getOrgByID, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.SessionInvitePolicy,
		&i.OrgProtected,
	)
	return i, err
}

const getOrgBySlug = `-- name: GetOrgBySlug :one
SELECT id, name, slug, created_at, session_invite_policy, org_protected
FROM orgs
WHERE slug = ?
`

func (q *Queries) GetOrgBySlug(ctx context.Context, slug string) (Org, error) {
	row := q.db.QueryRowContext(ctx, getOrgBySlug, slug)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.SessionInvitePolicy,
		&i.OrgProtected,
	)
	return i, err
}

const getOrgSessionInvitePolicy = `-- name: GetOrgSessionInvitePolicy :one
SELECT session_invite_policy FROM orgs WHERE id = ?
`

func (q *Queries) GetOrgSessionInvitePolicy(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getOrgSessionInvitePolicy, id)
	var session_invite_policy string
	err := row.Scan(&session_invite_policy)
	return session_invite_policy, err
}

const updateOrgSessionInvitePolicy = `-- name: UpdateOrgSessionInvitePolicy :exec
UPDATE orgs SET session_invite_policy = ? WHERE id = ?
`

type UpdateOrgSessionInvitePolicyParams struct {
	SessionInvitePolicy string `json:"session_invite_policy"`
	ID                  string `json:"id"`
}

func (q *Queries) UpdateOrgSessionInvitePolicy(ctx context.Context, arg UpdateOrgSessionInvitePolicyParams) error {
	_, err := q.db.ExecContext(ctx, updateOrgSessionInvitePolicy, arg.SessionInvitePolicy, arg.ID)
	return err
}
