// Package sqlitestore — playground_extra.go contains hand-written queries for
// the playground destruction subsystem that are not generated by sqlc because
// they require dynamic IN clauses (DeleteAccountsByIDs) or are intentional
// cross-table aggregations (CountSessionEventsByType,
// ListAnonymousSessionMemberIDs).
package sqlitestore

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
)

// ListAnonymousSessionMemberIDs returns the account_ids of all anonymous
// accounts that are members of the given session. The JOIN against accounts
// filters by is_anonymous = 1 so only playground participant accounts are
// returned.
//
// MUST be called BEFORE deleting the sessions row — the cascade removes
// session_members rows which makes this JOIN unresolvable.
func (q *Queries) ListAnonymousSessionMemberIDs(ctx context.Context, orgID, sessionID string) ([]string, error) {
	const query = `
SELECT sm.account_id
FROM session_members sm
JOIN accounts a ON a.id = sm.account_id
WHERE sm.org_id = ? AND sm.session_id = ? AND a.is_anonymous = 1
`
	rows, err := q.db.QueryContext(ctx, query, orgID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var ids []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	return ids, rows.Err()
}

// DeleteAccountsByIDs hard-deletes the account rows with the given IDs in a
// single DELETE statement using a dynamic IN clause. Safe to call with an
// empty slice (no-op). The bearers and session_members rows are already gone
// via FK CASCADE before this is called; this step removes the orphaned account
// rows themselves.
func (q *Queries) DeleteAccountsByIDs(ctx context.Context, ids []string) error {
	if len(ids) == 0 {
		return nil
	}
	placeholders := make([]string, len(ids))
	args := make([]any, len(ids))
	for i, id := range ids {
		placeholders[i] = "?"
		args[i] = id
	}
	query := fmt.Sprintf("DELETE FROM accounts WHERE id IN (%s)", strings.Join(placeholders, ", "))
	_, err := q.db.ExecContext(ctx, query, args...)
	return err
}

// CountSessionEventsByType returns the number of events for a session that
// match the given type string. Used by the destruction routine to compute
// tombstone summary stats:
//   - "commit.arrived" → commits_count
//   - "merge.succeeded" → auto_merges_count
func (q *Queries) CountSessionEventsByType(ctx context.Context, sessionID, eventType string) (int64, error) {
	const query = `SELECT COUNT(*) FROM events WHERE session_id = ? AND type = ?`
	row := q.db.QueryRowContext(ctx, query, sessionID, eventType)
	var count int64
	err := row.Scan(&count)
	if err != nil {
		if err == sql.ErrNoRows {
			return 0, nil
		}
		return 0, err
	}
	return count, nil
}
