// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitestore

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error
	AddSessionMember(ctx context.Context, arg AddSessionMemberParams) error
	ConsumeMagicLinkToken(ctx context.Context, arg ConsumeMagicLinkTokenParams) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateMagicLinkToken(ctx context.Context, arg CreateMagicLinkTokenParams) (MagicLinkToken, error)
	CreateOAuthToken(ctx context.Context, arg CreateOAuthTokenParams) (OauthToken, error)
	CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetAccountByGitHubUserID(ctx context.Context, githubUserID sql.NullString) (Account, error)
	GetAccountByID(ctx context.Context, id string) (Account, error)
	GetMagicLinkTokenByHash(ctx context.Context, tokenHash string) (MagicLinkToken, error)
	GetOAuthTokenByHash(ctx context.Context, tokenHash string) (OauthToken, error)
	GetOrgByID(ctx context.Context, id string) (Org, error)
	GetOrgBySlug(ctx context.Context, slug string) (Org, error)
	GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrgMember, error)
	GetSession(ctx context.Context, arg GetSessionParams) (Session, error)
	GetSessionMember(ctx context.Context, arg GetSessionMemberParams) (SessionMember, error)
	ListOAuthTokensForAccount(ctx context.Context, accountID string) ([]OauthToken, error)
	ListOrgMembers(ctx context.Context, orgID string) ([]ListOrgMembersRow, error)
	ListOrgsForAccount(ctx context.Context, accountID string) ([]Org, error)
	ListSessionMembers(ctx context.Context, arg ListSessionMembersParams) ([]SessionMember, error)
	// Intentional cross-org exception: returns sessions across all orgs for the
	// authenticated account. The caller receives org_id on each row so it can
	// route further org-scoped queries correctly. This is the only query in this
	// file that does not restrict by org_id in WHERE.
	ListSessionMembershipsForAccount(ctx context.Context, accountID string) ([]ListSessionMembershipsForAccountRow, error)
	ListSessionsForOrg(ctx context.Context, orgID string) ([]Session, error)
	RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error
	RemoveSessionMember(ctx context.Context, arg RemoveSessionMemberParams) error
	RevokeAllOAuthTokensForAccount(ctx context.Context, arg RevokeAllOAuthTokensForAccountParams) error
	RevokeOAuthToken(ctx context.Context, arg RevokeOAuthTokenParams) error
	SetSessionBaseSHA(ctx context.Context, arg SetSessionBaseSHAParams) error
	TouchOAuthTokenLastUsed(ctx context.Context, arg TouchOAuthTokenLastUsedParams) error
	UpdateAccountDisplayName(ctx context.Context, arg UpdateAccountDisplayNameParams) error
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error
}

var _ Querier = (*Queries)(nil)
