// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitestore

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error
	AddSessionMember(ctx context.Context, arg AddSessionMemberParams) error
	AllocateNextSeq(ctx context.Context, sessionID string) (int64, error)
	AllocateNextSeqN(ctx context.Context, arg AllocateNextSeqNParams) (int64, error)
	CleanupExpiredOAuthState(ctx context.Context, expiresAt time.Time) error
	ClearFinalizeLock(ctx context.Context, arg ClearFinalizeLockParams) error
	ConsumeMagicLinkToken(ctx context.Context, arg ConsumeMagicLinkTokenParams) error
	ConsumeOAuthState(ctx context.Context, nonce string) (OauthState, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateMagicLinkToken(ctx context.Context, arg CreateMagicLinkTokenParams) (MagicLinkToken, error)
	CreateOAuthToken(ctx context.Context, arg CreateOAuthTokenParams) (OauthToken, error)
	CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteSession(ctx context.Context, arg DeleteSessionParams) error
	EnsureEventSeqRow(ctx context.Context, sessionID string) error
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetAccountByGitHubUserID(ctx context.Context, githubUserID sql.NullString) (Account, error)
	GetAccountByID(ctx context.Context, id string) (Account, error)
	GetArchivedSession(ctx context.Context, arg GetArchivedSessionParams) (ArchivedSession, error)
	GetMagicLinkTokenByHash(ctx context.Context, tokenHash string) (MagicLinkToken, error)
	GetOAuthTokenByHash(ctx context.Context, tokenHash string) (OauthToken, error)
	GetOrgByID(ctx context.Context, id string) (Org, error)
	GetOrgBySlug(ctx context.Context, slug string) (Org, error)
	GetOrgInviteByID(ctx context.Context, id string) (OrgInvite, error)
	GetOrgInviteByTokenHash(ctx context.Context, tokenHash string) (OrgInvite, error)
	GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrgMember, error)
	GetRefMode(ctx context.Context, arg GetRefModeParams) (RefMode, error)
	GetSession(ctx context.Context, arg GetSessionParams) (Session, error)
	GetSessionMember(ctx context.Context, arg GetSessionMemberParams) (SessionMember, error)
	InsertArchivedSession(ctx context.Context, arg InsertArchivedSessionParams) error
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertOAuthState(ctx context.Context, arg InsertOAuthStateParams) error
	InsertOrgInvite(ctx context.Context, arg InsertOrgInviteParams) (OrgInvite, error)
	ListEventsSince(ctx context.Context, arg ListEventsSinceParams) ([]Event, error)
	ListEventsSinceForDigest(ctx context.Context, arg ListEventsSinceForDigestParams) ([]Event, error)
	ListOAuthTokensForAccount(ctx context.Context, accountID string) ([]OauthToken, error)
	ListOrgMembers(ctx context.Context, orgID string) ([]ListOrgMembersRow, error)
	ListOrgsForAccount(ctx context.Context, accountID string) ([]Org, error)
	ListPendingOrgInvitesForEmail(ctx context.Context, arg ListPendingOrgInvitesForEmailParams) ([]OrgInvite, error)
	ListPendingOrgInvitesForOrg(ctx context.Context, arg ListPendingOrgInvitesForOrgParams) ([]OrgInvite, error)
	ListPresenceForSession(ctx context.Context, sessionID string) ([]Presence, error)
	ListRefModesForSession(ctx context.Context, sessionID string) ([]RefMode, error)
	ListSessionMembers(ctx context.Context, arg ListSessionMembersParams) ([]SessionMember, error)
	// Intentional cross-org exception: returns sessions across all orgs for the
	// authenticated account. The caller receives org_id on each row so it can
	// route further org-scoped queries correctly. This is the only query in this
	// file that does not restrict by org_id in WHERE.
	ListSessionMembershipsForAccount(ctx context.Context, accountID string) ([]ListSessionMembershipsForAccountRow, error)
	ListSessionsForOrg(ctx context.Context, orgID string) ([]Session, error)
	ListSessionsForOrgWithCursor(ctx context.Context, arg ListSessionsForOrgWithCursorParams) ([]Session, error)
	MarkOrgInviteAccepted(ctx context.Context, arg MarkOrgInviteAcceptedParams) error
	RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error
	RemoveSessionMember(ctx context.Context, arg RemoveSessionMemberParams) error
	RevokeAllOAuthTokensForAccount(ctx context.Context, arg RevokeAllOAuthTokensForAccountParams) error
	RevokeOAuthToken(ctx context.Context, arg RevokeOAuthTokenParams) error
	SetFinalizeLock(ctx context.Context, arg SetFinalizeLockParams) error
	SetSessionBaseSHA(ctx context.Context, arg SetSessionBaseSHAParams) error
	SetSessionEndReason(ctx context.Context, arg SetSessionEndReasonParams) error
	TouchOAuthTokenLastUsed(ctx context.Context, arg TouchOAuthTokenLastUsedParams) error
	UpdateAccountDisplayName(ctx context.Context, arg UpdateAccountDisplayNameParams) error
	UpdateSessionGoalScopeMode(ctx context.Context, arg UpdateSessionGoalScopeModeParams) error
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error
	UpsertPresence(ctx context.Context, arg UpsertPresenceParams) error
	UpsertRefMode(ctx context.Context, arg UpsertRefModeParams) error
}

var _ Querier = (*Queries)(nil)
