// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: session_members.sql

package sqlitestore

import (
	"context"
	"time"
)

const addSessionMember = `-- name: AddSessionMember :exec
INSERT INTO session_members (org_id, session_id, account_id, role, joined_at)
VALUES (?, ?, ?, ?, ?)
`

type AddSessionMemberParams struct {
	OrgID     string    `json:"org_id"`
	SessionID string    `json:"session_id"`
	AccountID string    `json:"account_id"`
	Role      string    `json:"role"`
	JoinedAt  time.Time `json:"joined_at"`
}

func (q *Queries) AddSessionMember(ctx context.Context, arg AddSessionMemberParams) error {
	_, err := q.db.ExecContext(ctx, addSessionMember,
		arg.OrgID,
		arg.SessionID,
		arg.AccountID,
		arg.Role,
		arg.JoinedAt,
	)
	return err
}

const getSessionMember = `-- name: GetSessionMember :one
SELECT org_id, session_id, account_id, role, joined_at
FROM session_members
WHERE org_id = ? AND session_id = ? AND account_id = ?
`

type GetSessionMemberParams struct {
	OrgID     string `json:"org_id"`
	SessionID string `json:"session_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) GetSessionMember(ctx context.Context, arg GetSessionMemberParams) (SessionMember, error) {
	row := q.db.QueryRowContext(ctx, getSessionMember, arg.OrgID, arg.SessionID, arg.AccountID)
	var i SessionMember
	err := row.Scan(
		&i.OrgID,
		&i.SessionID,
		&i.AccountID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listSessionMembers = `-- name: ListSessionMembers :many
SELECT org_id, session_id, account_id, role, joined_at
FROM session_members
WHERE org_id = ? AND session_id = ?
ORDER BY joined_at ASC
`

type ListSessionMembersParams struct {
	OrgID     string `json:"org_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) ListSessionMembers(ctx context.Context, arg ListSessionMembersParams) ([]SessionMember, error) {
	rows, err := q.db.QueryContext(ctx, listSessionMembers, arg.OrgID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionMember
	for rows.Next() {
		var i SessionMember
		if err := rows.Scan(
			&i.OrgID,
			&i.SessionID,
			&i.AccountID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionMembershipsForAccount = `-- name: ListSessionMembershipsForAccount :many
SELECT sm.org_id, sm.session_id, sm.account_id, sm.role, sm.joined_at,
       s.name AS session_name, s.status AS session_status, s.goal AS session_goal
FROM session_members sm
JOIN sessions s ON s.id = sm.session_id
WHERE sm.account_id = ?
ORDER BY sm.joined_at DESC
`

type ListSessionMembershipsForAccountRow struct {
	OrgID         string    `json:"org_id"`
	SessionID     string    `json:"session_id"`
	AccountID     string    `json:"account_id"`
	Role          string    `json:"role"`
	JoinedAt      time.Time `json:"joined_at"`
	SessionName   string    `json:"session_name"`
	SessionStatus string    `json:"session_status"`
	SessionGoal   string    `json:"session_goal"`
}

// Intentional cross-org exception: returns sessions across all orgs for the
// authenticated account. The caller receives org_id on each row so it can
// route further org-scoped queries correctly. This is the only query in this
// file that does not restrict by org_id in WHERE.
func (q *Queries) ListSessionMembershipsForAccount(ctx context.Context, accountID string) ([]ListSessionMembershipsForAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionMembershipsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionMembershipsForAccountRow
	for rows.Next() {
		var i ListSessionMembershipsForAccountRow
		if err := rows.Scan(
			&i.OrgID,
			&i.SessionID,
			&i.AccountID,
			&i.Role,
			&i.JoinedAt,
			&i.SessionName,
			&i.SessionStatus,
			&i.SessionGoal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSessionMember = `-- name: RemoveSessionMember :exec
DELETE FROM session_members
WHERE org_id = ? AND session_id = ? AND account_id = ?
`

type RemoveSessionMemberParams struct {
	OrgID     string `json:"org_id"`
	SessionID string `json:"session_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) RemoveSessionMember(ctx context.Context, arg RemoveSessionMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeSessionMember, arg.OrgID, arg.SessionID, arg.AccountID)
	return err
}
